### ISSUE TITLE
[Bug] Error: usePayPalScriptReducer must be used within a PayPalScriptProvider

### ISSUE THREAD

**Issue by Salaahuddiin** [paypal/react-paypal-js#103]
### 🐞 Describe the Bug

`Unhandled Runtime Error
Error: usePayPalScriptReducer must be used within a PayPalScriptProvider`

### 🔬 Minimal Reproduction

(settings: react / nextjs)

I simply add the context in _app.js :
`        <PayPalScriptProvider options={{ 'client-id': 'test' }}>
          <Page>
            <Component {...pageProps} />
          </Page>
        </PayPalScriptProvider>`

I add the PayPal button into a component.

### 😕 Actual Behavior

And then everything bugs, error message: 
```
Unhandled Runtime Error
Error: usePayPalScriptReducer must be used within a PayPalScriptProvider
```

I don't even use this hook. Even by adding it somewhere, same issue. No way so far to use this service...

**Comment by gregjopa** [comment]
Hey @Salaahuddiin this error usually happens when trying to render the `<PayPalButtons />` component (or any other sdk component) outside of the `<PayPalScriptProvider />`. 

Can you share a full reproduction of the problem? Perhaps you can create an example github repo or use codesandbox.io.

**Comment by gregjopa** [comment]
Hi @Salaahuddiin I'm going to close this out. Please reopen with a reproduction if this is still a problem.
