### ISSUE TITLE
[Bug] Error: Window closed before response

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/react-paypal-js#104]
This bug is understandable when we implement the script tag directly, but using it as a react app, it's just weird. If a user closes the tab before PayPal receives some action back, it throws this error.

It wouldn't be a problem for small projects, but for big ones, it's a nightmare and doesn't provide any benefit (in my point of view).

Wouldn't it be a good idea to remove it?

**Comment by gregjopa** [comment]
@pedroapfilho can you provide a reproduction of this error with the latest version of this library? We recently added error handling where I wouldn’t expect this error to show anymore.

**Comment by pedroapfilho** [comment]
Alright, I'll update the code to the latest, and see if it continues. If not, I'll close this issue! Thanks!

**Comment by gregjopa** [comment]
I'm going to close this one out. @pedroapfilho please reopen if you still see this issue after upgrading.
