### ISSUE TITLE
[Bug] Checkout button not appearing

### ISSUE THREAD

**Issue by lavan350** [paypal/react-paypal-js#105]
### 🐞 Describe the Bug

Hello,

I'm writing this message because I'm trying to set up a payment processing via Paypal. Unfortunately, I wanted to use your library but I can't.

When I put my button in my form, it is displayed once but the next time I reload the page, it is not displayed at all as a button in the form. And nowhere else.

However, I think I have followed the README that you propose. I have created my Sandbox account and my app on paypal. I simply copied, afterwards, the client-id of my app.

Thankyou for your help,

### 🔬 Minimal Reproduction

The first time I load the page on my browser, I have the button that appears
![image](https://user-images.githubusercontent.com/57091903/114322171-05e33580-9b1f-11eb-9b05-e11a8dcf679f.png)

The second time, however, the button completely disappeared from the form.
![image](https://user-images.githubusercontent.com/57091903/114322242-578bc000-9b1f-11eb-84db-7fbbfaf912c4.png)

However, in the "network" field of my browser, I see the following error:
![image](https://user-images.githubusercontent.com/57091903/114322273-7e49f680-9b1f-11eb-956b-29aef696babc.png)

### 😕 Actual Behavior

Here is the code I brought to try to implement the checkout button
`
    <PayPalScriptProvider
      options={{
        'client-id':
          'AQul7weTY7xqBj4Yhp6hGDnRKONiHEfKe0itCC7IrSMlK3eQzqIGoUwPb8cP7uQa-2YF4B72xXIxrRx9',
      }}
    >
      <PayPalButtons style={{ layout: 'horizontal' }} />
    </PayPalScriptProvider>
`

### 🌍 Environment

| Software         | 
| ---------------- | 
| react-paypal-js  |
| Safari, Mozilla Firefox, Google Chrome |

**Comment by gregjopa** [comment]
Hi @lavan350 can you please share a reproduction? Perhaps you can create a github repo with an example of the problem.

I'm not able to see any helpful information from your screenshot. Are you seeing errors in your dev console?

**Comment by SurgeS** [comment]
I came across the same problem, but couldn't reproduce it in an example repo. Nothing in the console, only one cancelled request in the network tab that @lavan350 already provided.

The problem in my case was that we were not using the `PayPalScriptProvider` at the root of our app but deeper in the hierarchy. So I suppose that may have messed up the initialization somehow.  It would be nice to have this restriction mentioned more prominently in the readme with a short explanation why. (I think previous version had some error mentioning `zoid` for this issue but that disappeared after we upgraded from v4 to v6)

**Comment by gregjopa** [comment]
Thanks for more details @SurgeS. If you can create a reproduction, I'm happy to dive in to try and figure out what's going on. I know it can be tricky to create a reproduction from a large closed source React app. Is there anything specific you can share about your react implementation? For example, is it using CRA, React router, and/or Next.js?

We have the PayPalScriptProvider documented in the Readme and also have a specific Storybook story for it: https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalscriptprovider--default. I'm open to making more docs changes after we figure out the root cause of the problem.

**Comment by UsamaIrfan** [comment]
bump

**Comment by theNodeMan** [comment]
bump

**Comment by JanJanssenD** [comment]
bump

**Comment by renato-bohler** [comment]
> I came across the same problem, but couldn't reproduce it in an example repo. Nothing in the console, only one cancelled request in the network tab that @lavan350 already provided.
> 
> The problem in my case was that we were not using the `PayPalScriptProvider` at the root of our app but deeper in the hierarchy. So I suppose that may have messed up the initialization somehow. It would be nice to have this restriction mentioned more prominently in the readme with a short explanation why. (I think previous version had some error mentioning `zoid` for this issue but that disappeared after we upgraded from v4 to v6)

Had the same problem, and this fix worked for me.

**Comment by rajendrapancholi** [comment]
gp
