### ISSUE TITLE
[Bug] PreRender Button Clicks open many popup windows

### ISSUE THREAD

**Issue by gregjopa** [paypal/react-paypal-js#109]
### 🐞 Describe the Bug

When the buttons first render, clicking on them many times will result in several popup windows opening. The issue seems to go away after second render is complete. The problem is more noticeable on a slower internet connection.

<img width="1755" alt="react-prereder-many-popups-bug" src="https://user-images.githubusercontent.com/534034/117182691-4b042b80-ad9c-11eb-9480-7b0997fdf2fc.png">

### 🔬 Minimal Reproduction

Go to https://paypal.github.io/react-paypal-js/iframe.html?id=example-paypalbuttons--default&args=&viewMode=story and repeatedly click on the buttons as soon as they render. It will open up many popup windows.

### 😕 Actual Behavior

Repeatedly click on the buttons as soon as they render results in many popup windows opening.

### 🤔 Expected Behavior

Repeatedly click on the buttons as soon as they render results in only one popup window opening.

### 🌍 Environment

Happens in Chrome and Safari.

### ➕ Additional Context

It's unclear what the root cause is. I tested react-paypal-js@3 locally and see the same issue 🤔

**Comment by leogedler** [comment]
@gregjopa I found that this problem is coming from: https://github.com/paypal/paypal-checkout-components/blob/master/src/zoid/buttons/prerender.jsx#L36

I have created a PR with a solution: https://github.com/paypal/paypal-checkout-components/pull/1635

**Comment by gregjopa** [comment]
Thanks for your help with this @leogedler! I verified that this bug has been fixed in production with the JS SDK 5.0.230 release.
