### ISSUE TITLE
[Feature] Feature request: Return value

### ISSUE THREAD

**Issue by ChrisChross** [paypal/react-paypal-js#114]
### 🚀 Feature Proposal

Hey guys, first of all thanks for creating this. 
It's still active right? 

### Motivation

I wanted to know if it's possible to receive a return value after the button was pushed 
and the order created (sucessfully or not). So I would like to get a response code back
to the react app. Do you guys thinks thats possible somehow? 

### Example
const return_value = 0

    return (
        <PayPalScriptProvider options={initialOptions}>
            <PayPalButtons
        createSubscription={(data, actions) =>
            actions.subscription.create({
                plan_id: "P-XXXXX",
            }). onApprove( return_value = data.status.code )
        }
        style={{
            label: "subscribe",
        }}
    />
        </PayPalScriptProvider>
    );

Best regards
Christian Klose

**Comment by gregjopa** [comment]
Hi @ChrisChross, the `createOrder`, `createSubscription`, and `onApprove` props are callbacks that return promises. So you can add a `then` or `catch` to implement more logic around them. For example, the `createSubscription` callback gets called on button click so you can use that. Ex:

```jsx
function createSubscriptionCallback (data, actions) {
    return actions.subscription.create({
        plan_id: "P-3RX065706M349222L5IFM4I",
    })
    .then(id => {
        console.log('subscription id: ', id);
        return id;
    })
    .catch(err => {
        console.log('createSubscription failed', err);
    })
}

<PayPalButtons createSubscription={createSubscriptionCallback} />
```
