### ISSUE TITLE
[Bug] Authentication Error on 2nd Attempt

### ISSUE THREAD

**Issue by HeikoMueller** [paypal/react-paypal-js#115]
🐞 Describe the Bug
I use Smart Button in React/NextJs for creating subscriptions. Everything works as expected, but if the user closes the Paypal popup window after having logged in already (OrderId created, onShippingChangeData called), and then attempts by clicking the Paypal button for a second time, I see the following error:

Uncaught Error: Create Subscription Api response error:
{
"name": "NOT_AUTHORIZED",
"message": "Authorization failed due to insufficient permissions.",
"debug_id": "3ba3d8fcdc9e7",
"details": [
{
"issue": "PERMISSION_DENIED",
"description": "You do not have permission to access or perform operations on this resource."
}

The popup window then opens and immediately disappears. I tried tackling this with a) calling dispatch with resetOptions in onCancel and b) reloading the react component including PayPalScriptProvider without success.

Am I missing something here? Do I somehow need to cancel the orderID at onCancel manually?

🔬 Minimal Reproduction
Create a subscription checkout with @paypal/react-paypal-js, initiate checkout, log into buyer account, close Popup window and attempt checkout for a second or third time.

😕 Actual Behavior
see above

🤔 Expected Behavior
Ability to re-open the subscription checkout multiple times without loosing access rights

🌍 Environment
Browser version: Chrome Version 89.0.4389.114
OS version: OSX 11.2.3
SDK version (window.paypal.version): - @paypal/react-paypal-jss

**Comment by HeikoMueller** [comment]
Just in case anyone else is facing this issue: I finally got this solved by adding the following to onCancel

dispatch({
          type: "resetOptions",
          value: {
              ...options,
              "data-order-id": data.orderID,
},

**Comment by johan123312321** [comment]
I have exactly the same issue (both on production and sandbox environments).  Update to the last (7.0.0) version doesn't resolve the problem.
