### ISSUE TITLE
Explain how to make an async post before transaction and after success

### ISSUE THREAD

**Issue by shehzi-khan** [paypal/react-paypal-js#118]
I used PayPalButton as recommended in the documentation.
However, I have two tasks to perform.

1. Make an async Post call to our own server API  ("api/payements") to create an order in our DB and waits for the response. I use await keyword to wait for the promise to resolved.
2. Makes another aysnc post call to our own server API ("api/confirm") to update the transaction status and reciept ID from Paypal after PayPal payment is successful. I use await keyword in this call too.

However, I don't know where can I call these functions.

I tried to call first API in create Order before return action.order(), but I am not allowed to write await keyword in a callback function.
Moreover, I write second API call in create Order function, in "then" section and it makes the call regardless of  the Payment status on PayPal.
Please guide me.

```
  const registerOrder = async() =>{
      return axios?.post('/api/payments', {
            description: description,
            email: email,
            price: price,
            userId: user?.id,
      });
  }


  const createOrder = useCallback((data, actions) =>{

        const resOrder =await registerOrder()            #### I can not write await here :(

        return actions.order
            .create({
                purchase_units: [
                    {
                        amount: {
                            value: lecture.price,
                        },
                    },
                ],
            })
            .then( async(orderID) => {
                try {
                 ####### this part runs regardless of PayPal payment status
                  await axios?.post(`/api/confirm/${resOrder?.data.id}`, {receiptId: orderID})      #### I need the response of resOrder here
                } catch {
                  setPopupOpenedTrue();
                  return
                }
              return orderID;

            });
    });
```

PayPal button component:
```
import React, {useState} from "react";
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";

export default function PayPal() {

 
  return (
      <PayPalScriptProvider options={{ "client-id": "sdjfhsdjfksdhfskdjfhskdhfjskfrhsdfkhsdhfj" }}>
          <PayPalButtons createOrder={createOrder} style={{ color: "black", shape:"pill",label: "pay", layout: "horizontal" ,height:40}} />
      </PayPalScriptProvider>
  );
}

```

`

**Comment by johan123312321** [comment]
Hi, @shehzi-khan!
Try this:

```

import React, {useState} from "react";
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";

export default function PayPal() {

  const registerOrder = async() =>{
    return axios?.post('/api/payments', {
      description: description,
      email: email,
      price: price,
      userId: user?.id,
    });
  }
  
  // Will be triggered when starts transaction
  const createOrder = async (data, actions) => {

    const resOrder = await registerOrder();

    const request = {
      intent: 'capture',
      purchase_units: [
        {
          amount: {
            value: lecture.price,
          },
          // Put your invoice ID to the paypal request (it should be string), to access it later
          custom_id: resOrder['id'],
        },
      ]
    };
    return actions.order.create(request);
  }

  // Will be triggered when user approved order
  const onApproveOrder = async (data, actions) => {

    // This function captures the funds from the transaction.
    const captured = await actions.order.capture();

    // TODO: remove debug logging
    console.log(captured);

    // paypal order ID
    console.log(captured['id']);

    // your invoice ID
    console.log(captured['custom_id']);

    try {
      // this part runs regardless of PayPal payment status
      await axios?.post(`/api/confirm/${captured['id']}`, {receiptId: captured['custom_id']});  // I need the response of resOrder here
    } catch {
      setPopupOpenedTrue();
    }
  }

  return (
    <PayPalScriptProvider options={{ "client-id": "sdjfhsdjfksdhfskdjfhskdhfjskfrhsdfkhsdhfj" }}>
      <PayPalButtons
        createOrder={(data, actions) => createOrder(data, actions)}
        onApprove={(data, actions) => onApproveOrder(data, actions)}
        style={{ color: "black", shape:"pill",label: "pay", layout: "horizontal" ,height:40}}
      />
    </PayPalScriptProvider>
  );
}
```

**Comment by shehzi-khan** [comment]
I recieved following error on the line, custom_id:resOrder['id']
TypeScript error: Object is possibly 'undefined'.  TS2532

**Comment by shehzi-khan** [comment]
Also in the post request in onApproveOrder, the recieptId should be the PayPal transaction ID, and the id in the confirm API URL should be the "order ID" received in the response of registerOrder.

**Comment by shehzi-khan** [comment]
Appreciate your help by the way. :)

**Comment by shehzi-khan** [comment]
- ok I changed `resOrder['id']` to `resOrder?.data.id` and tried to `console.log(resOrder?.data.id)` displays the correct orderID. 
- Now I changed `custom_id` in `purchase_units` from `resOrder['id']` to `resOrder?.data.id` 
- `console.log(captured['id']);` displays the correct transaction ID recieved from PayPal.

:( :(
- However `console.log(captured['custom_id']);` prints "undefined" :(

**Comment by johan123312321** [comment]
Hi @shehzi-khan!

Regarding this `I recieved following error on the line, custom_id:resOrder['id']
TypeScript error: Object is possibly 'undefined'. TS2532` 
Ofc there will be error, because I don't know your data structures. I just given to you direction where to go.

Regarding this:
> However console.log(captured['custom_id']); prints "undefined" :(
Put `console.log(captured);` and explore `captured` structure in the console. Probably 'custom_id' is in some nested object.
...
ok.. I have done it for you :) 
try `console.log(captured['purchase_units'][0]['custom_id'])` to access your **orderID**;

**Comment by gregjopa** [comment]
@johan123312321 thanks answering @shehzi-khan's questions and for providing a server-side example in https://github.com/paypal/react-paypal-js/issues/118#issuecomment-856705827 💯🥇👍 

We also provide this example for server-side integrations:
- https://developer.paypal.com/demo/checkout/#/pattern/server
- https://github.com/paypal/paypal-checkout-demo/tree/master/src/app/server
