### ISSUE TITLE
shippingPreference: "NO_SHIPPING"

### ISSUE THREAD

**Issue by avi312singh** [paypal/react-paypal-js#119]
Does passing shippingPreference: "NO_SHIPPING" not work? This functionality is in third party libs but doesn't seem to be here...
`<PayPalScriptProvider options={{ "client-id": clientId, currency: "GBP", "disable-funding": "sofort", shippingPreference: "NO_SHIPPING" }}>`
Doesn't seem to have any effect at the checkout page as it still shows the delivery address
![image](https://user-images.githubusercontent.com/5769090/121269122-288f9180-c8b7-11eb-93a6-dc1ddce200d7.png)

**Comment by avi312singh** [comment]
After digging through the source code you can supply many options.. I was able to set no shipping address like this:
    ```
const createOrder = (data, actions) => {
        return actions.order
            .create({
                purchase_units: [
                    {
                        amount: {
                            value: donationAmount,
                        },
                    },
                ],
                application_context: {
                    shipping_preference: "NO_SHIPPING"
                }
            })
            .then((orderID) => {
                setOrderID(orderID);
                return orderID;
            });
    }
```

**Comment by hemengke1997** [comment]
i've used this code but no works...
