### ISSUE TITLE
HTTPS loading issue on Safari

### ISSUE THREAD

**Issue by kolber** [paypal/react-paypal-js#122]
On my current version of Desktop Safari (`Version 14.1.1 (15611.2.7.1.6, 15611)`) on OSX (`macOS 10.15.7 (19H1217)`) the PayPal buttons are hanging the browser for a noticeable amount of time (between 2-4 seconds) when loading the library.

This is especially noticeable as we are using dynamic amounts, so it will also hang every time we run a `forceReRender`.

Interestingly this only seems to happen over HTTPS, as local testing over HTTP does not have the same issues at all (but local testing over HTTPS does).

I can also verify this does not happen on Chrome or Firefox.

### 🔬 Minimal Reproduction

This can be replicated on the current example on Storybook (in Safari).
https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--dynamic-amount

First the screen locks up for quite a while loading all of the examples, and then when changing currency you can see a noticeable delay between changing the value dropdown, and the UI actually updating.

**Comment by gregjopa** [comment]
Hi @kolber thanks for the report. Does this same issue in safari happen on this demo site? https://developer.paypal.com/demo/checkout/#/pattern/client. This site does not use this react library.

I’d like to figure out if the issue is specific to this react library or if it’s an issue with the PayPal JS SDK.

**Comment by kolber** [comment]
Ahh good thinking @gregjopa. I can verify the same issue occurs here: 
https://www.paypal.com/buttons/smart?flowloggingId=7d521d04dae80

So it doesn't look like the React library directly!

**Comment by kolber** [comment]
I'm guessing I should direct my bug report elsewhere, do you know where the best place would be?

**Comment by gregjopa** [comment]
@kolber Thanks for testing it on the other websites. Please open an issue for the JS SDK team here and then the right folks will get notified: https://github.com/paypal/paypal-checkout-components/issues.
