### ISSUE TITLE
[Bug] script option 'disable-funding' not working

### ISSUE THREAD

**Issue by hermanskurichin** [paypal/react-paypal-js#123]
### 🐞 Describe the Bug

Passing script option 'disable-funding' has no effect.

### 🔬 Minimal Reproduction

```
<Fragment>
      <PayPalScriptProvider
        options={{
          vault: true,
          intent: 'subscription',
          'disable-funding': 'credit,card',
          'client-id': clientId,
        }}
      >
        <PayPalButtons
          style={{
            color: 'gold',
            shape: 'pill',
            size: 'small',
            label: 'checkout',
          }}
          createSubscription={createSubscription}
          onApprove={onApprove}
          onError={onError}
          onCancel={onCancel}
        />
      </PayPalScriptProvider>
</Fragment>
```

### 😕 Actual Behavior

Paypal checkout opens with option to use paypal account OR pay by debit/credit card.

### 🤔 Expected Behavior

Paypal checkout opens with only paypal username/password form as a payment option.  Alternative/Anonymous payments are not offered

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 1.0.0 |
| Browser          | N/A |
| Operating System | N/A |

### ➕ Additional Context

I have exactly the same setup but with options = { intent: 'capture' }  and it is working as expected.
Issue is reproducible in sandbox and live versions.

**Comment by gregjopa** [comment]
Hi @hermanskurichin the `'disable-funding': 'credit,card',` option controls what buttons are rendered. It does not control if the "Pay with Debit or Credit Card" option is shown in the popup.

**Comment by hermanskurichin** [comment]
@gabrielo91 Thank you for your reply.

Can we control payment options offered in the pop-up, we are only interested in subscribing **payer** accounts.

**Comment by ELBEQQAL94** [comment]
Hi @hermanskurichin, I think this `"disable-funding": 'credit,card'` it works for me
