### ISSUE TITLE
[Feature] Paypal Donate button

### ISSUE THREAD

**Issue by patrickliang** [paypal/react-paypal-js#124]
### 🚀 Feature Proposal

Does this library support [Paypal Donate button](https://www.paypal.com/donate/buttons)?

### Motivation

For non-profit organizations, they take donations instead of actually selling products or services, and Paypal has that Donate button option.

**Comment by TrejoCode** [comment]
Please

**Comment by gregjopa** [comment]
I'm happy to share that we just added support to the PayPal JS SDK for donations. Here's an example: https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--donate
