### ISSUE TITLE
TypeScript declaration files don’t type check

### ISSUE THREAD

**Issue by geigerzaehler** [paypal/react-paypal-js#125]
### 🐞 Describe the Bug

The TypeScript declaration files don’t type check when [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) is set to `false`.

### 🔬 Minimal Reproduction

```bash
yarn init
yarn add typescript @paypal/react-paypal-js
yarn run tsc --init
echo 'import "@paypal/react-paypal-js"' > index.ts
yarn run tsc --skipLibCheck false
```

### 😕 Actual Behavior

Typescript shows the following error

```plain
node_modules/@paypal/react-paypal-js/dist/index.d.ts:5:25 - error TS7016: Could not find a declaration file for module '@paypal/sdk-constants/dist/module'. '/home/thomas/code/play/paypal-bug/node_modules/@paypal/sdk-constants/dist/module/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/paypal__sdk-constants` if it exists or add a new declaration (.d.ts) file containing `declare module '@paypal/sdk-constants/dist/module';`

5 export { FUNDING } from "@paypal/sdk-constants/dist/module";
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
### 🤔 Expected Behavior

Typescript should not show any errors

### 🌍 Environment

* @paypal/react-paypal-js@7.1.0
* typescript@4.3.5

**Comment by gregjopa** [comment]
Hey @geigerzaehler thanks for letting us know about this type bug.

We are automatically generating the TypeScript declarations for this library: https://github.com/paypal/react-paypal-js/blob/main/tsconfig.json#L3. And that process doesn't seem to automatically include the type declarations for this "@paypal/sdk-constants/dist/module" dependency (https://github.com/paypal/react-paypal-js/blob/main/src/types.d.ts). Any suggestions on how to best fix?
