### ISSUE TITLE
[Question] How to log into sandbox environment

### ISSUE THREAD

**Issue by rever96** [paypal/react-paypal-js#128]
### 🐞 Describe the Bug

The login with paypal doesn't works

### 🔬 Minimal Reproduction

1. npm install @paypal/react-paypal-js
2. copy code:
```
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";

export default function App() {
    return (
        <PayPalScriptProvider options={{ "client-id": "test" }}>
            <PayPalButtons style={{ layout: "horizontal" }} />
        </PayPalScriptProvider>
    );
}
```
3. replace my sandbox client id
4. npm start
5. click button paypal, using correct credentials results in "Some data are incorrects. Try again"

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | ^7.1.2
| Browser          | Chrome

### ➕ Additional Context

![2021-07-08 15_49_59-React App](https://user-images.githubusercontent.com/19595534/124934894-735f0f00-e005-11eb-9a9c-9d6f87429803.png)

**Comment by gregjopa** [comment]
Hi @rever96 it looks like you are trying to log into PayPal with a production account when using a sandbox client id. When using a sandbox client id you need to login with a sandbox user. Log into https://developer.paypal.com/ and you should see a couple sandbox accounts that you can log in and test with. Here's a screenshot of that page:

<img width="1167" alt="sandbox-accounts-screenshot" src="https://user-images.githubusercontent.com/534034/124937360-edbf6d00-dfcc-11eb-98bf-799a871c03df.png">

**Comment by rever96** [comment]
I've followed this docs: https://developer.paypal.com/docs/api/overview/#get-credentials


![2021-07-08 16_30_31-Impostazioni](https://user-images.githubusercontent.com/19595534/124939983-df437680-e009-11eb-8146-410a9a27ead5.png)

is it correct?

I still have the problem

**Comment by rever96** [comment]
Maybe because I didn't set up any `data-client-token`?

**Comment by rever96** [comment]
The requests gives back 200 status

![2021-07-08 17_08_39-](https://user-images.githubusercontent.com/19595534/124946524-634c2d00-e00f-11eb-8e3a-9917c9d5a047.png)

**Comment by rever96** [comment]
I have this problem in the storybook too.
https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--default

**Comment by gregjopa** [comment]
Hi @rever96 it sounds like your questions are about how to use the PayPal sandbox environment. I recommend reaching out to paypal support for help: https://developer.paypal.com/support/.

This issue is unrelated to this react library so I'm going to close it out.

**Comment by gregjopa** [comment]
Hi @rever96 it sounds like your questions are about how to use the PayPal sandbox environment. I recommend reaching out to paypal support for help: https://developer.paypal.com/support/.

This issue is unrelated to this react library so I'm going to close it out.
