### ISSUE TITLE
Client id is not been sent

### ISSUE THREAD

**Issue by rick427** [paypal/react-paypal-js#133]
Hi, i just installed this library, followed the instructions and steps listed in the documentation, but discovered that the Paypal script was not loading. I kept getting a 400 response. Upon inspecting the network, i found out that the client-id was not been sent as a query param, even though am passing it in Provider component. What do i do pls ?.

**Comment by gregjopa** [comment]
Hi @rick427, the `client-id` is kebab-case. Does this example work for you? 

```js
import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";

<PayPalScriptProvider options={{ "client-id": "test" }}>
   <PayPalButtons
       style={{ layout: "horizontal" }}
       createOrder={(data, actions) => {
           return actions.order.create({
               purchase_units: [
                   {
                       amount: {
                           value: "2.00",
                       },
                   },
               ],
           });
       }}
   />;
</PayPalScriptProvider>
```

**Comment by rick427** [comment]
Nah didn't work, but I got it to work. Lemme explain how I did it. So the docs said "**Place <PayPalScriptProvider/> at the root of your app**" and I did just that. However the root of my app is where I declared my routes using react router dom. So i did something like so: 

```
<PayPalScriptProvider options={options}>
     <Switch>
         <Route path="/xyz" component={component}/>
     <Switch>
<PayPalScriptProvider/>
```

This led to the options not been passed to the PayPal script hence the 400 error. Probably has to with context. So I refactored the above using react router's render function like so:
     ```
    <Switch>
         <Route path="/xyz"  render={(renderProps) => (
               <PayPalScriptProvider options={options}>
                      <Component {...renderProps} />
               </PayPalScriptProvider> 
          )}/>
     <Switch>
```

Thanks for your quick response. Good stuff. Hope this helps someone :)
