### ISSUE TITLE
Error paypal sdk “react-paypal-js” and cypress

### ISSUE THREAD

**Issue by solangeDev** [paypal/react-paypal-js#134]
I have at error with cypress and paypal sdk "react-paypal-js" when I'm doing click in the paypal button I have the next error

"TypeError: o.removeEventListener is not a function" "Uncaught TypeError: Cannot read property 'stack' of null"

can it be integrated with cypress?
what would be the correct way to do it?

**Comment by gregjopa** [comment]
Hi @solangeDev, the PayPal JS SDK relies on using iframes. Cypress does not play nice with iframes and it looks like there's additional work to get it setup: https://www.cypress.io/blog/2020/02/12/working-with-iframes-in-cypress/. Could you try using Cypress with this demo page? https://developer.paypal.com/demo/checkout/. That will help us figure out if its a problem with this react library or the PayPal JS SDK in general.

**Comment by solangeDev** [comment]
Hi thanks!! I open the PayPal pop-up window, how can I access to log in? Is it possible to do this?. This window does not appear to be inside an iframe. 
this is the test, it is working, but it just pulls up the pop up and it has no iframe: 
import i18n from '@/lib/i18n';
import users from '@/cypress/fixtures/common/users';

const getIframeDocument = () => {
  return cy
  .get('[data-cy=invoice-btn-paypal]').find('iframe')
  // Cypress yields jQuery element, which has the real
  // DOM element under property "0".
  // From the real DOM iframe element we can get
  // the "document" element, it is stored in "contentDocument" property
  // Cypress "its" command can access deep properties using dot notation
  // https://on.cypress.io/its
  .its('0.contentDocument').should('exist')
}

const getIframeBody = () => {
  // get the document
  return getIframeDocument()
  // automatically retries until body is loaded
  .its('body').should('not.be.undefined')
  // wraps "body" DOM element to allow
  // chaining more Cypress commands, like ".find(...)"
  .then(cy.wrap)
}

describe('<InvoiceList />', () => {
  Cypress.on('uncaught:exception', (err, runnable) => {
    return false
  });

  before(() => {
    cy.task('db:seed:invoices');
  });

  it('<InvoiceList /> - Validate app list', () => {
    cy.login({ email: users[1].email, password: 'usertimg' });
    cy.visit('/invoices');
    cy.wait(8000);
    getIframeBody().find('#buttons-container').click()
  });
});
