### ISSUE TITLE
[Bug] Invalid "Expiry" date format

### ISSUE THREAD

**Issue by cadehammond** [paypal/react-paypal-js#136]
### 🐞 Describe the Bug

When using PayPal's HostedFields and configuring the display of those fields to include an `expirationYear` and `expirationMonth` as `<select>` elements (rather than `expirationDate`), users encounter a 400 response if they do not change the `expirationMonth` field from its default value. This is because it is being transmitted in the format `"expiry":"2021-7"` rather than `"expiry":"2021-07"`.

### 🔬 Minimal Reproduction

Field options used for setup: 
`fields: {
              number: {
                selector: '#adp-card-number',
              },
              expirationMonth: {
                selector: '#adp-expiration-month',
                select: true,
              },
              expirationYear: {
                selector: '#adp-expiration-year',
                select: true,
              },
              cvv: {
                selector: '#adp-cvv',
              },
            },
`
Once rendered, enter a Credit Card number and CVV, then submit the form leaving the date fields (Month and Year) at their defaults.

NOTE: Changing the month field to any value will result in a correctly formatted request.

### 😕 Actual Behavior

PayPal responds with a 400 status code and the following message (debug_id removed)
`
{"name":"INVALID_REQUEST","details":[{"field":"/payment_source/card/expiry","value":"2021-7","location":"body","issue":"INVALID_PARAMETER_SYNTAX","description":"the value of a field does not conform to the expected format"},{"field":"/payment_source/card/expiry","value":"2021-7","location":"body","issue":"INVALID_STRING_LENGTH","description":"The value of a field is either too short or too long"}],"message":"Request is not well-formed, syntactically incorrect, or violates schema.","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_PARAMETER_SYNTAX","rel":"information_link"},{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH","rel":"information_link"}],"debug_id":"--redacted--"}
`

### 🤔 Expected Behavior

The "expiry" field should be properly formatted whether a user changes the Month field from the default or not.

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 7.2.1 |
| Browser          | Chrome 92.0.4515.107 |
| Operating System | Mac OS 10.14.6 |

**Comment by gregjopa** [comment]
Hi @cadehammond can you share your hosted fields integration code? I'd like to reproduce the problem to better troubleshoot.

**Comment by cadehammond** [comment]
Hi @gregjopa thank you for your response!

With this being a work project (and one that is not yet available on an outside server) I can't share a demo or the source code right now. My work is based on [PayPal SDK Docs](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-reference/#hosted-fields) and I found this [reference](https://developer.paypal.com/braintree/docs/guides/hosted-fields/faq/javascript/v3#can-i-use-a-dropdown-(&lt;select&gt;)-for-a-field?) on how to split the expiration date field into Month and Year `<select>` inputs.

There is always the possibility this issue exists within the PayPal SDK itself. If that seems like the case or if there is any specific setup information I can provide, please let me know.

**Comment by cadehammond** [comment]
Hello again @gregjopa .

Just wanted to give a quick update. We attempted to use the standard text `<input>` rather than `<select>` to see if it would help. When using separate inputs for Month and Year, a user could type `7` (no leading `0`) and this would cause the same 400 error. The field is still reported as `isValid: true` in the field's state, so we have no indication that a `0` is "required".

To get this working, we've gone to a single `<input>` for the date. This implementation automatically adds the `0` for a user as they type, and the resulting post contains a correctly formatted `expiry` as a result.

I believe we would still be interested in using the separate date fields (and as `<select>` elements if possible) in the future, so I will check back on this post. Once we've gone to production with the feature, it may be possible to setup a demo for you using the desired configuration as well.

Thanks so much for looking into this!
