### ISSUE TITLE
[Bug] 'BraintreePayPalButtons' not exported

### ISSUE THREAD

**Issue by intermetric** [paypal/react-paypal-js#143]
### 🐞 Describe the Bug

The BraintreePayPalButtons component is not exported from @paypal/react-paypal-js.

### 🔬 Minimal Reproduction

Importing the component like so:
```
import { BraintreePayPalButtons } from "@paypal/react-paypal-js"
```

### 😕 Actual Behavior

Compilation failure: "Attempted import error: 'BraintreePayPalButtons' is not exported from '@paypal/react-paypal-js'".

### 🤔 Expected Behavior

The component is exported as described in the docs.

**Comment by gregjopa** [comment]
Hi @intermetric we just published 7.3.0 which includes the `<BraintreePayPalButtons />` component. Please give it a try.
