### ISSUE TITLE
[Error]: Followed the provided instruction to use PayPal Button but getting error on rendering

### ISSUE THREAD

**Issue by SatishJaiswalOZ** [paypal/react-paypal-js#162]
Error:
Error: Failed to render <PayPalButtons /> component. Failed to initialize:  InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

But when I commented, the button worked :
const initialOptions = {
  'client-id': 'Ab',
  currency: 'USD',
  intent: 'capture',
  // 'data-client-token': 'abc123xyz==',
}

Platform:
React/NextJS
Typescript

**Comment by Danicoco** [comment]
I believe there is no such option as "data-client-token".

**Comment by SatishJaiswalOZ** [comment]
> I believe there is no such option as "data-client-token".

When I used BraintreePaypalButton it asked for the same and then I had to generate through Braintree SDK. It worked finally.

**Comment by gregjopa** [comment]
Yes the `data-client-token` is required for the `<BraintreePayPalButtons />` component. @SatishJaiswalOZ good to hear your integration is working. Is it okay to close out this issue?
