### ISSUE TITLE
[Hacktoberfest] Covert PayPalMarks.test.js to TypeScript

### ISSUE THREAD

**Issue by gregjopa** [paypal/react-paypal-js#168]
We have a bunch of tests that are still using plain JavaScript even though this library is written in TypeScript.

For this issue, convert the [PayPalMarks.test.js](https://github.com/paypal/react-paypal-js/blob/main/src/components/PayPalMarks.test.js) to TypeScript.

**Comment by namit-chandwani** [comment]
Hey @gregjopa, I'd like to work on this issue. Can you please assign it to me?

**Comment by davidalpert** [comment]
you may want to wait until we merge #174 (or cherry-pick the `package.json` changes from that PR) as I ran into some missing types and a mocking library which will probably be helpful for all the test file conversions.

**Comment by namit-chandwani** [comment]
Sure, will wait.

**Comment by davidalpert** [comment]
@namit-chandwani #174 has been merged; go for it!

**Comment by yaya-usman** [comment]
@gregjopa Can I kindly get assigned this issue, if it's not yet closed

**Comment by mkirlin** [comment]
It looks like this was completed and merged with PR #203, so I'm going to go ahead and close this.
