### ISSUE TITLE
[Hacktoberfest] Covert contextValidator.test.js to TypeScript

### ISSUE THREAD

**Issue by gregjopa** [paypal/react-paypal-js#171]
We have a bunch of tests that are still using plain JavaScript even though this library is written in TypeScript.

For this issue, convert the [contextValidator.test.js](https://github.com/paypal/react-paypal-js/blob/main/src/hooks/contextValidator.test.js) to TypeScript.

**Comment by pedpess** [comment]
Hey again Greg 👋🏻 , I can take this one too. I will continue working on it in few hours

**Comment by itsdharmxd** [comment]
**@gregjopa**  can you please assign this project

**Comment by sagarchoudhary96** [comment]
@gregjopa  @itsdharmxd if it's not completed can i pick it up ?

**Comment by itsdharmxd** [comment]
> 
> 
> @gregjopa @itsdharmxd if it's not completed can i pick it up ?

sure go for it

**Comment by sagarchoudhary96** [comment]
@gregjopa once file is changed to `.ts` file it will start throwing error for invalid param type passed to the functions based on the type check. what all needs to be changed in the test FIle then ?

**Comment by sagarchoudhary96** [comment]
@gregjopa please review the PR.
