### ISSUE TITLE
[DOCS]: You guys broke my application again

### ISSUE THREAD

**Issue by TrejGun** [paypal/react-paypal-js#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

So when you released 7.3.0 you forgot to export PayPalButtonsComponentProps and broke my app
https://github.com/paypal/react-paypal-js/issues/145

now with 7.4.0 you suddenly renamed DISPATCH_ACTION to SCRIPT_PROVIDER_DISPATCH_ACTION
and broke my app again. you don't even put this into the changelog

what kind of financial software is this?!

**Comment by gregjopa** [comment]
Good catch @TrejGun! This was an accident and we shouldn't be renaming any public types without doing a major version release. Sorry about the troubles. Working on releasing a fix #192.

**Comment by meowdao** [comment]
what a shame!

**Comment by gregjopa** [comment]
This is fixed with 7.4.1
