### ISSUE TITLE
[BUG]: PayPalHostedFieldsProvider is not working

### ISSUE THREAD

**Issue by lu-cruz** [paypal/react-paypal-js#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I'm having some issues with PayPalHostedFieldsProvider.
I followed exactly what is in the example, getting no errors, but it´s showing nothing.
Here is the code:
```
  const options = {
    currency: 'USD',
    components: 'hosted-fields',
    intent: 'capture',
    'client-id': 'xxxxxxxx',
    'data-client-token': 'xxxxxxxx',
  };

    <PayPalScriptProvider options={options}>
      <PayPalHostedFieldsProvider
        createOrder={() => {
          // Here define the call to create and order
          return (
            fetch('/your-server-side-integration-endpoint/orders')
              .then((response) => response.json())
              // .then((order) => order.id)
              .catch((err) => {
                // Handle any error
                console.log(err);
              })
          );
        }}
      >
        <PayPalHostedField
          id="card-number"
          hostedFieldType="number"
          options={{ selector: '#card-number' }}
        />
        <PayPalHostedField
          id="cvv"
          hostedFieldType="cvv"
          options={{ selector: '#cvv' }}
        />
        <PayPalHostedField
          id="expiration-month"
          hostedFieldType="expirationMonth"
          options={{ selector: '#expiration-month', placeholder: 'MM' }}
        />
        <PayPalHostedField
          id="expiration-year"
          hostedFieldType="expiration"
          options={{ selector: '#expiration-year', placeholder: 'YYYY' }}
        />
      </PayPalHostedFieldsProvider>
    </PayPalScriptProvider>

```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anarerdene** [comment]
@lu-cruz did you fix this issue. Same here :(

**Comment by lu-cruz** [comment]
> @lu-cruz did you fix this issue. Same here :(

Unfortunately not yet...
Just waiting for answers

**Comment by borodovisin** [comment]
Good morning @lu-cruz, please can you define a custom error component and pass it to the `PayPalHostedFieldsProvider`. I mean something like this:

```js
const NotEligible = () => (<div>Your account is not eligible</div>);

<PayPalHostedFieldsProvider notEligibleError={<NotEligible />} />
```

To check if your account is eligible to use hosted fields?

**Comment by lu-cruz** [comment]
Hey, @borodovisin morning thanks for the response! I'm getting this notEligibleError right now...
So what should I do to make my account eligible to use these fields?

**Comment by borodovisin** [comment]
Hi @lu-cruz, you're right. If the account you're using is ineligible, you won't be able to use the HostedFields. 
You need to use an eligible `client-id` to make the HostedFields works...

**Comment by borodovisin** [comment]
Hi @lu-cruz, HostedFields is disabled by default. You need to follow this guide: 
https://developer.paypal.com/docs/checkout/advanced/integrate/

Please be aware of this section: **Enable your account**
<img width="850" alt="enable_account" src="https://user-images.githubusercontent.com/26287838/140101117-47e70c2b-5de0-4ccf-a1fb-c6e2728fd8c8.png">

**Comment by lu-cruz** [comment]
Thank you very much! @borodovisin
