### ISSUE TITLE
[BUG]: startsWith of null or undefined

### ISSUE THREAD

**Issue by ntekka** [paypal/react-paypal-js#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Paypal Messages stopped working, I think paypal SDK upgraded and introduced a new property for 'account' which broke the existing message component.  

```
TypeError: String.prototype.startsWith called on null or undefined
    at startsWith (<anonymous>)
    at Object.decorate (VM175 js:1)
    at VM175 js:1
    at Vr (VM175 js:1)
    at VM175 js:1
    at Object.Je [as setProps] (VM175 js:1)
    at Object.e [as init] (VM175 js:1)
    at t (VM175 js:1)
    at Na (VM175 js:1)
    at ka (VM175 js:1)
```

### 🔬 Minimal Reproduction

```markdown
reproducible on the storybook demo as of 11/01/2021. https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalmessages--default
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregjopa** [comment]
Hi @ntekka thanks for reporting this issue. We rolled the JS SDK back (`5.0.268 => 5.0.267`) to resolve this issue with the messaging component. It should be working again with version 5.0.267. Please re-open if you are still having issues.
