### ISSUE TITLE
[BUG]: OnApproveActions doesn't cater to subscriptions

### ISSUE THREAD

**Issue by AJDowds** [paypal/react-paypal-js#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

type onApproveActions seems to only be applicable to standard orders and not subscriptions:

```
export type OnApproveActions = {
    order: {
        capture: () => Promise<OrderResponseBody>;
        authorize: () => Promise<OrderResponseBody>;
    };
    redirect: (redirectURL: string) => void;
    restart: () => void;
};
```

where the paypal response for a subscription onApprove looks like this:

![image](https://user-images.githubusercontent.com/11509307/139919375-e613a3ae-ddf7-4ea7-88c7-338ca067a06d.png)

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |   7.4.2    |
| Browser          |   Brave    |
| Operating System |   Windows  |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkirlin** [comment]
Hey @AJDowds! I'm a member of PayPal's devrel team. Thanks for your patience on this; I know it's been a while. I've talked to the team that maintains this project; they've created tickets for it, and they're hoping to get them completed during the first sprint in January. I'll follow up with them on Jan. 10 and let you know what the status is.

**Comment by borodovisin** [comment]
Hi @mkirlin and @AJDowds here is work progress related to this issue: https://github.com/paypal/paypal-js/pull/140.

Still waiting for feedback and any concern about this change.

**Comment by mkirlin** [comment]
Hey @AJDowds! Looks like @borodovisin was got the fix for this merged a few days back, so I'm going to go ahead and close this issue. Please reopen if you continue to run into this problem. We appreciate your patience on this!
