### ISSUE TITLE
[BUG]: onApprove callback is not invoked on new subscription, sometimes

### ISSUE THREAD

**Issue by jhg023** [paypal/react-paypal-js#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

The `onApprove` callback is only firing sometimes, which results in subscriptions (recurring payments) being created on PayPal's end, yet not allowing me to communicate with my service that a new subscription has been created.

This issue is affecting my production (live, non-sandbox) environment.

### 😕 Current Behavior

The `onApprove` callback only fires some of the time new subscriptions are created.

### 🤔 Expected Behavior

The `onApprove` callback fires every time a new subscription is created.

### 🔬 Minimal Reproduction

```markdown
N/A
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 7.4.2      |
| Browser          | N/A        |
| Operating System | N/A        |
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sgarg17** [comment]
@jhg023 did you happen to find any workarounds or resolution for this issue? We're hitting this in sandbox and concerned about the production implications

**Comment by jhg023** [comment]
@sgarg17 I did, actually.

My goal was to create a mapping from a user's ID to their respective PayPal subscription ID, and I initially added the logic in the `onApprove` block.

However, because `onApprove` is not always invoked, I moved the logic into the `createSubscription` block, as the PayPal subscription ID is available there as well.

Here's our updated React code:

```typescript
<PayPalButtons
  //eslint-disable-next-line @typescript-eslint/no-explicit-any
  createSubscription={(_: any, actions: any) => {
    return actions.subscription
      .create({
        plan_id: planId,
      })
      .then((subscriptionId: string) => {
        return new Promise<string>((resolve) => {
          processSubscription(
            JSON.stringify({
              planId: planId,
              subscriptionID: subscriptionId,
            })
          )
          .catch((error: AxiosError) => {
            setErrorMessage(error.response?.data ?? error.message);
          })
          .finally(() => resolve(subscriptionId));
        });
      });
  }}
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  onApprove={() => {
    onSubscriptionSuccess();
    return Promise.resolve();
  }}
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  onError={(error: any) => {
    setErrorMessage(error.message);
  }}
/>
```

**Comment by mkirlin** [comment]
Hey @jhg023 ! I'm a member of PayPal's devrel team. Thanks for your patience on this; I know it's been a while. I've talked to the team that maintains this project; they've created tickets for it, and they're hoping to get them completed during the first sprint in January. I'll follow up with them on Jan. 10 and let you know what the status is.

**Comment by Arebisc** [comment]
@mkirlin any update? I've also faced this issue on live environment.

**Comment by mkirlin** [comment]
Hey @Arebisc! This work is in progress in our current sprint; we're hoping to have it completed on or before the 18th.

**Comment by borodovisin** [comment]
Hi @jhg023, a new SDK release is available `paypal version: 280`.

Please, can you test it again with the latest release of the PayPal SDK and give us feedback if the problem did disappear?

If this is not an issue anymore,  please feel free to close it. 👍

**Comment by mkirlin** [comment]
Hey folks! This issue has been quiet for three weeks now and I believe it is fixed, so I'm going to go ahead and close it. @jhg023, if you're still having issues, please reopen or create a new issue. Thanks!
