### ISSUE TITLE
[BUG]: White background clips around PayPalButtons

### ISSUE THREAD

**Issue by alex-r89** [paypal/react-paypal-js#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I seem to be unable to change the background color of `PayPalButtons` component, which is causing a white clipping to be visible around the Paypal button (image attached).

### 😕 Current Behavior

When using the `PayPalButtons`, a white background is visible around them

<img width="908" alt="Screenshot 2021-12-30 at 1 05 23 pm" src="https://user-images.githubusercontent.com/7352884/147755424-5b4b7cc3-f356-4946-8d06-91c742271a90.png">

### 🤔 Expected Behavior

The ability to either target a class or have a `background` option for the `style` prop for `PayPalButtons`

### 🔬 Minimal Reproduction

```markdown
1. Copy the implementation example from storybook here: https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--default
2. View the background is white
3. Does not seem to work via the className prop

I have attempted to target multiple classes the component adds to the DOM, which have been unsuccessful.
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 7.5.0      |
| Browser          | All        |
| Operating System | All        |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by borodovisin** [comment]
Hi @alex-r89, can you share all the options you're using  on the `PayPalButtons` component. Or you're able to share a sandbox fork with this issue to take a look?

**Comment by alex-r89** [comment]
Hi,

The only style related options I am using are as follows:

`style={{ layout: 'vertical', label: 'paypal' }}`

The way I am using this is:

```js
import { PayPalScriptProvider, PayPalButtons } from '@paypal/react-paypal-js'


      <PayPalScriptProvider
        options={{
          'client-id': process.env.PAYPAL_CLIENT_ID
        }}>
        <PayPalButtons
          fundingSource={'paypal'}
          style={{ layout: 'vertical', label: 'paypal' }}
          createOrder={createOrder}
          onApprove={onApprove}
          onError={onError}
        />
      </PayPalScriptProvider>
```

I have since stopped using blue and I am instead using the gold button because the white edges are less visible, but they are still visible.

**Comment by borodovisin** [comment]
Hi @alex-r89, I don't see any issue with the behavior of the SDK library. Can you please check if you have some custom CSS class modifying for the example the iframe similar to this:

```
iframe {
  background-color: white;
}
```
Can you inspect the button iframe container and make sure the `background-color` is `transparent`.
<img width="305" alt="Screen Shot 2022-02-08 at 10 42 54 AM" src="https://user-images.githubusercontent.com/26287838/153022542-79e71990-5b6e-44bb-b1c7-f44bc2b22767.png">

Please can you make sure that value is not overridden from another CSS class or a custom style?

**Comment by alex-r89** [comment]
Hi,

No, I do not style iframes at all on my site: 

<img width="725" alt="Screenshot 2022-02-12 at 4 16 29 pm" src="https://user-images.githubusercontent.com/7352884/153719132-53400bf6-d927-4af4-a543-081b689fdbd2.png">


In fact, setting a background on this iframe doesnt do anything - it doesnt remove the white background around the button:

<img width="1187" alt="Screenshot 2022-02-12 at 4 18 33 pm" src="https://user-images.githubusercontent.com/7352884/153719188-62cb19c7-122c-4b30-b5ad-871f0a2deddc.png">

**Comment by ianstrong** [comment]
I'm also experiencing this issue. this needs to be fix i think.
![image](https://user-images.githubusercontent.com/34215734/186256222-b8039e62-6644-4cf3-badc-5cfaf5047281.png)

**Comment by ianstrong** [comment]
@alex-r89 did you get a fix for this?

**Comment by ianstrong** [comment]
@alex-r89 @borodovisin I got the cause of this one from one of my senior @ moment. it happens when color scheme is dark. so make sure to **""color-scheme: none""** the parent div of PaypalButtons. I'll create a pr for this.

**Comment by castrolem** [comment]
@ianstrong this comment saved the life of many of the designers at my company, thank you 🙌

**Comment by ianstrong** [comment]
> @ianstrong this comment saved the life of many of the designers at my company, thank you 🙌

happy to help <3

**Comment by imranbarbhuiya** [comment]
I'm also having the same issue. My code
```ts
				<MantineProvider
					theme={{
						colorScheme: 'dark',
					}}
					withGlobalStyles
					withNormalizeCSS
				>
							<PayPalScriptProvider options={options}> 
...
</PayPalScriptProvider>
</MantineProvider>
```

removing the theme fixes this issue but changes my website design, so I can't remove it. Are there any other ways to fix it?

**Comment by castrolem** [comment]
@imranbarbhuiya what I did was make `a <div style={{colorScheme: 'none'}}><JustMyPayPalComponent /></div>` to not affect anything outside of the codebase.
