### ISSUE TITLE
[BUG] : can not get dynamic client id

### ISSUE THREAD

**Issue by Jerald-tonmoy-dias** [paypal/react-paypal-js#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

  
  
  //paypal integration
  const initialOptions = {
    "client-id": { paypal_client_id },
    //"client-id": "AWOafqislzl8zx6-w5BwIOu9p-7DXKNt3Ly4hGzXYNRYBKJkY_yrUcAYSc5RP6YFz_ckikuYoDoBs9NK",
    currency: "USD",
    intent: "capture",
  };    

  {/* paypal modal */}
      <div className="modal fade" id="exampleModalCenter" tabIndex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div className="modal-dialog modal-dialog-centered" role="document">
          <div className="modal-content">
            <div className="modal-header">
              <h6 className="modal-title" id="exampleModalLongTitle">pay online</h6>
              <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div className="modal-body">
              <PayPalScriptProvider
                options={initialOptions}>
                <PayPalButtons
                  forceReRender={[orderDetails]}
                  createOrder={(data, actions) => {
                    return actions.order.create({
                      purchase_units: [{
                        amount: {
                          value: formatPrice(getTotal() + getVat())
                        }
                      }]
                    });
                  }}
                  onApprove={(data, actions) => {
                    return actions.order.capture().then(function (orderData) {

                      var transaction_id = orderData.purchase_units[0].payments.captures[0].id;
                      console.log(transaction_id);
                      // order 
                      setOrderDetails({
                        ...orderDetails,
                        uploading: true,
                      });

                      let url = BASE_URL + "/website/order";
                      let formData = orderDetails;
                      formData.subTotal = getTotal();
                      formData.vat = getVat();
                      formData.payment_type = 'PAYPAL';
                      formData.payment_id = transaction_id;
                      console.log(formData);
                      return axios
                        .post(url, orderDetails, {
                          headers: { Authorization: `Bearer ${getCookie()}` },
                        })
                        .then((res) => {
                          if (res.data !== "ended") {
                            setShowCheckout(false);
                            setFoodStockWeb(res.data);
                            setOrderDetails({
                              items: [],
                              branch: null,
                              workPeriod: null,
                              workPeriodStatus: false,
                              address: authUserInfo.details && authUserInfo.details.address,
                              name: authUserInfo.details && authUserInfo.details.name,
                              phn_no: authUserInfo.details && authUserInfo.details.phn_no,
                              note: null,
                              payment_type: "COD",
                              uploading: false,
                            });
                            toast.success(`${_t(t("Your order has been placed"))}`, {
                              position: "bottom-center",
                              autoClose: 10000,
                              hideProgressBar: false,
                              closeOnClick: true,
                              pauseOnHover: true,
                              className: "text-center toast-notification",
                            });
                            history.push('/');
                          } else {
                            toast.error(`${_t(t("Sorry, this branch is closed now"))}`, {
                              position: "bottom-center",
                              autoClose: 10000,
                              hideProgressBar: false,
                              closeOnClick: true,
                              pauseOnHover: true,
                              className: "text-center toast-notification",
                            });
                            setOrderDetails({
                              ...orderDetails,
                              uploading: false,
                            });
                          }
                        })
                        .catch((err) => {
                          setOrderDetails({
                            ...orderDetails,
                            uploading: false,
                          });
                          toast.error(`${_t(t("Please try again"))}`, {
                            position: "bottom-center",
                            autoClose: 10000,
                            hideProgressBar: false,
                            closeOnClick: true,
                            pauseOnHover: true,
                            className: "text-center toast-notification",
                          });
                        });
                      // end here

                    });
                  }}
                />
              </PayPalScriptProvider>
            </div>
          </div>
        </div>
      </div>
      {/* paypal modal */}

### 😕 Current Behavior

I am using react laravel project. Everything is going fine with static client id. But when I pass client id from database or laravel env file  through api  paypal buttons are not appearing. The main this is I can not add dyanmic value to client id. 

http://prntscr.com/26ejct8
http://prntscr.com/26ejbfi

### 🤔 Expected Behavior

When I add dynamic client id buttons should come up ex: http://prntscr.com/26ejax9

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | ^7.5.0     |
| Browser          | chrome     |
| Operating System |windows 10  |
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by borodovisin** [comment]
Hi @Jerald-tonmoy-dias. I saw in your code this: `{ paypal_client_id }` the `client-id` is a string value, not an object.
You should use something like this: `"client-id": `${paypal_client_id}`,` instead.

Please try it and feel free to let us know any feedback or if this doesn't fix your problem.

**Comment by Jerald-tonmoy-dias** [comment]
Hello brother @borodovisin thank you for  your reply. I have already tried a couple of times the same way you have shown. But still it is not working.

**Comment by mkirlin** [comment]
Hey @Jerald-tonmoy-dias! Haven't heard anything for a few weeks now, so I'm going to close this ticket for now. If you're still having this issue, please re-open it and post that sample env so Arturo can take a look at it. Thanks!
