### ISSUE TITLE
[FEATURE]: Cancel subscription functionality

### ISSUE THREAD

**Issue by ed-whittle** [paypal/react-paypal-js#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Firstly thanks for this library, it's made Paypal integration with my React website a lot easier. 

I am using a subscription model and the createSubscription function is working well, however I haven't been able to locate a function to cancel a subscription. Does this exist at the moment and if not is there any plans to implement this?

Implementation as per
https://developer.paypal.com/api/subscriptions/v1/#subscriptions_cancel

### Describe the solution you'd like

Wrapper to call the https://developer.paypal.com/api/subscriptions/v1/#subscriptions_cancel API, similar to the createSubscription functionality

### Describe alternatives you've considered

Making the API call myself

**Comment by gorootde** [comment]
+1 and bump

**Comment by robwheatley** [comment]
This would be great. Also a 'change plan' feature.
