### ISSUE TITLE
[FEATURE]: PayPalScriptProvider for multiparty payments

### ISSUE THREAD

**Issue by l30c0d35** [paypal/react-paypal-js#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When using the `PayPalScriptProvider` component the options prop does not seem to take a `merchant-id`. However, to perform a multiparty payment (where the web app is only the platform) script tag would require a merchant id identifying the payments receiver.

### Describe the solution you'd like

The `<PayPalScriptProvider/>`'s options prop should take a merchant id to allow for multiparty payments.

**Comment by gregjopa** [comment]
Hi @l30c0d35 can you try passing the `merchant-id` value as an array? The `PayPalScriptProvider` should support all the params that the paypal-js loader supports:
https://github.com/paypal/paypal-js#merchant-id-array
