### ISSUE TITLE
Question - how does security work with setting the amount in createOrder()

### ISSUE THREAD

**Issue by alex-r89** [paypal/react-paypal-js#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Apologies, this is not really a feature request, but I wonder; is it secure that this package is basically all run on the client?

For example, order details are created on the client side and passed into the `actions.order.create` function. Even if the order details were not created on the client, the function to generate the checkout would be run on the client side. For example:

```js
import { PayPalScriptProvider, PayPalButtons } from '@paypal/react-paypal-js'

const orderDetails = {
  purchase_units: [
    {
      description: 'A description',
      amount: {
        currency_code: 'USD',
        value: 5
      }
    }
  ],
  application_context: {
    shipping_preference: 'NO_SHIPPING'
  }
}

  const createOrder = (data, actions) => {
    return actions.order.create(orderDetails).then((orderID) => {
      return orderID
    })
  }

      <PayPalScriptProvider
        options={{
          'client-id': process.env.PAYPAL_CLIENT_ID
        }}>
        <PayPalButtons
          fundingSource={'paypal'}
          createOrder={createOrder}
        />
      </PayPalScriptProvider>
```

As this is all done on the client, I don't see what stops someone altering any of the potential values passed into `actions.order.create` - eg lower the value ? I have not done this because I don't actually know how, but this seems to go against everything I have learnt about generating these sorts of values and processing them on the client?

### Describe the solution you'd like

Either an update to the docs explaining why this is ok to be done on the client, or an update to the package if this is in fact insecure.

### Describe alternatives you've considered

N/A

**Comment by gregjopa** [comment]
Hi @alex-r89, PayPal recommend doing a server-side integration with the `createOrder()` and `onApprove()` callbacks. That way you can validate the final amount in the `onApprove()` callback before approving the payment. This question has come up before too. Here is my response in a similar issue: https://github.com/paypal/react-paypal-js/issues/197#issuecomment-945961288 

This seems like a great thing for the team to document in the react-paypal-js readme.

**Comment by alex-r89** [comment]
Thanks for the info. Yeah, the multiple official paypal docs for this all do everything on the client:

- https://www.npmjs.com/package/@paypal/react-paypal-js
- https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--default
- https://developer.paypal.com/sdk/js/reference/

There is also no real mention that this is insecure. Even on the server side docs (https://developer.paypal.com/demo/checkout/#/pattern/server) it doesn't mention that this method is secure and the others should be avoided.

I dont really understand how the server side integration of `createOrder()` and `onApprove()` in the above example actually works though. I see it makes a fetch to a server endpoint I assume, but what would we actually be validating here? What is it that we should be doing on the server - it doesnt seem like there is any paypal server side node package to run to generate or verify the request we would make? There doesnt seem to be a paypal server side node package which I can use to generate a valid `orderId` or confirm anything we post to our endpoint. I dont see what the request to something server side is doing. 


Is there anyway you can explain this at all?

Thanks

**Comment by xjamundx** [comment]
Here's the video series:
https://www.youtube.com/playlist?list=PLJa2J9JcsT9WRoNhETHRZkXZ-NrF0YBWU

There's a doc update coming in another week or two that will add these examples to the docs.

Currently, the video and accompanying examples only showcases the most basic server-side order creation/capture, but more advanced verification and fulfillment as well as a more thorough explanation of the tradeoffs between the approaches are something we hope to add in the future.

I don't know if that quite closes the issue, but hopefully gets us closer!
