### ISSUE TITLE
[BUG]: Credit card form magnifies and becomes unusable on Chrome 99.X on Android

### ISSUE THREAD

**Issue by saransh88** [paypal/react-paypal-js#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

  The Fields within the Debit or Credit Card form magnifies and becomes un-fillable

https://user-images.githubusercontent.com/99205307/159497211-f0ce7b50-0ac4-4482-8a20-0a7f532a3b80.mp4

### 😕 Current Behavior

The screen gets magnified and the form is not usable.

### 🤔 Expected Behavior

The screen stays in normal size for users to be able to fill in the information.

### 🔬 Minimal Reproduction

```markdown
1. Navigate to https://cnulkl.csb.app/ on Android with Chrome 99.X
2. Hit Debit & Credit card 
3. Start filling in the fields with the required information
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |   7.6.0    |
| Browser          | Chrome 99.0.4844.58|
| Operating System |  Android   |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

[Paypal-react-js-sandbox](https://codesandbox.io/s/withered-haze-cnulkl?file=/package.json) 
[PageLink](https://cnulkl.csb.app/)

**Comment by mpreddy928** [comment]
Hi @saransh88 i tested the issue on sandbox link provided so for the issue raised above can be fixable with user-scalable=no in the meta tag 
<meta
      name="viewport"
      content="width=device-width,initial-scale=1,user-scalable=no"
    />
    https://6r2w8n.csb.app/

**Comment by saransh88** [comment]
@mpreddy928 Thank you for getting back.
I tried using https://x4e05k.csb.app/ on my Device and this is what I see.
Device: Pixel 4a
Browser: Chrome-100.X
Android Version: 12.X

https://user-images.githubusercontent.com/99205307/161340964-d0d557a7-14a8-40f6-bfa7-5cfb2c329746.mp4

**Comment by mpreddy928** [comment]
@saransh88 i will check this and let you know asap. Thanks

**Comment by saransh88** [comment]
@mpreddy928 Most Android device with 
Android 10 +
Chrome on Mobile: 99.X+

Devices tried: 
Samsung Galaxy 9
Samsung S10+
Pixel 4a 5G

**Comment by saransh88** [comment]
Yes, It's fixed !
Thank you :-)
