### ISSUE TITLE
[BUG]: A cross-origin error was thrown. React doesn't have access to the actual error object in development. This error occurs when Paypal component re renders.

### ISSUE THREAD

**Issue by meghraj-bril** [paypal/react-paypal-js#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I am using Paypal react hosted fields to accept credit card payments so i created a common Paypal component to use wherever we need it for payment, this paypal component is inside other parent components so whenever a state changes in the parent the child components also re renders at this time this error is thrown
![Paypal error](https://user-images.githubusercontent.com/102206757/160056597-2b1ffbbd-835e-4fa5-873a-4345bf2879cc.png)
I have used same code for implementation as in this codesandbox https://codesandbox.io/s/paypal-custom-payment-integration-b9il3r?file=/pages/components/cardForm.js:1039-1123
Here is the code for paypal component
<PayPalScriptProvider
          options={{
            'client-id': client_id,
            components: 'hosted-fields',
            'data-client-token': clientToken,
          }}
        >
          <PayPalHostedFieldsProvider
            styles={{
              '.invalid': { color: '#dc3545' },
            }}
            createOrder={() =>
              props.createPaypalOrder().then((resp) => resp)
            }
          >
            <div className="row m-b-20">
              <div className="col-md-6">
                <PayPalHostedField
                  id="card-number"
                  style={CUSTOM_FIELD_STYLE}
                  className="input focused normal"
                  hostedFieldType="number"
                  options={{ selector: '#card-number' }}
                />
              </div>
              <div className="col-md-6">
                <input
                  type="text"
                  ref={cardHolderName}
                />
              </div>
            </div>
            <div className="row m-b-20">
              <div className="col-md-6">
                <AELabel variant="body2">
                  Expiry Date <span className="stripe-required">*</span>
                </AELabel>
                <PayPalHostedField
                  id="expiration-date"
                  style={CUSTOM_FIELD_STYLE}
                  hostedFieldType="expirationDate"
                  className="input focused normal"
                  options={{ selector: '#expiration-date', placeholder: 'MM/YY' }}
                />
              </div>
              <div className="col-md-6">
                <AELabel variant="body2">
                  CVV <span className="stripe-required">*</span>
                </AELabel>
                <PayPalHostedField
                  id="cvv"
                  style={CUSTOM_FIELD_STYLE}
                  className="input focused normal"
                  hostedFieldType="cvv"
                  options={{ selector: '#cvv', maskInput: true }}
                />
              </div>
            </div>
            <SubmitPayment submitHandler={submitHandler} />
          </PayPalHostedFieldsProvider>
        </PayPalScriptProvider>

Also the hosted fields gets cleared when any state in paypal component changes. That should not happen.

A quick response will be really helpful as i am stuck due to this issue, Thanks! 

### 😕 Current Behavior

Error is thrown when parent state changes and component re renders.

### 🤔 Expected Behavior

Error should not be thrown when parent state changes and component re renders also the fields should not be cleared.

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anuragsarma33** [comment]
Hey.
Is there any update regarding this issue?
I am also facing the same error

**Comment by borodovisin** [comment]
Hi @meghraj-bril and @anuragsarma33,  we are planning to start digging immediately this issue.
When we have some updates on what is going on here I'll post them and keep you updated.

**Comment by borodovisin** [comment]
Hi @meghraj-bril, I attached a simple test using the codesandbox you share:

🎥  https://www.loom.com/share/4c57d4c1e4f84575b92927a319a36f5f?sharedAppSource=personal_library

Can you please help me to replicate the issue 🆘 ? In the video above I make a complete transaction and I won't be able to see any issue with the state changes. I'll need your help to be able to easily replicate the issue.

**Comment by meghraj-bril** [comment]
Hi @borodovisin Thanks for checking, i already tried to replicate this issue on sandbox but it won't replicate there it only replicates in local environment.

**Comment by borodovisin** [comment]
Hi @meghraj-bril, can be something else in your env making the re-render process, I was thinking maybe the client-token change, or maybe another parent component is mounting/unmounting and that can be the reason the `PayPalScriptProvider ` is probably calling again the SDK library.

In that component, when React executes the state changes asynchronous after the comparison in the virtual DOM it shouldn't affect the `PayPalScriptProvider`, maybe I missing something else.
Don't hesitate to provide us feedback or an easy way to replicate this issue and we can take a closer look.

**Comment by diegoag64** [comment]
@meghraj-bril @borodovisin I can confirm that this is an issue. I am not able to replicate it on codesandbox but its really annoying working with the react-paypal-js hosted fields, any sort of state change or conditional rendering breaks the page.

I am constantly having issues where if I save any change on the PaymentForm.js (very similar to the one in the sandbox), the hotreload itself breaks the page and i need to hard refresh.

Here is the error I see:

_react-paypal-js.js:1250 Uncaught Error: Failed to render <PayPalHostedFieldsProvider /> component. BraintreeError: Element already contains a Braintree iframe._

So far I have found ways to work around it, but honestly getting a product to production with this library is really scary.
