### ISSUE TITLE
[BUG]: Text unreadable on dark background

### ISSUE THREAD

**Issue by squareborg** [paypal/react-paypal-js#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

When using the buttons on a page with a dark background some of the text is unreadable

<img width="498" alt="image" src="https://user-images.githubusercontent.com/8677881/164444220-ead99477-dafe-4ee8-a170-0bbbcee1014a.png">

Is there a way to support dark backgrounds?

Thannks

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YousifRagab** [comment]
I ran into the same issue as well, titles (i.e Billing Address) and the close button are very black, I can't figure out how to change their styles.
