### ISSUE TITLE
[BUG]: Unable to build

### ISSUE THREAD

**Issue by KoesterJannik** [paypal/react-paypal-js#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Unable to build this npm package

### 😕 Current Behavior

NPM run build give an type error:

### 🤔 Expected Behavior

npm build compiles fine.

### 🔬 Minimal Reproduction

```markdown
npm run build
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |  7.6.0          |
| Browser          |            |
| Operating System |            |
```

### Relevant log output

```shell
./node_modules/@paypal/react-paypal-js/dist/types/components/braintree/BraintreePayPalButtons.d.ts:1:15
Type error: ',' expected.

> 1 | import { type FC } from "react";
    |               ^
  2 | import { type BraintreePayPalButtonsComponentProps } from "../../types";
  3 | /**
  4 | This `<BraintreePayPalButtons />` component renders the [Braintree PayPal Buttons](https://developer.paypal.com/braintree/docs/guides/paypal/overview) for Braintree Merchants.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

I have never seen this before.

**Comment by krik-chry** [comment]
I am having exactly the same problem in version 7.7.0. Maybe a workaround to exclude these files from type checks?

**Comment by KoesterJannik** [comment]
@krik-chry 

Im using react-paypal-button-v2 now. This is working for me.

**Comment by krik-chry** [comment]
What is your typescript version? Updating from 4.3.2 to 4.5.5 fixed this issue for me

**Comment by KoesterJannik** [comment]
good to know! My version is 4.6.2

**Comment by gregjopa** [comment]
Thanks for reporting this issue. The PayPal team is investigating and testing with different versions of TS to see what's going on.

**Comment by gregjopa** [comment]
@KoesterJannik can you test out the latest release 7.8.1 and see if it fixes your issue? 

Here’s the related PR that should have fixed it
https://github.com/paypal/react-paypal-js/pull/277

**Comment by krik-chry** [comment]
@gregjopa Glad that you had a look. I'll have a look as soon as possible too, test it with the latest version

**Comment by KoesterJannik** [comment]
Thanks. For me it is working with the latest version.
