### ISSUE TITLE
[BUG]: onApprove not always firing

### ISSUE THREAD

**Issue by gghdev** [paypal/react-paypal-js#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I've already read through these:
https://github.com/paypal/paypal-checkout-components/issues/1813
https://github.com/krakenjs/post-robot/pull/96
https://caniuse.com/?search=noopener

I'm unable to reproduce this bug myself but we're still having a small but consistent trickle of users who complete their PayPal transactions and yet `onApprove` is never fired. The issue linked above seems like it would only still occur in a niche scenario -- a specific workflow in addition to an old browser?

Our client has a technologically unsophisticated user base and getting details is painful. It's possible that a higher percentage of their users are on old software, but still, we're seeing one or two of these a day.

Any ideas?

These Sentry errors are never captured, of course, because it's merely not running in the fault scenario:

```TS
  const onPaymentApprove: PayPalButtonsComponentProps["onApprove"] = async (data, actions) => {
    const capturePaymentResult = await actions.order?.capture();
    if (!capturePaymentResult) {
      sentryBrowserClient?.captureException(
        new Error(`Payment capture error (modal): undefined result`)
      );
    } else if (capturePaymentResult.status === "COMPLETED") {
      const productPurchaseResult = await purchaseProduct({
        variables: {
          productId,
          payPalPaymentDetails: [data.orderID, data.payerID || ""],
          couponCode: discountData.code,
          productVariationId: String(productVariationId),
        },
      });
      if (!productPurchaseResult.data?.purchaseProduct?.success) {
        sentryBrowserClient?.captureException(
          new Error(
            `Order creation error (modal): ${productPurchaseResult.data?.purchaseProduct?.errorCode}: ` +
              `${productPurchaseResult.data?.purchaseProduct?.message}`
          )
        );
      }
    } else {
      sentryBrowserClient?.captureException(
        new Error(`Payment capture error (modal): ${capturePaymentResult.status}`)
      );
    }
    postPurchaseActions();
  };
```

### 😕 Current Behavior

`onApprove` occasionally doesn't fire (under unknown conditions).

### 🤔 Expected Behavior

`onApprove` should always fire.

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 7.8.1      |
| Browser          | Multiple   |
| Operating System | Multiple   |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dayvyno2021** [comment]
onApprove doesn't fire because of a bug when dynamically entering the value(amount price). You can confirm that by hard coding the value, it fires. To solve this, use parseInt(#value). Price in the code below represents the dynamically imputed price

export default function App() {
    return (
        <PayPalScriptProvider options={{ "client-id": "test" }}>
            <PayPalButtons
                createOrder={(data, actions) => {
                    return actions.order.create({
                        purchase_units: [
                            {
                                amount: {
                                    value: parseInt(#price),
                                },
                            },
                        ],
                    });
                }}
                onApprove={(data, actions) => {
                    return actions.order.capture().then((details) => {
                        const name = details.payer.name.given_name;
                        alert(`Transaction completed by ${name}`);
                    });
                }}
            />
        </PayPalScriptProvider>
    );
}

**Comment by fvlasie** [comment]
This fix doesn't work for me unfortunately.
