### ISSUE TITLE
[FEATURE]: Add a button which lets user choose donation amount.

### ISSUE THREAD

**Issue by MafinBoy** [paypal/react-paypal-js#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Yes, I know this can be coded by the developer by letting user type in the amount in a textfield, but this is not a very elegant way to do it.
It would be better if this library had a pre-made button that did essentially the same thing as the button created on this site: https://www.paypal.com/donate/buttons/

### Describe the solution you'd like

Expected behaviour:
![paypaldonate2](https://user-images.githubusercontent.com/42269909/173657908-50b3960b-4895-4247-9f60-61ffe3203dcd.gif)

**Comment by xjamundx** [comment]
FWIW I love this

**Comment by Aldiyazov** [comment]
Need

**Comment by manziEric** [comment]
did someone manage to get this working im looking for this solution
