### ISSUE TITLE
[BUG]: Text is not visible on dark background

### ISSUE THREAD

**Issue by YousifRagab** [paypal/react-paypal-js#283]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### 🐞 Describe the Bug

All texts, titles, and the close button are designed for a light background, using a dark background results in these texts being barely visible.

Does the package support dark mode? Or is there any way to use white color for texts instead of black?

### 😕 Current Behavior

All texts, titles, and the close button are not visible like in the screenshot below
![PayPal_0](https://user-images.githubusercontent.com/43272557/174435294-f2a7a79f-521e-42ee-9100-16987333b2db.png)

Here's the highlighted texts as well
![PayPal_1](https://user-images.githubusercontent.com/43272557/174435296-adf7f3df-6ca7-47c4-9e1f-c50075757374.png)

### 🤔 Expected Behavior

These texts and close button should be white when using a dark background

### 🔬 Minimal Reproduction

```markdown
1- Create a new app
2- use a dark background
3- Integrate PayPal Buttons
```

### 🌍 Environment

```markdown
| Software         | Version(s)      |
| ---------------- | --------------- |
| react-paypal-js  | 7.8.1           |
| Browser          | FireFox 101.0.1 |
| Operating System | Windows 10      |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

I only found one issue about this and it was closed recently with no solution.

**Comment by YousifRagab** [comment]
For anyone wondering, I ended up creating a transparent background for the buttons, and when the purchase button is clicked, the background's color is set to white, and when the screen is closed the background will return to be transparent again.

Not the best solution, but it works.

**Comment by naingaungphyo** [comment]
Why this issue is closed? 
I have the similar problem with black background. Please give the option to change debit card label font color.
