### ISSUE TITLE
[BUG]: Error during built NextJS

### ISSUE THREAD

**Issue by Gechrist** [paypal/react-paypal-js#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I am using react paypal js for a sandbox eshop web app built with Next JS. When I try to built I get the following error:

info  - Checking validity of types...
Failed to compile.
./node_modules/@paypal/react-paypal-js/dist/types/components/PayPalButtons.d.ts:1:15
Type error: ',' expected.
> 1 | import { type FunctionComponent } from "react";
    |               ^
  2 | import type { PayPalButtonsComponentProps } from "../types";
  3 | /**
  4 | This `<PayPalButtons />` component supports rendering [buttons](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-reference/#buttons) for PayPal, Venmo, and alternative payment methods.
Error! Command "npm run build" exited with 1

### 😕 Current Behavior

Error when compiling

### 🤔 Expected Behavior

Finish compiling without error

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregjopa** [comment]
Hi @Gechrist, what version of react-paypal-js are you using? The latest release [7.8.1](https://github.com/paypal/react-paypal-js/commit/002426389663ab1a7add659e74881e6d90aa0b4a) should resolve this issue

**Comment by Gechrist** [comment]
Just updated to 7.8.1 and it works. Thank you.
