### ISSUE TITLE
[BUG]: actions.disable() in onInit doesn't disable the button

### ISSUE THREAD

**Issue by shinchannn** [paypal/react-paypal-js#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Hi, I'm trying to validate the my form before entering PayPal flow. As far as I know, there's no code example out there about how to implement this in `<PayPalButtons/>`, so I referred to the documentation in this [page](https://developer.paypal.com/sdk/js/reference/). I tried to attach the prop `onInit` to my `<PayPalButtons/>` component. The function runs, as I can tell from the content it prints. However, the window pops up upon click like nothing was changed. So even my first step in validation can't be finished.

### 😕 Current Behavior

The window pops up even if `actions.disable()` is written in `onInit`.

### 🤔 Expected Behavior

I tried to call the `actions.disable()` in the environment using `<script>`, it won't respond to clicking.

### 🔬 Minimal Reproduction

```markdown
Codesanbox here for reproduction. (https://codesandbox.io/s/oninit-issue-464e8b).
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AwaMelvine** [comment]
hi @shinchannn, I am facing the same issue as well. Did you manage to find a solution or workaround for this?

**Comment by gregjopa** [comment]
Hi @shinchannn and @AwaMelvine we provide a `disabled` prop for managing the disabled state in react-paypal-js. You should be able to use this instead of wiring up the behavior in `onInit()`. Ex:

<img width="1126" alt="Screen Shot 2022-08-02 at 10 09 58 AM" src="https://user-images.githubusercontent.com/534034/182409149-0d1257ac-84cc-432d-85a3-4caee3452d2b.png">

**Comment by MatthewTang** [comment]
bump

**Comment by MatthewTang** [comment]
> Hi @shinchannn and @AwaMelvine we provide a `disabled` prop for managing the disabled state in react-paypal-js. You should be able to use this instead of wiring up the behavior in `onInit()`. Ex:
> 
> <img alt="Screen Shot 2022-08-02 at 10 09 58 AM" width="1126" src="https://user-images.githubusercontent.com/534034/182409149-0d1257ac-84cc-432d-85a3-4caee3452d2b.png">

This solution doesn't quite fit my use case, since I need to post my server and ensure a successful response after they click the paypal button *but before* letting the payapl popup appear. 

Hope this make sense, Thanks!

**Comment by AndrewEastwood** [comment]
does this mean that this is no longer working with react?

```
onInit={async (data, actions) => {
  const ok = await canProceed();
  ok ? actions.enable() : actions.disable();
}}
```
