### ISSUE TITLE
[BUG]: Subscription revise types not provided

### ISSUE THREAD

**Issue by ArtemFokin** [paypal/react-paypal-js#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Hello
i'm trying to call subscription actions.revise action in createSubscription(data, actions) handler, but types for it not provided.  I've checked my logs and method exist. 

same method in sdk:
https://developer.paypal.com/sdk/js/reference/#link-createsubscription

### 🌍 Environment

```markdown
| Software         |   Version(s)  |
| ---------------- | ------------- |
| react-paypal-js  |    7.8.1      |
| Browser          |   Chrome 103  |
| Operating System | MacOS Monerey |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oscyp** [comment]
bump
