### ISSUE TITLE
[BUG]: The events of the PaypalButtons component don't catch the updated external variables

### ISSUE THREAD

**Issue by SalvadorJJ** [paypal/react-paypal-js#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

The events of the PaypalButtons component miss the changes of the variables outside of the event, for example in the `createOrder` event I'd like to use a state outside of the event, like a state value, when the state value change, inside the event has not detected this change and use the previous value of the state.

### 😕 Current Behavior

The external values of the variables, states, or props values  used  in the events like `createOrder` are kept

### 🤔 Expected Behavior

The external values of the variables, states, or props values  used  in the events like `createOrder` have  the updated value  

### 🔬 Minimal Reproduction

```markdown
I created a [codesandbox](https://codesandbox.io/s/paypal-bug-test-kdckvc?file=/src/App.js:726-909) with the example of the issue

In the example, we can find two buttons, a regular button, and the Paypal button, there is a state with a boolean value, it's named test.

The regular button changes the state and there is a useEffect that shows the test state value when its value changes. you can see it on the console

If we click on the Paypal button the test value is the previous one, inside the event the value never changed
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |     7.8.9  |
| Browser          |     any    |
| Operating System |     any    |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SalvadorJJ** [comment]
I found the solution. I figured out the prop `forceReRender`

**Comment by xjamundx** [comment]
For things like amount, you can `useRef` and reference `amountRef.current` in the `createOrder` function closure and it will stay up-to-date as well. Frankly, this needs a better callout in the docs!
