### ISSUE TITLE
[FEATURE]: Give donors the option to increase their donation amount to help offset the cost of fees?

### ISSUE THREAD

**Issue by jbyerline** [paypal/react-paypal-js#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

PayPal recently released support to round up your donation to cover processing fees. It would be extremely helpful if we had this option as well! Thanks

### Describe the solution you'd like

Simply adding a checkbox to the checkout modal prompting the user if they would like to round up.

**Comment by manziEric** [comment]
did you manage to make this work. im looking for code snippet for multiple choices for the donation button

**Comment by jbyerline** [comment]
Unfortunately no I did not
