### ISSUE TITLE
[BUG]: Smart Button first (fast) click not working and shows blue border

### ISSUE THREAD

**Issue by lennartlott** [paypal/react-paypal-js#300]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

The first click within 2 seconds after loading on the smart button shows a blue border and doesn't work.

![paypal button error](https://user-images.githubusercontent.com/6389443/187896262-9f3e2783-54b4-407e-8faf-c420903ffbab.png)

Failed to load resource: https://b.sbox.stats.paypal.com/v2/counter.cgi?p=uid_5f89bd1380_mta6mjm6mzc&s=SMART_PAYMENT_BUTTONS

**Comment by lennartlott** [comment]
This bug still exists. Also big sites like Disney Plus and Joyn are affected.

**Comment by wicka-aus** [comment]
We have this issue too. Button needs to be clicked twice to work.
