### ISSUE TITLE
[BUG]: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by mercpls** [paypal/react-paypal-js#303]
# Fix: Removing `data-client-token` fixes the issue. And buttons render properly.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### HTTP / HTTPS
Happens in both cases. Hosted / Local

## Description
When using `data-client-token` as given in the Example causes the an error to fire [here](https://github.com/paypal/react-paypal-js/blob/a0db96c5d3cd0e050ca7ba81a9d8fa6429b77c4d/src/components/PayPalButtons.tsx#L81-L92)

## Error Response
Failed to render <PayPalButtons /> component. Failed to initialize: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### 😕 Current Behavior

When I attempt to render the PayPalButtons, I get this error

```Failed to render <PayPalButtons /> component. Failed to initialize: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.```

### 🤔 Expected Behavior

Paypal buttons should render

### 🔬 Minimal Reproduction

```markdown
### Initialize a remix run project

### Create Example.tsx in `routes`
Supplied code for `Example.tsx`

import { Outlet } from "remix";
// Paypal provider
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

// Paypal initialization
const initialOptions = {
    "client-id": "test",
    currency: "USD",
    intent: "capture",
    "data-client-token": "abc123xyz==",
};

export default function Example() {
    return (
        <PayPalScriptProvider options={initialOptions}>
                <Outlet />
        </PayPalScriptProvider>
    );
}


### Create routes/example/index.tsx
(So all routes inside /example/xyz get the PayPalScriptProvider that we need for checking out a user, but routes that don't use paypal don't load the script)

Supplied code for `index.tsx` inside `routes/example`

```ts
// Paypal
import { PayPalButtons } from "@paypal/react-paypal-js";

const Index = () => {
    return (
        <div>
            <p>Checkout</p>
            <div id="paypal-container" className="border">
                <PayPalButtons />
            </div>
        </div>
    );
};

export default Index;
```
```


### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| remix-run        | 1.0.6      |
| react            | 17.0.2     |
| react-dom        | 17.0.2     |
| Browser          |            |
| Operating System | Mac Os 15.2.1|
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devpato** [comment]
Thanks for providing the solution to your problem! That fixed my error too :)

**Comment by WhooperDar** [comment]
> # Fix: Removing `data-client-token` fixes the issue. And buttons render properly.
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues.
> 
> ### 🐞 Describe the Bug
> ## Framework: Remix run
> ### HTTP / HTTPS
> Happens in both cases. Hosted / Local
> 
> ## Description
> When using `data-client-token` as given in the Example causes the an error to fire [here](https://github.com/paypal/react-paypal-js/blob/a0db96c5d3cd0e050ca7ba81a9d8fa6429b77c4d/src/components/PayPalButtons.tsx#L81-L92)
> 
> ## Error Response
> Failed to render component. Failed to initialize: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
> 
> ### 😕 Current Behavior
> When I attempt to render the PayPalButtons, I get this error
> 
> `Failed to render <PayPalButtons /> component. Failed to initialize: InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`
> 
> ### 🤔 Expected Behavior
> Paypal buttons should render
> 
> ### 🔬 Minimal Reproduction
> ```gfm
> ### Initialize a remix run project
> 
> ### Create Example.tsx in `routes`
> Supplied code for `Example.tsx`
> 
> import { Outlet } from "remix";
> // Paypal provider
> import { PayPalScriptProvider } from "@paypal/react-paypal-js";
> 
> // Paypal initialization
> const initialOptions = {
>     "client-id": "test",
>     currency: "USD",
>     intent: "capture",
>     "data-client-token": "abc123xyz==",
> };
> 
> export default function Example() {
>     return (
>         <PayPalScriptProvider options={initialOptions}>
>                 <Outlet />
>         </PayPalScriptProvider>
>     );
> }
> 
> 
> ### Create routes/example/index.tsx
> (So all routes inside /example/xyz get the PayPalScriptProvider that we need for checking out a user, but routes that don't use paypal don't load the script)
> 
> Supplied code for `index.tsx` inside `routes/example`
> 
> ```ts
> // Paypal
> import { PayPalButtons } from "@paypal/react-paypal-js";
> 
> const Index = () => {
>     return (
>         <div>
>             <p>Checkout</p>
>             <div id="paypal-container" className="border">
>                 <PayPalButtons />
>             </div>
>         </div>
>     );
> };
> 
> export default Index;
> ```
> 
> ```
> 
> 
> ### 🌍 Environment
> 
> ```markdown
> | Software         | Version(s) |
> | ---------------- | ---------- |
> | react-paypal-js  |            |
> | remix-run        | 1.0.6      |
> | react            | 17.0.2     |
> | react-dom        | 17.0.2     |
> | Browser          |            |
> | Operating System | Mac Os 15.2.1|
> ```
> 
> ### Relevant log output
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct
> 
> ### ➕ Anything else?

Thanks for the solution
