### ISSUE TITLE
[FEATURE]: Subscription revise method

### ISSUE THREAD

**Issue by oscyp** [paypal/react-paypal-js#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

PayPal allows invoking the `actions.subscription.revise` method from the client but this library doesn't support that. This topic was raised here https://github.com/paypal/react-paypal-js/issues/293 but without any response.

Documentation is under this section: https://developer.paypal.com/sdk/js/reference/#link-createsubscription

### Describe alternatives you've considered

The workaround for this is to call the backend for approval href which contains the token in it and later user has to confirm that.

**Comment by gregjopa** [comment]
Hi @oscyp, thanks for reporting this issue. I submitting a PR to add types for `revise()`. Please have a look here: https://github.com/paypal/paypal-js/pull/318
