### ISSUE TITLE
[BUG]: Using PayPalScriptProvider when react app has multiple entry points

### ISSUE THREAD

**Issue by TraGicCode** [paypal/react-paypal-js#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Our whole application does not consist of a single react app.  Instead, it's composed of multiple react apps.  In our case we have 2 seperate react apps/components.  One for Showing Credit Messaging and one for showing paypal billing buttons.  My Question is how can we "correctly" use the "PayPalScriptProvider" component in both of these React Apps/Components ( that do not share a common parent ) without having any issues or loading the script twice?

### 🤔 Expected Behavior

N/

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by gregjopa** [comment]
Hi @TraGicCode, thanks for explaining your use case. Here are a couple options to try with the current design:

## Option 1 - rely on the caching behavior in the paypal-js script loader

We do have some logic inside our script loader to try and prevent unneccessary reloads of the JS SDK script (https://github.com/paypal/paypal-js/blob/main/src/load-script.ts#L30-L31). Can you try wrapping each React app in a `<PayPalScriptProvider>` with the same params and then check the network tab in dev tools to see if the script loads twice from your merchant domain? One thing to mention is the PayPal JS SDK script is designed to load twice, once on the parent page (merchant domain), and once in the child frame (paypal.com domain) so please ensure you are checking the referrer to know if it's double loading or not on your domain. 

One tricky thing that comes to mind is there could be a race condition if both of your react apps are rendered on the same page at the same time. If that is the case, you could try using the `deferLoading` feature in one of the PayPalScriptProvider components to prevent the script from loading on render and configure some logic to load it after the first one finishes. It is extra logic to write but `deferLoading` should provide more granular control as to when the request is made to load the script. Ex: https://github.com/paypal/react-paypal-js#deferloading

## Option 2 - leverage the `data-namespace` data attribute to isolate the PayPal JS SDK behavior for each app

We do offer a `data-namespace` feature with the PayPal JS SDK script to isolate behavior with the global window namespace and post message communication. You can pass in the `data-namespace` value to the PayPalScriptProvider component and have it be unique for each react app. It will load the JS SDK script twice on your domain but should enable each component to continue functioning without an issue.

Please give these a try and let me know how it goes. If both options are problematic, we can explore other solutions. I'm also open to suggestions with how to better design this React library in our next major release.

**Comment by TraGicCode** [comment]
Hey @gregjopa ,

So for option 1, i actually discovered this when digging through your code and testing it locally.  This is a bit of a hack and I don't like it unfortunately ( in regards to the caching that is done for the options params ).  The Defer loading solution also doesn't seem appeasing.

For Option 2, this is what we currently have but having to load the js sdk 2 times ( or event more depending on if another react app/component needs  to use this library ) is also not ideal.

> I'm also open to suggestions with how to better design this React library in our next major release.

I don't there are that many "great solutions".  I am curious though, do these components work without the PaypalScriptProvider component wrapping them?  If we added as a script tag manually in the html will the components still work?  I didn't try this but maybe you know?  I assume if it did work the script tag would have to be synchronously downloaded.

**Comment by TraGicCode** [comment]
Hey @gregjopa ,

This makes the Public API for PayPalScriptProvider seem unsatisfactory and confusing.  If something is putting the script tag on the page it would also be responsible for setting values that would normally be passed into the "options" prop.  Therefore, the even though you have added a new prop "loadingStatus", the options prop is essentially not necessary.
