### ISSUE TITLE
[BUG]: Button max-width

### ISSUE THREAD

**Issue by UndercoverNL** [paypal/react-paypal-js#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

a max-width is being set twice once on the `zoid-paypal-buttons-uid_....` element and once within the iframe on the `paypal-button-container` element, the max width is 750px, even tho the buttons would be meant to be filled to its parent class size according to the docs. I can overwrite the max-width of the `zoid-paypal-buttons-uid_....` element, but I can't change anything within the iframe of course, so I can't change that max width.

Why are those max-widths set? The button itself should shrink to its parent class in general as width: 100% is used, shouldn't it?
Is there some setting I can do to remove this max width? 

### 😕 Current Behavior

`PayPalButtons` element won't be wider as 750px

### 🤔 Expected Behavior

`PayPalButtons` element having width 100% without a max width so that it can grow to its full parent's class width.

### 🔬 Minimal Reproduction

```markdown
Make use of the `PayPalButtons` element in a parent element with a width of > 750px
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |^7.8.2      |
| Browser          |Any         |
| Operating System |Any         |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UndercoverNL** [comment]
bump

**Comment by skateeveryday10** [comment]
bump

**Comment by Blkc** [comment]
bump

**Comment by alexle-dev** [comment]
bump

**Comment by Wyatt-SG** [comment]
This is still an issue- very disappointed to see this neglected.

**Comment by wsbrunson** [comment]
Hey all, this has actually been solved. Still waiting on the public developer docs to be updated.

You can pass 

```
 paypal.Buttons({
  style: {
    disableMaxWidth: true 
  },
}).render('#paypal-button-container');
```

To remove the hard-coded max-width. The buttons should then respect any max-width or width settings you have on your container
