### ISSUE TITLE
[BUG]: BraintreePayPalButtons in ShadowDOM - Failed to render <PayPalButtons /> component. Error: Component closed

### ISSUE THREAD

**Issue by nipuna777** [paypal/react-paypal-js#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

The BraintreePayPalButtons do not render when the app is rendered in a shadow DOM and strict mode is enforced.

### 😕 Current Behavior

When using the BraintreePayPalButtons with the following criteria: 
1. React 18
2. Strict mode
3. Rendering the app in a shadow dom

The buttons do not render as expected and we get the error:
`Failed to render <PayPalButtons /> component. Error: Component closed`

Removing strict mode or the shadow DOM fixes the issue.

### 🤔 Expected Behavior

Buttons should render correctly in strict mode inside shadow dom

### 🔬 Minimal Reproduction

```markdown
Please find the repro here: 
https://codesandbox.io/s/braintree-react-strict-shadow-issue-gzioso 

You will need to add a client ID as the [demo API](https://braintree-sdk-demo.herokuapp.com/api/braintree/auth) seems to be down.



//create shadow root to isolate our react app
const host = document.getElementById("root");
const shadow = host.attachShadow({ mode: 'open' });
const renderIn = document.createElement('div');
shadow.appendChild(renderIn);
const root = ReactDOM.createRoot(renderIn);

root.render(
  <StrictMode>
    <App /> <-- same content from the docs
  </StrictMode>
);
```
```


### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |      7.8.2 |
| Browser          | FF 107.0.1 |
| Operating System | macOS 12.6 |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dfcn84** [comment]
bump! this hasn't been looked at. can someone help?

i am noticing this is error source is from:
https://github.com/paypal/react-paypal-js/blob/a0346e34bb4f1443bc8311a02d7fc2d0321bf222/src/components/PayPalButtons.tsx#L114-L118

is something not allowing the the button to render (or re-render) correctly?

i am also getting component closed error when onApprove calls some function despite not in Strict Mode.

**Comment by xv-uladzislau-klachkou** [comment]
same here, facing the same issue. Could anyone help?

**Comment by xv-jim-c** [comment]
keeping this alive. this is not resolved.

**Comment by dfcn84** [comment]
bump. still not resolved
