### ISSUE TITLE
[BUG]: onClick is not working

### ISSUE THREAD

**Issue by AndrewEastwood** [paypal/react-paypal-js#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

For some reason the `createOrder` is being called even when `actions.reject` was made before. This makes no senes at all.

```
        createOrder={(data, actions) => {
          return createOrder(data, actions);
        }}
        onClick={(data, actions) => {
          actions.reject();
        }}
        onInit={(data, actions) => {
          canProceed()
              .then((s) => {
                enableButton(s);
              })
              .catch(() => {
                enableButton(false)
              });
        }}
```

### 😕 Current Behavior

actions.reject(); does not block further execution

### 🤔 Expected Behavior

actions.reject(); should prevent and discard current flow.

### 🔬 Minimal Reproduction

```markdown
Try this configuration:


        createOrder={(data, actions) => {
          return createOrder(data, actions);
        }}
        onClick={(data, actions) => {
          actions.reject();
        }}
```
```


### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregjopa** [comment]
Hey @AndrewEastwood, can you try using the `disabled` prop? We added this to make validation easier with the `<PayPalButtons />` component.  

Sorry for the confusion around validation. This [disabled prop](https://github.com/paypal/react-paypal-js/blob/main/src/components/PayPalButtons.tsx#L17) was originally documented in Storybook but it was removed.

**Comment by mnicpt** [comment]
@AndrewEastwood, also try returning actions.reject().Sent from my iPhone 12 Pro MaXOn Dec 26, 2022, at 3:23 PM, Greg Jopa ***@***.***> wrote:﻿
Hey @AndrewEastwood, can you try using the disabled prop? We added this to make validation easier with the <PayPalButtons /> component.
Sorry for the confusion around validation. This disabled prop was originally documented in Storybook but it was removed.

**Comment by AndrewEastwood** [comment]
@gregjopa @mnicpt could you explain how do I use `actions.reject();` from the `onClick` attribute? What exactly this rejection is suppose to do?

**Comment by mnicpt** [comment]
@AndyEastwood This is what reject does: https://github.com/paypal/paypal-smart-payment-buttons/blob/300798e412f1018192616b0bab4a23d99f7954de/src/props/onClick.js#L30 . That’s why I mentioned to return it. The onClick callback is used to allow client-side validation prior to rendering the checkout flow. You could also just return true or false and will work. Hope this helps.Sent from my iPhone 12 Pro MaXOn Dec 26, 2022, at 3:44 PM, Andy Eastwood ***@***.***> wrote:﻿
@gregjopa @mnicpt could you explain how do I use actions.reject(); from the onClick attribute? What exactly this rejection is suppose to do?

**Comment by AndrewEastwood** [comment]
Seems it does not allow to do that because of onClick expects nothing to be returned from it.
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/1483306/209676051-758b70d2-cde3-4356-84a6-80a456d832cd.png">

**Comment by AndrewEastwood** [comment]
...alright.. I think I get this suff working when I put `return` kwd there, like this:
```
onClick={(data, actions) => {
  return actions.reject();
}}
```
however, I'm seeing this side-effect:

https://user-images.githubusercontent.com/1483306/209677010-078c40b9-7455-47be-801a-4a317e857ffe.mov
