### ISSUE TITLE
[BUG]: Type '(data: OnApproveData, actions: OnApproveActions) => Promise<void> | undefined' is not assignable to type '(data: OnApproveData, actions: OnApproveActions) => Promise<void>'.   Type 'Promise<void> | undefined' is not assignable to type 'Promise<void>'.     Type 'undefined' is not assignable to type 'Promise<void>'.

### ISSUE THREAD

**Issue by hvlxh** [paypal/react-paypal-js#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Pasting the example of onApprove funcion doesn't work in typescript

### 😕 Current Behavior

Show this error:
[{
	"resource": "/e:/Codes/SEGA/web/pages/shop/1.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '(data: OnApproveData, actions: OnApproveActions) => Promise<void> | undefined' is not assignable to type '(data: OnApproveData, actions: OnApproveActions) => Promise<void>'.\n  Type 'Promise<void> | undefined' is not assignable to type 'Promise<void>'.\n    Type 'undefined' is not assignable to type 'Promise<void>'.",
	"source": "ts",
	"startLineNumber": 118,
	"startColumn": 15,
	"endLineNumber": 118,
	"endColumn": 24,
	"relatedInformation": [
		{
			"startLineNumber": 134,
			"startColumn": 5,
			"endLineNumber": 134,
			"endColumn": 14,
			"message": "The expected type comes from property 'onApprove' which is declared here on type 'IntrinsicAttributes & PayPalButtonsComponentProps'",
			"resource": "/e:/Codes/SEGA/web/node_modules/@paypal/paypal-js/types/components/buttons.d.ts"
		}
	]
}]

### 🤔 Expected Behavior

onApprove event work

### 🔬 Minimal Reproduction

```markdown
Just paste the example code of react paypal js in https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--default
```

### 🌍 Environment

```markdown
| Software         | Version(s)             |
| ---------------- | ---------------------- |
| react-paypal-js  | 7.8.2                  |
| Browser          | Chrome 108.0.5359.125  |
| Operating System | Windows 10 21H2        |
```

### Relevant log output

```shell
[{
	"resource": "/e:/Codes/SEGA/web/pages/shop/1.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '(data: OnApproveData, actions: OnApproveActions) => Promise<void> | undefined' is not assignable to type '(data: OnApproveData, actions: OnApproveActions) => Promise<void>'.\n  Type 'Promise<void> | undefined' is not assignable to type 'Promise<void>'.\n    Type 'undefined' is not assignable to type 'Promise<void>'.",
	"source": "ts",
	"startLineNumber": 118,
	"startColumn": 15,
	"endLineNumber": 118,
	"endColumn": 24,
	"relatedInformation": [
		{
			"startLineNumber": 134,
			"startColumn": 5,
			"endLineNumber": 134,
			"endColumn": 14,
			"message": "The expected type comes from property 'onApprove' which is declared here on type 'IntrinsicAttributes & PayPalButtonsComponentProps'",
			"resource": "/e:/Codes/SEGA/web/node_modules/@paypal/paypal-js/types/components/buttons.d.ts"
		}
	]
}]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by engdlee** [comment]
I am having the same issue, this is because `action.order` could be `undefined` so the return is of the type `Promise<void> | undefined` so is not like the expected type which is only `Promise<void>`

**Comment by BrandonArgel** [comment]
I also had problems trying to access the methods of `actions.order`, the way I fixed it was by using the [Non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#:~:text=Non%2Dnull%20assertion%20operator&text=produces%20a%20value%20of%20the,in%20the%20emitted%20JavaScript%20code.) `actions.order!`. It's not the best practice, but it was the unique way I found to continue. So this would be the final code:
```ts
onApprove={(data, actions) => {
                    return actions.order!.capture().then((details) => {
                        // Your code here after capture the order
                    });
                }}
```
