### ISSUE TITLE
[BUG]: PayPalScriptProvider options typescript type error

### ISSUE THREAD

**Issue by designed2use** [paypal/react-paypal-js#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

When putting messages on the same PayPalScriptProvider component it will only allow string as the type and fails to render if entering in a string with "buttons messages" or with an array.

### 😕 Current Behavior

When I use the following PayPalScriptProvider options:
{
        "client-id": PP_CLIENT_ID,
        currency: "GBP",
        intent: "capture",
        components: ["buttons", "messages"],
}

I get this typescript error:
Type '{ "client-id": string; currency: string; intent: string; components: string[]; }' is not assignable to type 'PayPalScriptOptions'.
  Types of property 'components' are incompatible.
    Type 'string[]' is not assignable to type 'string'.ts(2322)
scriptProviderTypes.d.ts(36, 5): The expected type comes from property 'options' which is declared here on type 'IntrinsicAttributes & ScriptProviderProps'

### 🤔 Expected Behavior

Should render without error.

### 🔬 Minimal Reproduction

```markdown
Use above options for PayPalScriptProvider component
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |  7.8.2     |
| Browser          |    chrome  |
| Operating System |     windows|
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

Changing the type components type on PayPalScriptQueryParameters in: 
@paypal\paypal-js\types\script-options.d.ts
to : string | string[];

Fixes the issue and enable the page to render ok.

**Comment by misraelson** [comment]
@designed2use  It's supposed to be a string we comma separated values:
`'buttons,funding-eligibility,hosted-fields'`

**Comment by bohorquez866** [comment]
if you are still having this issue, replace "client-id" with clientId property. 

EX:

```
import { loadScript } from "@paypal/paypal-js";

loadScript({clientId: 'MY_ID' }).then(  // code here )

```
