### ISSUE TITLE
[BUG]: Clicking pay by card creates an invalid order

### ISSUE THREAD

**Issue by jfilby** [paypal/react-paypal-js#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I click pay by credit/debit card. A PayPal dialog box shows a loading image and closes, and the created order Id is given.

When I go to Subscriptions in the dashboard, no orders/subscriptions are listed. When I search on the given order Id it finds it, but the order appears to be invalid. It has no status, and clicking on the order details displays an error page.

### 😕 Current Behavior

1. Not prompted for card details.
2. An invalid order is created with no error message.

### 🤔 Expected Behavior

1. I expect to be prompted for card details.
2. An error message should be displayed instead of creating an invalid order.

### 🔬 Minimal Reproduction

```markdown
1. Setup a page to create a subscription.
2. Click on pay be credit/debit card.
```

### 🌍 Environment

```markdown
| Software         | Version(s)  |
| ---------------- | ----------- |
| react-paypal-js  | 7.8.2       |
| Browser          | Firefox 109 |
| Operating System | Fedora 37   |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abdelmoulaBouc** [comment]
i faced the same issue , please if you have a solution share it with me.

**Comment by jfilby** [comment]
I gave up and went with Chargebee. They support PayPal as a payment processor.
