### ISSUE TITLE
[BUG]: Error in BraintreePayPalButtons StoryBook

### ISSUE THREAD

**Issue by erandagan1000** [paypal/react-paypal-js#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

In StoryBokk [HERE](https://paypal.github.io/react-paypal-js/?path=/docs/braintree-braintreepaypalbuttons--default)

The endpoint used to generate auth token is not working and generates an error

`/App.js: Failed to fetch (76:10)

  73 | 	useEffect(() => {
  74 | 		(async () => {
  75 | 			const response = await (
> 76 | 				await fetch(
                 ^
  77 | 					"https://braintree-sdk-demo.herokuapp.com/api/braintree/auth"
  78 | 				)
  79 | 			).json();

1`

### 😕 Current Behavior

When I opened this page -  https://paypal.github.io/react-paypal-js/?path=/docs/braintree-braintreepaypalbuttons--default

error is shown

### 🤔 Expected Behavior

Should see working live demo - smart button should be displayed

### 🔬 Minimal Reproduction

```markdown
Go To  [HERE](https://paypal.github.io/react-paypal-js/?path=/docs/braintree-braintreepaypalbuttons--default)

see the error
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregjopa** [comment]
Hi @erandagan1000, the storybook demos should be working again. Going to close this out. Let me know if you still have any issues.

**Comment by erandagan1000** [comment]
Hi,
Thanks for picking up.
still broken.
[image: image.png]
