### ISSUE TITLE
[BUG]: Method onCancel called when pay with MyBank

### ISSUE THREAD

**Issue by sherkot** [paypal/react-paypal-js#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

When I have to make a payment with MyBank, as soon as the redirect to the bank site is made, the "onCancel" callback is called, the popup remains displayed but the checkout page loses the reference to the payment flow

### 😕 Current Behavior

I render these buttons

![image](https://user-images.githubusercontent.com/16966007/230006119-57c2f046-d56e-4886-8817-8e70876ee9ff.png)

When I click on MyBank, the popup is correctly opened. I fill in all the data as required until I get to the bank selection

![image](https://user-images.githubusercontent.com/16966007/230006523-fb931cd9-bebc-46bd-979d-4da35884bf22.png)

As soon as I land on the bank selection page, the following is written in console (debug)

![image](https://user-images.githubusercontent.com/16966007/230006695-d29c043d-acc2-4980-aa49-08198ca2c425.png)

Finally, by clicking "Continue," the "onCancel" callback is called. Below is what has been tracked in the network

![image](https://user-images.githubusercontent.com/16966007/230006853-1974bc01-9ad7-4a07-a14a-9d5d71c61023.png)

### 🤔 Expected Behavior

When I log into my bank account and pay the related amount, the MyBank popuo will close and the checkout page captures onApprove callback

### 🔬 Minimal Reproduction

```markdown
1. Click on MyBank button
2. Compile data
3. Select bank account
4. Click on continue
```

### 🌍 Environment

```markdown
| Software         | Version(s)                            |
| ---------------- | ----------                            |
| react-paypal-js  | 7.8.2                                 |
| Browser          | Chrome Versione 111.0.5563.147        |
| Operating System | Windows 10 21H2 (build OS 19044.2728) |
```

### Relevant log output

```shell
{
  "events": [
    {
      "level": "info",
      "event": "button_cancel",
      "payload": {
        "timestamp": "1680678544302",
        "referer": "www.paypal.com",
        "sdkCorrelationID": "f7521323fcft415f",
        "sessionID": "uid_2csdsad226bc129_masdasdmde",
        "clientID": "XXXXXXX",
        "env": "production",
        "buttonSessionID": "uid_378905e355_xxxxxxxx",
        "buttonCorrelationID": "f96912312XXX7645b",
        "time": "1680678544302",
        "user_id": "uid_378905e355_xxxxxxxx",
        "token": "CCCXXX123123213"
      }
    }
  ],
  "meta": {},
  "tracking": [
    {
      "transition_name": "process_checkout_cancel",
      "event_name": "process_checkout_cancel",
      "context_type": "EC-Token",
      "token": "CCCXXX123123213",
      "context_id": "9DL6CCCCC9952J",
      "feed_name": "payments_sdk",
      "serverside_data_source": "checkout",
      "client_id": "XXXXXXX",
      "page_session_id": "uid_378905e355_xxxxxxxx",
      "referer_url": "www.paypal.com",
      "buyer_cntry": "IT",
      "locale": "it_IT",
      "integration_identifier": "XXXXXXX",
      "sdk_environment": null,
      "sdk_name": "payments_sdk",
      "sdk_version": "5.0.361",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.147 Safari/537.36",
      "context_correlation_id": "f119776v7225b",
      "t": "1680678544303",
      "button_session_id": "uid_378905e355_xxxxxxxx",
      "button_version": "5.0.135",
      "button_correlation_id": "f119776v7225b",
      "stickiness_id": null,
      "user_action": "commit",
      "seller_id": "NVXXXX4R22T3Z4",
      "merchant_domain": "http://localhost:3000",
      "selected_payment_method": "mybank",
      "experience": "default",
      "user_id": "uid_378905e355_xxxxxxxx",
      "time": "1680678544303",
      "fields_component_session_id": ""
    }
  ],
  "metrics": []
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OPNG23** [comment]
Hi @sherkot, have you seen this [article](https://mybank.eu/en/inanutshell-how-to-integrate-mybank-with-paypal/)? Could probably related to your issue.

**Comment by znaghash** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues.
> 
> ### 🐞 Describe the Bug
> When I have to make a payment with MyBank, as soon as the redirect to the bank site is made, the "onCancel" callback is called, the popup remains displayed but the checkout page loses the reference to the payment flow
> 
> ### 😕 Current Behavior
> I render these buttons
> 
> ![image](https://user-images.githubusercontent.com/16966007/230006119-57c2f046-d56e-4886-8817-8e70876ee9ff.png)
> 
> When I click on MyBank, the popup is correctly opened. I fill in all the data as required until I get to the bank selection
> 
> ![image](https://user-images.githubusercontent.com/16966007/230006523-fb931cd9-bebc-46bd-979d-4da35884bf22.png)
> 
> As soon as I land on the bank selection page, the following is written in console (debug)
> 
> ![image](https://user-images.githubusercontent.com/16966007/230006695-d29c043d-acc2-4980-aa49-08198ca2c425.png)
> 
> Finally, by clicking "Continue," the "onCancel" callback is called. Below is what has been tracked in the network
> 
> ![image](https://user-images.githubusercontent.com/16966007/230006853-1974bc01-9ad7-4a07-a14a-9d5d71c61023.png)
> 
> ### 🤔 Expected Behavior
> When I log into my bank account and pay the related amount, the MyBank popuo will close and the checkout page captures onApprove callback
> 
> ### 🔬 Minimal Reproduction
> ```
> 1. Click on MyBank button
> 2. Compile data
> 3. Select bank account
> 4. Click on continue
> ```
> 
> ### 🌍 Environment
> ```
> | Software         | Version(s)                            |
> | ---------------- | ----------                            |
> | react-paypal-js  | 7.8.2                                 |
> | Browser          | Chrome Versione 111.0.5563.147        |
> | Operating System | Windows 10 21H2 (build OS 19044.2728) |
> ```
> 
> ### Relevant log output
> ```shell
> {
>   "events": [
>     {
>       "level": "info",
>       "event": "button_cancel",
>       "payload": {
>         "timestamp": "1680678544302",
>         "referer": "www.paypal.com",
>         "sdkCorrelationID": "f7521323fcft415f",
>         "sessionID": "uid_2csdsad226bc129_masdasdmde",
>         "clientID": "XXXXXXX",
>         "env": "production",
>         "buttonSessionID": "uid_378905e355_xxxxxxxx",
>         "buttonCorrelationID": "f96912312XXX7645b",
>         "time": "1680678544302",
>         "user_id": "uid_378905e355_xxxxxxxx",
>         "token": "CCCXXX123123213"
>       }
>     }
>   ],
>   "meta": {},
>   "tracking": [
>     {
>       "transition_name": "process_checkout_cancel",
>       "event_name": "process_checkout_cancel",
>       "context_type": "EC-Token",
>       "token": "CCCXXX123123213",
>       "context_id": "9DL6CCCCC9952J",
>       "feed_name": "payments_sdk",
>       "serverside_data_source": "checkout",
>       "client_id": "XXXXXXX",
>       "page_session_id": "uid_378905e355_xxxxxxxx",
>       "referer_url": "www.paypal.com",
>       "buyer_cntry": "IT",
>       "locale": "it_IT",
>       "integration_identifier": "XXXXXXX",
>       "sdk_environment": null,
>       "sdk_name": "payments_sdk",
>       "sdk_version": "5.0.361",
>       "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.147 Safari/537.36",
>       "context_correlation_id": "f119776v7225b",
>       "t": "1680678544303",
>       "button_session_id": "uid_378905e355_xxxxxxxx",
>       "button_version": "5.0.135",
>       "button_correlation_id": "f119776v7225b",
>       "stickiness_id": null,
>       "user_action": "commit",
>       "seller_id": "NVXXXX4R22T3Z4",
>       "merchant_domain": "http://localhost:3000",
>       "selected_payment_method": "mybank",
>       "experience": "default",
>       "user_id": "uid_378905e355_xxxxxxxx",
>       "time": "1680678544303",
>       "fields_component_session_id": ""
>     }
>   ],
>   "metrics": []
> }
> ```
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct
> 
> ### ➕ Anything else?
> _No response_

Hello,

Were you able to solve this issue?
The same issue we get now.
