### ISSUE TITLE
[TOC] Adding TableOfContents in readme.md

### ISSUE THREAD

**Issue by ng29** [paypal/react-paypal-js#35]
### 🚀 Feature Proposal

Adding table of contents in readme.md.

### Motivation

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

### Example

Down the line, if readme content increases it will be easy to hop between the docs too.

**Comment by gregjopa** [comment]
Hi @ng29, thanks for the feature request. The readme.md file isn't very long. I don't think we need a Table of Contents section just yet. 

We will keep this in mind as we continue to evolve the docs.
