### ISSUE TITLE
[BUG]: Closes immediately on mobile

### ISSUE THREAD

**Issue by KthProg** [paypal/react-paypal-js#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

When a user clicks the PayPal button on a mobile device, the popup opens, and then immediately closes.

On mobile we show two buttons at the same time on different parts of the page, which could be related, but this works fine on desktop anyways. This occurs on iOS and Android.

We are also showing a paypal message next to each button, both are wrapped in a script provider. We also update the button and re-render it frequently as the page loads using forceReRender.

### 😕 Current Behavior

When a user on a mobile device clicks the PayPal Button, the popup opens and then immediately closes.

### 🤔 Expected Behavior

When a user on a mobile device clicks the PayPal Button, the popup opens and remains open until they complete their purchase.

### 🔬 Minimal Reproduction

```markdown
1. Add a paypal button on a mobile device
2. Click it
3. Observe the popup immediately closes
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |   7.8.3            |
| Browser          |   Safari/Chrome    |
| Operating System |  iOS/Android       |
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by barshag** [comment]
ALSO HERE  ON WEBSITE....:(

**Comment by gregjopa** [comment]
Could you please provide a link to a reproduction? I just tested the [sandbox demos on storybook](https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--default) and they work fine on my iphone. 

The expected behavior is that the popup will open in a new tab on mobile (thats how window.open() functions on mobile browsers). And will redirect back after competing the purchase.

**Comment by KthProg** [comment]
Hello, I figured out how this occurs. If there is a change to the parameters of `forceReRender` on mobile while the PayPal window is open(ing), it will immediately close the window. I solved this by using a ref that will not change while the window is open:

```
  const [isPayPalWindowOpen, setIsPayPalWindowOpen] = useState(false)
  const payPalTriggerRenderCount = useRef(0)

  const reRenderPayPalTrigger = useMemo(() => {
    if (!isPayPalWindowOpen) {
      payPalTriggerRenderCount.current += 1
    }
    // stop incrementing render count, and therefore stop
    // triggering re-render, if paypal window is open
    return payPalTriggerRenderCount.current
  }, [
    ...otherRefs,
    isPayPalWindowOpen,
  ])
```

then `forceReRender={[reRenderPayPalTrigger]}`

and the onClick handler for PayPalButtons calls `setIsPayPalWindowOpen(true)`
