### ISSUE TITLE
[BUG]:  How can I only show one paypal button not other payment solutions ?

### ISSUE THREAD

**Issue by pullmann4rent** [paypal/react-paypal-js#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

How can I only show one paypal button not other payment solutions ?

### 😕 Current Behavior

I only want to show the Paypal button yellow not more

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |  7.8.3          |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by aheidelberg** [comment]
```tsx
<PayPalButtons fundingSource="paypal" />
```
