### ISSUE TITLE
[BUG]: Dynamic amount value glitch

### ISSUE THREAD

**Issue by mashwishi** [paypal/react-paypal-js#355]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### 🐞 Describe the Bug

When the amount value change sometimes when you click pay button it doesn't change the amount from the invoice, Let's say a user order a 25$ but the customer want to buy 2 so price changes on useState then when they click pay sometime the output is correct which is $50 but sometime still at $25 

```tsx
<PayPalScriptProvider options={{ "client-id": process.env.PAYPAL_CLIENTID }}>
<PayPalButtons
    style={{ layout: "horizontal", color: "silver", tagline: false, height: 32, shape: "rect"}}
    createOrder={(data, actions) => {
        return actions.order.create({
            purchase_units: [
                {
                    amount: {
                        value: `${orderTotalAmount}`,
                    },
                },
            ],
        });
    }}
    onApprove={async (data, actions) => {
        handlePurchase()
    }}
/>
</PayPalScriptProvider>
```

### 🌍 Environment

```markdown
| Software         | Version(s) 
| ---------------- | ---------- 
| react-paypal-js  | ^7.8.3     
| Browser          | Microsoft Edge Version 112.0.1722.68 (Official build) (64-bit) 
| Operating System | Windows 11
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gregjopa** [comment]
You should be able to leverage the `forceReRender` buttons prop to have your function recalculate when the amount changes.

For the next major release of react-paypal-js, we may want to update this library to leverage the [useCallback hook](https://react.dev/reference/react/useCallback) for function props and require the user to wrap every function prop in useCallback. That seems to be the correct way to detect when function props change.
