### ISSUE TITLE
[BUG]: Error: Unable to render <PayPalButtons /> because window.paypal.Buttons is undefined.

### ISSUE THREAD

**Issue by sonipranjal** [paypal/react-paypal-js#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Getting this error "Error: Unable to render <PayPalButtons /> because window.paypal.Buttons is undefined." while using the package with Next.js

I have used the script tag for a workaround with the before interactivity strategy, then it's not throwing the error, but the buttons are still not appearing.

### 😕 Current Behavior

<img width="1109" alt="Screenshot 2023-05-14 at 3 32 47 AM" src="https://github.com/paypal/react-paypal-js/assets/43893639/b3275bad-a918-4385-a9bc-35dd12e212ea">

### 🤔 Expected Behavior

No error

### 🔬 Minimal Reproduction

```markdown
Just use it with Next.js app
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |     7.8.3       |
| Browser          | 113.0.5672.92   
| Operating System |     macos
```

### Relevant log output

```shell
Unhandled Runtime Error
Error: Unable to render <PayPalButtons /> because window.paypal.Buttons is undefined.

Call Stack
eval
node_modules/.pnpm/@paypal+react-paypal-js@7.8.3_biqbaboplfbrettd7655fr4n2y/node_modules/@paypal/react-paypal-js/dist/esm/react-paypal-js.js (417:0)
basicStateReducer
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (16540:0)
updateReducer
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (16664:0)
updateState
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (17004:0)
Object.useState
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (17915:0)
useState
node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.development.js (1622:0)
PayPalButtons
node_modules/.pnpm/@paypal+react-paypal-js@7.8.3_biqbaboplfbrettd7655fr4n2y/node_modules/@paypal/react-paypal-js/dist/esm/react-paypal-js.js (396:19)
renderWithHooks
node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js (16305:0)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sonipranjal** [comment]
I made it work somehow!

**Comment by Flaxxas** [comment]
For anyone coming here: had the same issue and fixed it by changing the id `paypal` of another element on the page. In my case I had a radio button with that id and renamed it to `paypal-radio`. 🙃
