### ISSUE TITLE
[BUG]: Method Called After Teardown

### ISSUE THREAD

**Issue by lucaleoni73** [paypal/react-paypal-js#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I'm using the PayPalHostedFieldsProvider to integrate the Advanced PayPal Checkout. But, when the interface showing the hosted fields loses focus and then re-gets focus, I receive this error:
Uncaught {name: 'BraintreeError', code: 'METHOD_CALLED_AFTER_TEARDOWN', message: 'teardown cannot be called after teardown.', type: 'MERCHANT', details: undefined}

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by kirkh34** [comment]
I am having the same issue, any luck?

**Comment by pfftdammitchris** [comment]
Make sure that your `<PaypalPayPalHostedFieldsProvider />` does not render multiple times. It should only render after `clientToken` is available but not re-render. The hosted fields should be rendered in a separate component where it can be be re-rendered for state updates, and should be placed as children of `<PaypalPayPalHostedFieldsProvider />
