### ISSUE TITLE
[FEATURE]: PayPal-Mock-Response

### ISSUE THREAD

**Issue by minorsetback** [paypal/react-paypal-js#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Good afternoon, I'm a react js developer and would like to suggest that you add the ability for users to add the "PayPal-Mock-Response" header, it is designed to test various errors, from the official documentation (https://developer.paypal.com/tools/sandbox/negative-testing/request-headers/) to create an order, you can use this feature, but since there is no possibility to change the headers.

### Describe the solution you'd like

I would like to suggest adding a new field in the options, "dataMockResponse" which users will use to generate artificial errors, this will allow users to better test their products.

### Describe alternatives you've considered

unfortunately I could not find any alternatives, only in php there are libraries that allow you to change headers

**Comment by aishize** [comment]
any updates?
