### ISSUE TITLE
[BUG]:  Warnings related to intent=tokenize on createSubscription

### ISSUE THREAD

**Issue by kimfucious** [paypal/react-paypal-js#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I'm switching over an app to use this library, and it's quite nice and well-documented.  Thanks for making this!

I've setup my code pretty much identical to what found in the Storybook [here](https://paypal.github.io/react-paypal-js/?path=/docs/example-subscriptions--default).

When I click the subscribe button, the popup window opens; however, there are two warnings in the console (see below).

The subscriptions are working in the sandbox.

I realize these are warnings; however, I'd like to know if I can safely ignore them, or make some changes to the implementation to address them.

### 😕 Current Behavior

When I click the subscribe button there are warnings in the browser console.

### 🤔 Expected Behavior

There should be no warnings.

### 🔬 Minimal Reproduction

```markdown
1. Implement buttons as shown in the Storybook mentioned above.
2. Click subscribe button.
3. View warnings in console.
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 8.1.0      |
| Browser          | Chrome 114.0.5735.198 |
| Operating System | macOS Ventura |
```

### Relevant log output

```console
smart_button_validation_error_billing_without_purchase_intent_tokenize_not_passed
{
    "vault": true,
    "cartBillingType": "SUBSCRIPTIONS_V1",
    "timestamp": "1690454123853",
    "referer": "www.sandbox.paypal.com",
    "sdkCorrelationID": "xxx",
    "sessionID": "xxx",
    "clientID": "xxx,
    "env": "sandbox",
    "buttonSessionID": "xxx",
    "buttonCorrelationID": "xxx",
    "time": "1690454123853",
    "user_id": "xxx",
    "token": "xxx"
}
Expected intent=tokenize for a billing-without-purchase transaction
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RodolfoDiazDev** [comment]
any solution?

**Comment by gregjopa** [comment]
>smart_button_validation_error_billing_without_purchase_intent_tokenize_not_passed

Hi @RodolfoDiazDev and @kimfucious, I learned today that there is a bug in the PayPal JS SDK Buttons component causing this warning with the Subscriptions button. They are working on a fix. For now, please ignore this warning. 

As long as you pass in `vault=true` and `intent=subscription` as mentioned in this [Subscriptions Doc](https://developer.paypal.com/docs/subscriptions/integrate/#link-createpaymentbutton), you are integrating correctly.

**Comment by GatoVuelta** [comment]
I'm getting this as well even, I'm not new but then this started to pop out, also seems to be the direct cause for the following errors that break my app completely:

```
smart_api_billagmt_subscriptions_get_contingency_error 
Object { timestamp: "1692414277583", referer: "www.sandbox.paypal.com", sdkCorrelationID: "f29334927a890", sessionID: "uid_b6e3970e67_mdm6mdm6ntg", clientID: "AT_JzFs8g...", env: "sandbox", buttonSessionID: "uid_f07437e2c9_mdm6mdm6ntg", buttonCorrelationID: "f368299bd965a", token: "0BL308..." }

```

Then

```
Uncaught Error: RESOURCE_NOT_FOUND
js:3:71880

at error https://www.paypal.com/sdk/js?client-id=AT_JzFs8gVW...&intent=subscription&vault=true:3
at  Wr https://www.paypal.com/sdk/js?client-id=AT_JzFs8gVW...&intent=subscription&vault=true:3
at [...]
```

**Comment by rafaelcardoso** [comment]
I'm also having the same problem, my front-end integration breaks the same way @GatoVuelta described, but the webhook arrives correctly after a few seconds on my back-end.

**Comment by rafaelcardoso** [comment]
> I'm also having the same problem, my front-end integration breaks the same way @GatoVuelta described, but the webhook arrives correctly after a few seconds on my back-end.

I've made a temporary workaround to avoid this problem, if I catch the error `RESOURCE_NOT_FOUND` I just show a loading state while I poll my backend waiting for the payment confirmation ¯\_(ツ)_/¯

**Comment by wyokyla23** [comment]
Is this something that will be fixed soon? I'd love to be able to use this but am on a bit of a time crunch.

**Comment by 8ctopus** [comment]
Same issue here. Crazy that they handle such bugs so slowly...

**Comment by fabeluna** [comment]
Same issue here, as @GatoVuelta described..  a few weeks ago it works, but now it breaks the payment process of my plugin..

**Comment by monti-star** [comment]
It appears as though we've merged a fix for this issue, can anyone confirm if this problem still exists? If not, we will close this issue as completed.

**Comment by GatoVuelta** [comment]
> It appears as though we've merged a fix for this issue, can anyone confirm if this problem still exists? If not, we will close this issue as completed.

Do we need to update anything? Because in my end it's still the same error. Nothing has changed.

**Comment by fabeluna** [comment]
Still also the same error

**Comment by aPortejoie** [comment]
> It appears as though we've merged a fix for this issue, can anyone confirm if this problem still exists? If not, we will close this issue as completed.

Hi, on my side this issue doesn't seems to appear again. But I don't see an update to the package (8.1.3 was published mid-august) so I'm wondering where the change happened.

**Comment by dundja** [comment]
@aPortejoie  I am on latest version `8.1.3` and I am having same issue. 
`https://www.sandbox.paypal.com/smart/api/billagmt/subscriptions/{ID}` is returning `RESOURCE_NOT_FOUND` without any other indication what is going on. I also think this is something on their side because it seams like subscription is successfully created every time.

**Comment by devchristina** [comment]
@all I've created a new ticket specifically for the second issue identified within this issue. I will be closing this ticket as completed, please follow the above new issue for status updates on the fix.
