### ISSUE TITLE
[FEATURE]:  Add a control for overlay

### ISSUE THREAD

**Issue by gersanco** [paypal/react-paypal-js#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

After completing the `onApprove` function, I would like to be able to manage the overlay. It would make more sense for it to remain visible while the backend is processing. Rather than creating a new overlay.

<img width="400" alt="overlay page" src="https://github.com/paypal/react-paypal-js/assets/12337026/a9e2e995-8ff3-45b4-bcc5-17d5ed185030">

### Describe the solution you'd like

Maybe a possible solution will be having a `dispatch` to show and hide the overlay. 

### Describe alternatives you've considered

The alternative that I have is to create my own overlay.

**Comment by devchristina** [comment]
Hi @gersanco, apologies for the delay in an acknowledgement / response for this issue. I'll take this request to the product team and see if this is something that is either 1. Achievable (and how) or 2. an enhancement we can add to the backlog.

**Comment by gersanco** [comment]
@devchristina Thanks so much 😄
