### ISSUE TITLE
[Feature] Add GitHub Action badge to README

### ISSUE THREAD

**Issue by gregjopa** [paypal/react-paypal-js#38]
Add a new badge to the README for GitHub Actions. Ex: https://github.com/paypal/react-paypal-js/workflows/CI/badge.svg

In terms of badge order, please make this the second badge after the npm badge.

**Comment by hndoss** [comment]
Hi! I already sent a PR.

**Comment by yash2189** [comment]
Hi can I work on this?

**Comment by gregjopa** [comment]
Sorry @yash2189 but @hndoss beat you to it and already has a PR w/ the fix. I assigned this issue to @hndoss
