### ISSUE TITLE
Apple Pay Button Not Available[BUG]: 

### ISSUE THREAD

**Issue by wyokyla23** [paypal/react-paypal-js#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Trying to view the apple pay button when it should be visible and it always shows 'The Component Is Ineligile To Render' instead.

### 😕 Current Behavior

When I open up the 'react-paypal-js' Storybook from my iphone 14 plus, select the default PayPalButtons, select Docs and then scroll down to fundingSource and select 'apple', 'The Component is ineligible to render' is displayed. 

### 🤔 Expected Behavior

I understand the Apple Pay button should only appear in certain scenarios like Iphone or Ipad and in Safari, so when I test to confirm the button renders under those circumstances, I expect to see the button.

### 🔬 Minimal Reproduction

```markdown
1.) Go to 'https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--default&args=fundingSource:applepay' on Iphone 

2.) Select PayPalButtons default

3.) Select Docs and scroll down to fundingSource dropdown

4.) Select 'applepay'

5.) Scroll back up and see 'The Component Is Ineligible To Render' showing instead of button
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |  ^8.1.3    |
| Browser          |  Safari    |
| Operating System |  Iphone 14 Plus|
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by monti-star** [comment]
Hi @wyokyla23, are you still facing this issue? Happy to work with engineering to find you an answer.

**Comment by wyokyla23** [comment]
> Hi @wyokyla23, are you still facing this issue? Happy to work with engineering to find you an answer.

I am still able to reproduce it, yes.

**Comment by devchristina** [comment]
Hi @wyokyla23. Got an answer for you! Apologize for the delay. 

Unfortunately the react-paypal-js library has not been updated to support the new ApplePay standalone component. 

PayPal no longer supports ApplePay as part of the smart buttons stack. It should be removed as an option from the funding sources dropdown in the storybook example and we will take that as an action item.

To use ApplePay with PayPal, please follow these steps documented [here](https://developer.paypal.com/docs/checkout/apm/apple-pay/). 

ApplePay is used as a standalone button integration using `window.paypal.Applepay`

**Comment by wyokyla23** [comment]
Ok. Thank you for the update!

**Comment by bradoyler** [comment]
Are there any examples of using a standalone Applepay button with `<PaypalScriptProvider />`?

**Comment by DSKonstantin** [comment]
Hi there. Any updates here?
