### ISSUE TITLE
[BUG]: Invalid selector error when PayPalButtons is rendered

### ISSUE THREAD

**Issue by theabdulmateen** [paypal/react-paypal-js#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Hey I get an unhandled JavaScript error when I try to render the `PayPalButtons` component

### 😕 Current Behavior

When I try to render the `PayPalButtons` component I get the following JS error:

`DOMException: Failed to execute 'querySelector' on 'Document': 'script[src="https://www.paypal.com/sdk/js?client-id="<KEY>"BUILD_NUMBER=15&currency=USD&components=buttons&intent=authorize"]' is not a valid selector`

### 🤔 Expected Behavior

It should not throw the error

### 🔬 Minimal Reproduction

```markdown
1. Render `PayPalButtons` component

<PayPalButtons
  style={{ layout: 'vertical', shape: 'pill' }}
   fundingSource={undefined}
   createOrder={createOrder}
   onApprove={onApprove}
/>

2. The invalid selector error mentioned above is thrown
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |   ^8.1.3   |
| Browser          |   Chrome   |
| Operating System | Arch Linux |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

Note: The above error is not thrown when I use a sandbox key, this error is only thrown in production with a live key

**Comment by monti-star** [comment]
Hi @theabdulmateen, 

I'll check with the engineering team and get you an answer regarding this issue.

**Comment by devchristina** [comment]
Hi @theabdulmateen. Due to lack of response, I'll close this issue. Please re-open if this is still an issue.

**Comment by princefishthrower** [comment]
@theabdulmateen - I'm working on this, my guess is that it has something to do with the library not being compatible with SSR frameworks (I'm using Gatsby right now and getting this)
