### ISSUE TITLE
[BUG]: Failed to render <PayPalHostedFieldsProvider /> component. BraintreeError: Element already contains a Braintree iframe.

### ISSUE THREAD

**Issue by Grumpier** [paypal/react-paypal-js#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I get this error when conditionally rendering hosted fields based on state. I want to display the hosted fields only if the user presses a credit card button.  Before press...
![image](https://github.com/paypal/react-paypal-js/assets/12978695/a0f1ebf5-9d6b-47a4-9319-53c7f962d8b3)
After press..
![image](https://github.com/paypal/react-paypal-js/assets/12978695/77c08fb4-7a12-47d5-954d-7432c2863bb9)

My code to do this is...
```
return (
    <>
      <Button 
        disabled={!canCharge}
        variant="contained" 
        sx={{width: "100%", height: 45, color: "white", backgroundColor: "grey.700"}} 
        type="submit" 
        onClick={handleCard}
        endIcon={
          [<img 
            key={1}
            style={{
              marginTop: 2
            }}
            width={90}
            height={45}
            src="/images/creditcards/1.png"
            alt="visa"
          />,
          <img 
            key={2}
            style={{
              marginTop: 2
            }}
            width={90}
            height={45}
            src="/images/creditcards/2.png"
            alt="mastercard"
          />,
          <img 
            key={3}
            style={{
              marginTop: 2
            }}
            width={90}
            height={45}
            src="/images/creditcards/22.png"
            alt="mastercard"
          />]
        }
      >
      </Button>
      { card ?
      <PayPalHostedFieldsProvider createOrder={createOrder} notEligibleError={<NotEligible />} >
        <CreditCardForm billingAddress={billingValues} createOrder={createOrder}/>
        <HandleSubmit billingAddress={billingValues} openCard={openCard} alertContext={alertContext} handlePayment={handlePayment} />
      </PayPalHostedFieldsProvider>
      : 
      null }
    </>
  )

```
The onClick event handleCard changes the state of card from false to true.

### 😕 Current Behavior

Here's the error generated:

hooks.tsx:608 React Router caught the following error during render Error: Failed to render <PayPalHostedFieldsProvider /> component. BraintreeError: Element already contains a Braintree iframe.
    at react-paypal-js.js:1237:1
    at basicStateReducer (react-dom.development.js:16540:1)
    at updateReducer (react-dom.development.js:16664:1)
    at updateState (react-dom.development.js:17004:1)
    at Object.useState (react-dom.development.js:17915:1)
    at useState (react.development.js:1622:1)
    at PayPalHostedFieldsProvider (react-paypal-js.js:1188:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1) Object

If I remove the conditional rendering, then the component works as expected.

### 🤔 Expected Behavior

Expect no error and component to render when state is changed.

### 🔬 Minimal Reproduction

```markdown
Should be simple to reproduce.
```

### 🌍 Environment

```markdown
| Software         | Version(s)  |
| ---------------- | ----------  |
| react-paypal-js  |  8.1.3      |
| Browser          |  Chrome     |
| Operating System |  macOS 13.5 |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pokrovskyy** [comment]
I stumbled upon a similar issue. One thing I noticed that enables the error in my case is passing `styles` prop to `PayPalHostedFieldsProvider` (even an empty object `styles={{}}` will suffice to trigger). Then on any field blur I get all sorts of errors, including mentioned by OP. I suppose something triggers re-render of the whole component which does not go well 🤔

**Comment by PrestonPHX** [comment]
Render fields inside an additional parent container (div) that you then hide/show as needed, with display:none or similar

**Comment by AndrewEastwood** [comment]
> I stumbled upon a similar issue. One thing I noticed that enables the error in my case is passing `styles` prop to `PayPalHostedFieldsProvider` (even an empty object `styles={{}}` will suffice to trigger). Then on any field blur I get all sorts of errors, including mentioned by OP. I suppose something triggers re-render of the whole component which does not go well 🤔

Awesome! That saved lot of time! Thanks
