### ISSUE TITLE
[BUG]: PayPal buttons not getting rendered on Safari browsers of some iPhone users

### ISSUE THREAD

**Issue by vorasudh** [paypal/react-paypal-js#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I am using PayPal buttons to display available options for users to pay. In general, the buttons get rendered correctly and users can use it just fine. But some of our users have complained that on Safari they just do not see the buttons. Some are using the latest version of iOS and Safari and some are using older versions. I have personally tested on a couple of different iPhone devices, but buttons appear for me.

### 😕 Current Behavior

In the root of the project, I have added the Paypal Providers - `<PayPalScriptProvider>` along with options. On one of the pages, I am using `<PayPalButtons>`.  The buttons appear on all browsers on phones and desktops except for Safari browser. On Safari, they are often not rendered at all.

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |  8.1.3     |
| Browser          |  Safari    |
| Operating System |  iOS       |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devchristina** [comment]
Hi @vorasudh, we're unable to research your issue as you haven't provided any details around how to reproduce. In order for us to efficiently provide support, we'll need something like your website or code.

**Comment by vorasudh** [comment]
Hi @devchristina my apologies. Here is the ticket booking platform where the issue happens.
https://booking.redlotusevents.com/tickets

You will have to create an account in order to add tickets to the cart.

I have to say that I have been able to reproduce it on my iPhone. But a lot of customers have complained that on Mobile Safari they just do not see PayPal buttons.

**Comment by devchristina** [comment]
@vorasudh Are you currently rendering the PayPal SDK inside of an iframe?

**Comment by vorasudh** [comment]
@devchristina No. It is rendered directly in the component. The Provider is at the very top and the PayPal Button component is inside a page.

**Comment by vorasudh** [comment]
@devchristina Any updates?

**Comment by KthProg** [comment]
We're seeing this same issue in production. One thing to note is that our button is re-rendered many times because of various changes to the cart, I wonder if many fast reloads of the same URL are causing issues in Safari?

**Comment by KthProg** [comment]
This is definitely related to the script not loading by the way. The script attempts to load for over a minute in some cases, and then it errors out with no error message and nothing logged to the console (that I can see).

**Comment by vorasudh** [comment]
@KthProg, true with re-rendering. I created an extra overview page just to show PayPal buttons and no "editing" of the cart is allowed. Still the same issue.

Regarding the script not loading, I moved the provider to the very top level so that the script is loaded at first page load. Or atleast this is my assumption. Still the same error.

**Comment by KthProg** [comment]
@vorasudh I would place a PayPal payments message somewhere on the page to verify it is actually loading, or show a loading indicator based on the isPending, isRejected, isResolved params from the PayPal script reducer. I have rarely been able to reproduce this myself, but when other users do, the PayPal messages have also not loaded, e.g. the script must not have loaded at all. Also when I reproduce it, i can see that the network request to get the PayPal script is stuck for over a minute.

**Comment by timfuhrmann** [comment]
We have experienced the same problem in the past, also around that time. Back then I was able to reproduce and found that it failed to load the PayPal SDK, hence no state changes in the script reducer. 

After of what it seems a fix on PayPal's side - no complaints for while. But in the last few days some customers have been messaging us again. Back then I can remember it happening after a Safari update, I'm not certain there was one in the past few days though.

**Comment by KthProg** [comment]
> We have experienced the same problem in the past, also around that time. Back then I was able to reproduce and found that it failed to load the PayPal SDK, hence no state changes in the script reducer.
> 
> After of what it seems a fix on PayPal's side - no complaints for while. But in the last few days some customers have been messaging us again. Back then I can remember it happening after a Safari update, I'm not certain there was one in the past few days though.

It being related to Safari security seems to be the leading theory, as this has apparently happened before several times over the last decade. I'm not sure if we've stopped seeing the issue or not since we were never able to track it down, but it would make sense to me that either a PayPal or a Safari update may have fixed the issue. My guess is that the browser trying to load the same script (and cancel and load again) over and over is triggering some kind of security feature in Safari to halt loading the script. If PayPal could debounce the script loading (e.g. wait for the previous script to load to try loading the new one), and not trigger loading the exact same script multiple times it would probably reduce instances of this issue. That's just an educated guess though.

**Comment by KthProg** [comment]
I don't see any recent releases for Safari. Makes me wonder if PayPal's server that serve the script are actually the ones having issues. It probably does serve a slightly different script for Safari no? Since the feature set is slightly different? Maybe something in that process is broken, otherwise maybe it's an iOS version thing. That may explain why I stopped seeing it on my own devices about a month ago.

https://developer.apple.com/documentation/safari-release-notes/

**Comment by KthProg** [comment]
The iOS releases line up better with the dates, as there was a release Dec 19th:
https://en.wikipedia.org/wiki/IOS_version_history

**Comment by paarthmanhastr** [comment]
Facing similar issue on Safari. The PayPal button doesn't render sometimes. One of our users complained about this few days ago. But I'm unable to reproduce the issue.
If anyone has any idea, that'd be helpful.

**Comment by ds41000** [comment]
bump
