### ISSUE TITLE
[BUG]: Broken link to dynamic currency example

### ISSUE THREAD

**Issue by FredericLatour** [paypal/react-paypal-js#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Can you please address this matter?

There were already 2 issues created and no answers were provided:
-  #324 
- #327 

Thanks in advance

### 😕 Current Behavior

If you click on the link https://paypal.github.io/react-paypal-js/?path=/story/example-usepaypalscriptreducer--currency it shows a broken link of a non-existent story.

### 🤔 Expected Behavior

When I visit the link https://paypal.github.io/react-paypal-js/?path=/story/example-usepaypalscriptreducer--currency a component example should be shown.

### 🔬 Minimal Reproduction

```markdown
1. Go to the read me https://www.npmjs.com/package/@paypal/react-paypal-js?activeTab=readme
2. Got to the dynamic currency example in storybook [link](https://paypal.github.io/react-paypal-js/?path=/story/example-usepaypalscriptreducer--currency) and click on it.
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devchristina** [comment]
@FredericLatour -- Researching this issue. Apologies for the delay in my response.

**Comment by devchristina** [comment]
@FredericLatour This issue was corrected in a commit back in January. This issue appears to affect anyone using version ≤7.8.2. The solution we'd suggest is to upgrade versions, or refer to a newer release’s docs. 

Let me know if this helps. I will close this issues as not planned. If this is not sufficient, please re-open the issue.

**Comment by FredericLatour** [comment]
If you look at the current documentation, it is clearly written:

>To learn more, check out the [dynamic currency example in storybook](https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--default).

![image](https://github.com/paypal/react-paypal-js/assets/1407847/7a4e111f-618a-45ca-8233-1a72ffa81bb5)

I you click on the link you can see by yourself that you are not pointing to a dynamic currency example.

Linking to some random page just to prevent an error from being displayed is not really providing a solution. 

The ability to change currency dynamically is a feature that certainly deserves a real example (even more so if we consider that previous versions of checkout buttons did not have this specific limitation). 

Does it clarify ?

**Comment by devchristina** [comment]
I get it now! Thank you for clarifying, you're not wrong. I'll ask the right people.

**Comment by devchristina** [comment]
@FredericLatour Got more details...

This dynamic currency example is technically in git history here: https://github.com/paypal/react-paypal-js/blob/v7.1.1/src/stories/usePayPalScriptReducer.stories.tsx

The most important part of the example show how to reload the JS SDK script using the dispatcher when the currency query param value changes: 

        const [{ options }, dispatch] = usePayPalScriptReducer();

        function onCurrencyChange(event: ChangeEvent<HTMLSelectElement>) {
            setCurrency(event.target.value);
            dispatch({
                type: "resetOptions",
                value: {
                    ...options,
                    currency: event.target.value,
                },
            });
        }

        return (
            <select
                value={currency}
                onChange={onCurrencyChange}
                name="currency"
                id="currency"
                style={{ marginBottom: "20px" }}
            >
                <option value="USD">United States dollar</option>
                <option value="EUR">Euro</option>
                <option value="CAD">Canadian dollar</option>
            </select>
        );
    }

**Comment by FredericLatour** [comment]
@devchristina Thanks for digging into this.
It is always helpful to see a complete example.
In my case, the amount (price & currency) comes from a `store`. Therefore, I came up with the following approach that seems to be working properly.

```jsx
  ...
  const [options, dispatch] = usePayPalScriptReducer()
  const amount = useStore($amount)

  useEffect(() => {
    dispatch({
      type: "resetOptions",
      value: {
        ...options.options,
        currency: amount.currency,
      },
    })
  }, [amount])
  ...
```

----
>PS: are you also supporting paypal-js ? I posted an issue there (not even sure this is the right place) and haven't any feedback yet. I'm moving to Javasript/typescript an old PHP app that was using an old paypal SDK and which allowed me to know the payment method that was used (paypal or credit card). I can't seem to get the information with the new apis. I can't say if the client paid with a CC or through Paypal. Do you have any pointer to get me into the right direction ? Anybody that can help ? Sorry for this aparte.

**Comment by devchristina** [comment]
Glad to see that you were able to create a working approach. I replied on your other issue, hoping to have an answer for you. I'll also see how I can get that example back into the Git repo. I'll close this issue as completed.
