### ISSUE TITLE
[BUG]: Paypal subscription button - Popup not closing and onApprove not triggered

### ISSUE THREAD

**Issue by zcmqc** [paypal/react-paypal-js#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I have implemented Paypal subscriptions using this approach and the buttons from this example  https://paypal.github.io/react-paypal-js/?path=/docs/example-subscriptions--default.

Everything was working fine until today, as we noticed following bug. 

`onApprove` never gets triggered and also popup window never gets closed, even though the payment is successful.

This happens in both the sandbox and production environments I have and also in your storybook example. 

![image](https://github.com/paypal/react-paypal-js/assets/17600873/cc513037-19ba-4c53-8967-f5b863d47ac5)

### 😕 Current Behavior

Paypal popup stays opened and it needs to be closed manually, after the payment is completed. 
OnApprove is not triggered. 

### 🤔 Expected Behavior

The Paypal popup closes after the payment is completed
OnApprove is triggered. 

### 🔬 Minimal Reproduction

```markdown
1. Go to https://paypal.github.io/react-paypal-js/?path=/story/example-subscriptions--default
2. Try to pay
3. Popup is not closing after the successful payment
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ------------------ |
| react-paypal-js  | 8.1.3      |
| Browser          | Brave v1.58.131       |
| Operating System | MacOS 13.5.1    |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dundja** [comment]
I have same issue as well

**Comment by F-Moody** [comment]
Same issue here, please DO NOT close this

**Comment by seedj** [comment]
I have the same problem, following this post.

**Comment by devchristina** [comment]
If you're not following the other issue. This has been fixed, please confirm that this is working as expected.

**Comment by dundja** [comment]
@devchristina I can confirm that issue is fixed. Thanks so much for support!

**Comment by zcmqc** [comment]
@devchristina I can confirm this is now resolved. Thank you for the quick response and resolution! 🥇

**Comment by seedj** [comment]
@devchristina we are facing randomly this issue again. Please can you check the status? Otherwise we'll be forced to change gateway early next week.
