### ISSUE TITLE
[BUG]: Sometimes can't get subscription details after successful approve

### ISSUE THREAD

**Issue by salievos** [paypal/react-paypal-js#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Sometimes we can't get subscription details after creating it, and we see that paypal is creating subscription and charge. Event if we try request data with some sleep function after 3 seconds. We can't catch this issue, and wrote some logging code inside try catch block with logging `JSON.stringify(e)` and it's just empty `{}`

### 😕 Current Behavior

When our client is trying to subscribe on some plan and approves payment on checkout page, we trying to get subscription details:
```
const onApprove = (data: OnApproveData, actions: OnApproveActions) => {
  try {
    const details = await actions?.subscription?.get();
  } catch (e) {
    console.log(JSON.stringify(e));
  }
};

<PayPalScriptProvider
  options={{
    'client-id': 'CLIENT-ID',
    'disable-funding': 'credit,card',
    vault: true,
    currency: 'USD',
  }}
>
  <PayPalButton
    onError={() => { /* handle error code */  }}
    onApprove={onApprove}
    createSubscription={() => { /* handle creating subscription code*/  }}
  />
</PayPalScriptProvider>
```

### 🤔 Expected Behavior

When the client approves the payment, we should be able to get the subscription details

### 🔬 Minimal Reproduction

```markdown
Somehow we can't reproduce it, usually it happens randomly
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |   7.3.3    |
| Browser          |    any     |
| Operating System |    any     |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by salievos** [comment]
@devchristina please, take a look to this issue

**Comment by devchristina** [comment]
Sent this to the product team to research.

**Comment by salievos** [comment]
@devchristina thanks, will be waiting update

**Comment by seedj** [comment]
Hi, we are all in the same situation @devchristina. 

I need to take a decision on it at the end of the day (if change PayPal to another payment gateway or not). 

Please, we are all waiting for an update.

**Comment by salievos** [comment]
@devchristina Hi, are there any updates?

**Comment by salievos** [comment]
still affecting

**Comment by seedj** [comment]
We had to change to Stripe the whole checkout process to avoid this issue.

PayPal 👎

**Comment by salievos** [comment]
@devchristina hi, any updates?

**Comment by salievos** [comment]
still affecting
