### ISSUE TITLE
[BUG]: URGENT // After payment we don't get Subscription details

### ISSUE THREAD

**Issue by seedj** [paypal/react-paypal-js#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

#393 #394  I'm referring to this issue.

We'll be forced to change the payment gateway if it will not be fixed within the next 24 hours.

### 😕 Current Behavior

#393 #394 It's the same behavior of these referenced issues.

### 🤔 Expected Behavior

Get the Subscription details for the user after payment.

### 🔬 Minimal Reproduction

```markdown
Hard to reproduce, it happens randomly.
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |     all    |
| Operating System |     all    |
```

### Relevant log output

```shell
2023-10-04 02:22:49,976 - ServicesBackend.Payment.views - PayPalSubscriptionPaymentSucceed Exception:‘NoneType’ object has no attribute ’IsPaypalUser’with params: I-TKW0RHTAKXK5 89.00 - views.py : 602
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

@devchristina please check it out.

**Comment by devchristina** [comment]
@seedj Apologies for the delay. Couple of questions: 

1. Are you able to get any correlation IDs? _It's extremely difficult to troubleshoot an issue when we cannot reproduce and/or know where to start?_ 
2. Have you submitted a merchant technical support ticket? If yes, what is that ticket number? 
3. If you cannot do number 1, can you provide us with an example of the code you're using?
