### ISSUE TITLE
[BUG]: Paypal subscription button - shows error but still charges the user

### ISSUE THREAD

**Issue by zcmqc** [paypal/react-paypal-js#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

We are using `react-paypal-js` for integration with Paypal. 

We found out weird issue. 
Paypal popup shows error message and `onApprove` is not triggered, however the user is charged the amount. 

We are not able to verify if the user payed since `onApprove` is not triggered. 

<img width="360" alt="image" src="https://github.com/paypal/react-paypal-js/assets/146339676/a82664ac-1e82-4acb-8d06-72cac87c56fb">
<img width="495" alt="image" src="https://github.com/paypal/react-paypal-js/assets/146339676/6d3fe1a1-be61-4370-8089-6e80732016e3">

### 😕 Current Behavior

When the user completes the checkout the error message is shown, `onApprove` is not triggered and window is not closing. 
However user is charged. 

### 🤔 Expected Behavior

If error pops up it should not charge the user. 

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ------------------ |
| react-paypal-js  | 8.1.3      |
| Browser          | Brave v1.58.131       |
| Operating System | MacOS 13.5.1    |
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by devchristina** [comment]
Hi @zcmqc -- Apologies for the delay in our acknowledgement, I'm currently working with the team to get answers. If you can please post a copy of your source code so we can troubleshoot this issue further.

**Comment by devchristina** [comment]
@zcmqc Can you provide specific example IDs -- at least completed sandbox transactions, but preferably the full address bar and anything relevant from the browser console (or code/site with steps to reproduce).

**Comment by zcmqc** [comment]
@devchristina Hello Christina. 

I am using subscription button https://paypal.github.io/react-paypal-js/?path=/docs/example-subscriptions--default

So after the user clicks this button, adds its data and goes through all the steps in the Paypal popup window, at the end of the process he gets the error I screenshot so the `onApprove` function is not triggered. But the user is charged. 
At least that is what I see in the transactions.
