### ISSUE TITLE
[BUG]: HOW TO SET LANGUAJE FOR PayPalMessages

### ISSUE THREAD

**Issue by DanielGBullido** [paypal/react-paypal-js#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Even if you set the language in the locale property, the text shown by the PayPalMessages component is still in English even if you send another language in locale.

I have tried to change the language of my browser but it keeps the language. There is no documentation or way to change it.

### 😕 Current Behavior

```
          <PayPalScriptProvider
            options={{
              clientId: clientId('en_US'),
              currency: currency,
              components: 'messages',
              intent: 'authorize',
              locale: 'en_US',
            }}
          >
            <PayPalMessages
              currency={currency as PayPalMessagesComponentOptions['currency']}
              style={style}
              placement="product"
              amount={amount}
              onClick={() => Satellite.moreInfoPaypalPayLater()}
              forceReRender={[style]}
            />
          </PayPalScriptProvider>
```

### 🤔 Expected Behavior

Show texte in language seted on locale property

### 🔬 Minimal Reproduction

```markdown
use documentation code
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |   8.1.3    |
| Browser          |   chrome   |
| Operating System |   mac      |
```

### Relevant log output

```shell
nothing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devchristina** [comment]
Hi @DanielGBullido -- I'm checking in with team members on this one. Apologies for the delay in our response.

**Comment by devchristina** [comment]
Hi @DanielGBullido -- For the PayLater messaging component you cannot override the default language, you can only render in the default language for that region. Please let me know if this helps, otherwise I will close this issue as working as expected.
