### ISSUE TITLE
[BUG]: Unexpected redirect after card from autocomplete

### ISSUE THREAD

**Issue by maksimchowis** [paypal/react-paypal-js#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Hello. After choosing "Debit or Credit Card" payment option and using autocomplete from browser suggestions, there is an unexpected redirect. I can only guess about two scenarios:

1. Autocomplete triggers form submit, that causes redirect
2. Some internal conflict, that causes redirect in Next.js (but I don't see any navigation requests made)

Interesting thing is that it only happens with address-related fields. Fields like "Name" and "Mobile" shows normal behavior on autocomplete.

[autocomplete-redicrect.webm](https://github.com/paypal/react-paypal-js/assets/118781348/1cc0a5cc-5af0-47e3-99d1-0be529dca5b4)

### 😕 Current Behavior

When I use autocomplete on "Debit or Credit Card" form, it redirects me to page that does not exist. From "http://localhost:3000/en/renew-license" to "http://renew-license/". There is no error raised, no network request made.

### 🤔 Expected Behavior

Using autocomplete causes no redirect

### 🔬 Minimal Reproduction

```markdown
1. Click "Debit or Credit Card" payment option
2. Click on any address-related field like "Street address" or "ZIP code"
3. Choose suggested option to autocomplete form
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | ^8.1.3     |
| next             | ^14.0.1    |
| Browser          | Google Chrome Version 119.0.6045.106 (Official Build) (64-bit)
| Operating System | Windows 11 Home
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Krangth** [comment]
had the same problem and im not even using react. it was a bug in chrome as it went away after an update
