### ISSUE TITLE
[DOCS]: Typing and Documentation Issues with onShippingAddressChange 

### ISSUE THREAD

**Issue by AngieDefiolle** [paypal/react-paypal-js#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Hello,

The **onShippingAddressChange** prop of the **PayPalButtons** component does not seem to be correctly typed, is non-compliant with the **paypal-js** SDK, and is not documented.

For example:
```tsx
      <PayPalButtons
        onShippingAddressChange={(address, actions) => {
          // @ts-ignore
          return actions.reject(address.ERRORS.ADDRESS_ERROR);
        }}
      />
```

* The **paypal-js** SDK appears to expose two methods, **actions.reject** and **actions.resolve**, but here only reject is available.
* By default, the displayed message is something like "unable to update your address." I eventually managed to display a different message by using an untyped **errors** property available on the **address** object and passing it to the **reject** function, which according to its type, does not accept any parameters.
* Additionally, the messages provided in the **ERRORS** property **are not translated** according to the current language of the client, which is the case with **paypal-js**.

**Comment by richbarrett7** [comment]
bump
