### ISSUE TITLE
[BUG]: PayPalHostedFieldsProvider does not support vault token creation

### ISSUE THREAD

**Issue by stevium** [paypal/react-paypal-js#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

As documented in the SDK:
 https://developer.paypal.com/docs/checkout/save-payment-methods/purchase-later/js-sdk/cards/

HostedFields should support card vaulting, in order to Save cards for later purchase, instead of making a transaction on every checkout.

However, `PayPalHostedFieldsProvider` only has a  `createOrder` callback which can only be used to create an order and return an ID of a purchase.

`createVaultSetupToken` on the other hand is supposed to create a token as a result of `api.paypal.com/v3/vault/setup-tokens`, which is followed by `onApprove` used to store the token back to the server.

### 😕 Current Behavior

`PayPalHostedFieldsProvider` only supports `createOrder` callback which is not suitable for `vaultSetupToken` creation.

### 🤔 Expected Behavior

`PayPalHostedFieldsProvider` should expose `createVaultSetupToken` and `onApprove` properties.

### 🔬 Minimal Reproduction

```markdown
1. Check SDK types on following URL: https://github.com/paypal/react-paypal-js/blob/main/src/types/payPalHostedFieldTypes.ts#L109
2. Observe that `createVaultSetupToken` property is missing
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | v8.1.3     |
| Browser          | all        |
| Operating System | all        |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0-harshit-0** [comment]
Hello,
Is it fixed?

**Comment by mawais78** [comment]
Facing the same issue.
