### ISSUE TITLE
[BUG]: npm installs 0.0.1-security security holding package

### ISSUE THREAD

**Issue by mckinlde** [paypal/react-paypal-js#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

running npm install @paypal/react-paypal-js installs a version that claims to be insecure, and is at minimum non-functional

### 😕 Current Behavior

cat package.json:
`{
  "name": "react-paypal-js",
  "version": "0.0.1-security",
  "description": "security holding package",
  "repository": "npm/security-holder"
}`

### 🤔 Expected Behavior

version 8.1.3 installed

### 🔬 Minimal Reproduction

```markdown
1. Open AML 2023 in EC2 Instance
2. >> npm install @paypal/react-paypal-js
3. >> cd node_modules/react-paypal-js
3. >> cat package.json
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 0.0.1-security |
| Browser          | n/a        |
| Operating System | AML 2023   |
```

### Relevant log output

```shell
[ec2-user@ip-redacted]$ npm install @paypal/react-paypal-js

added 1 package, and audited redacted 

[ec2-user@ip-redacted]$ cd node_modules/
[ec2-user@ip-redacted node_modules]$ cd react-paypal-js
[ec2-user@ip-redacted react-paypal-js]$ ls
README.md  package.json
[ec2-user@ip-redacted react-paypal-js]$ cat package.json
{
  "name": "react-paypal-js",
  "version": "0.0.1-security",
  "description": "security holding package",
  "repository": "npm/security-holder"
}
[ec2-user@ip-redacted react-paypal-js]$
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

I got here as a novice end user integrating advanced checkout via [this guide](https://developer.paypal.com/integration-builder/)

**Comment by mckinlde** [comment]
Installing with package-lock produces same behavior:

[ec2-user@ip-redacted ~]$ cat package.json
{
  "name": "redacted",
  "version": "0.1.0",
  "private": true,
  "proxy": "redacted",
  "dependencies": {
    redacted
    "@paypal/react-paypal-js": "^8.1.3",
    redacted
  },
  redacted
}
[ec2-user@ip-redacted ~]$ npm install

added 1 package, and audited redacted

[ec2-user@ip-redacted ~]$ cd node_modules/react-paypal-js/
[ec2-user@ip-redacted react-paypal-js]$ ls
README.md  package.json
[ec2-user@ip-redacted react-paypal-js]$ cat package.json 
{
  "name": "react-paypal-js",
  "version": "0.0.1-security",
  "description": "security holding package",
  "repository": "npm/security-holder"
}

**Comment by mckinlde** [comment]
Same behavior when installing with version specified, is this package deprecated?


Node.js v18.17.1
[ec2-user@ip-redacted ~]$ npm install @paypal/react-paypal-js@8.1.3

added 1 package, and audited redacted

Run `npm audit` for details.
[ec2-user@ip-redacted ~]$ cd node_modules/react-paypal-js/
[ec2-user@ip-redacted react-paypal-js]$ ls
README.md  package.json
[ec2-user@ip-redacted react-paypal-js]$ cat package.json
{
  "name": "react-paypal-js",
  "version": "0.0.1-security",
  "description": "security holding package",
  "repository": "npm/security-holder"
}

**Comment by gregjopa** [comment]
Also, here's where you should expect this package to be installed in the node_modules folder: `cd node_modules/@paypal/react-paypal-js/`

**Comment by mckinlde** [comment]
Update: I am unable to confirm Advanced Payments React integration because of another error; it seems the access token returned by PayPal is assuming a Braintree integration?  I've opened an issue at the relevant level [here](https://github.com/paypal/react-paypal-js/issues/410).
