### ISSUE TITLE
[FEATURE]:  Disable shipping form

### ISSUE THREAD

**Issue by armandoborge** [paypal/react-paypal-js#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

To improve the user experience, it would be beneficial to allow users to opt out of providing a billing address when using the "card" funding source. This option would streamline the checkout process and make it more convenient for users.

**Comment by jecsham** [comment]
@armandoborge 
You can disable shipping form by setting `shipping_reference` to `NO_SHIPPING` in the application context object when creating an order.
```js
createOrder={(data, actions) => {
          return actions.order
            .create({
              application_context: {
                shipping_preference: "NO_SHIPPING",
              },
...
```

**Comment by armandoborge** [comment]
I am creating the order exactly like that but on the backend side. 

```
await fetch(`.../v2/checkout/orders`, {
        method: 'POST',
        headers: ...,
        body: JSON.stringify({
            intent: 'CAPTURE',
            purchase_units: [
                ...
            ],
            application_context: {
                shipping_preference: 'NO_SHIPPING',
            },
        }),
    })
```

According to this doc: https://developer.paypal.com/docs/api/orders/v2/, the `application_context` property is supported in the API. Yeah, it is marked as deprecated but still supported; however, setting the property has no effect on the UI.

Another thing: using the new property `payment_source` -> `paypal` -> `shipping_preference` causes the next API call (capture payment) to fail. So, the deprecated property has no effect, and the new one causes an issue on the capture payment API call.

**Comment by wsbrunson** [comment]
@armandoborge I believe you would want your `body` to look like this:
```
{
  ...
  body: JSON.stringify({
    "intent": "CAPTURE",
    "purchase_units": [ ... ],
    "payment_source": {
      "paypal": {
        "experience_context": {
          "shipping_preference": "NO_SHIPPING"
        }
      }
    }
  })
}
```

`experience_context` is the name of the key in Orders v2

**Comment by trippingcats** [comment]
Hi Shane @wsbrunson
Thanks, your code works for the **paypal** **payment_source**; however I am trying to disable the shipping address on the **card** **payment_source** as well. It seems the later is not possible. 


```
payment_source: {
    paypal: {
        experience_context: {
            shipping_preference: 'NO_SHIPPING',  // This works perfectly
        },
    },
    card: {
        experience_context: {
            shipping_preference: 'NO_SHIPPING', // This doesn't exists 
        },
    },
},
```

Can you please confirm if disabling the shipping address from **card** type payment methods is indeed not supported?
