### ISSUE TITLE
[BUG]: AED Currency not working while integrating with braintree

### ISSUE THREAD

**Issue by amjadkhan896** [paypal/react-paypal-js#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

Hi all,

I integrated with braintree example and i set the currency AED. On official documentation of Braintree we checked it is accepting the currency AED. It was working fine, but from today morning it's stop working and when i click on the button I receive the below message.  I am attaching the screenshot below

<img width="1281" alt="image" src="https://github.com/paypal/react-paypal-js/assets/11747524/ed54107c-b3e7-4c4d-bf87-48ea9514a1b0">

<img width="1465" alt="Screen Shot 2024-01-29 at 3 14 27 PM" src="https://github.com/paypal/react-paypal-js/assets/11747524/477f6509-30b8-4579-8ed1-c09602a03a08">

Any help will be appreciated

Thanks

**
errorDetails
: 
[{issue: "CURRENCY_NOT_SUPPORTED",…}]
errorMessage
: 
"The requested action could not be performed, semantically incorrect, or failed business validation. --- Currency code is not currently supported. Please refer https://developer.paypal.com/docs/integration/direct/rest/currency-codes/ for list of supported currency codes."
errorName
: 
"UNPROCESSABLE_ENTITY"**

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thujaar** [comment]
You might want to look that:
(To specify currencies in request URI and body parameters, use [three-character ISO-4217](https://en.wikipedia.org/wiki/ISO_4217#Active_codes) codes.

follow the link,  https://en.wikipedia.org/wiki/ISO_4217#Active_codes

**Comment by amjadkhan896** [comment]
> You might want to look that: (To specify currencies in request URI and body parameters, use [three-character ISO-4217](https://en.wikipedia.org/wiki/ISO_4217#Active_codes) codes.
> 
> follow the link, https://en.wikipedia.org/wiki/ISO_4217#Active_codes

I am using the same key as mentioned in the docs. **AED** for UAE currency

**Comment by Thujaar** [comment]
try to use numric key, 784 of iso code

**Comment by amjadkhan896** [comment]
> try to use numric key, 784 of iso code

with numeric even though the button is not loading
