### ISSUE TITLE
[Feature] Expose script error state

### ISSUE THREAD

**Issue by dreyks** [paypal/react-paypal-js#46]
### 🚀 Feature Proposal

The library should expose the failing state of the SDK script

### Motivation

There's currently no indication in case the SDK script fails to load for any reason so there's no way for the application to figure out that the script has failed

### Example

This information would be useful to have the ability to notify the app user that they should take some actions like reloading the page or checking their network connection

if the script fails to load loadScript [rejects](https://github.com/paypal/paypal-js/blob/cbe0bf00344e3d105e9d66e7a6a618b757842a3c/src/main.js#L32-L34) but 
PayPalScriptProvider does not catch the rejected Promise
https://github.com/paypal/react-paypal-js/blob/d0a0f38881fc73abafac5302eb2873882719f328/src/ScriptContext.js#L59-L62

We can replace `isLoaded` state with a `loading/loaded/error` state. This would be a breaking change so we can first introduce a new field while keeping `isLoaded` for the backward compatibility

If you're interested I can take a stab at this

**Comment by gregjopa** [comment]
Hi @dreyks, this is a great feature request! 🚀  I totally overlooked error handling with script loading in the ScriptContext. 

> We can replace isLoaded state with a loading/loaded/error state.

I'm onboard with this design. Makes sense to track more about loading in state, including if it failed. Have you seen any other react libraries using this pattern? I'd like to learn more about it.

We'd happily do a major version release for this feature. We are interested and it would be awesome if you could send a PR for this. Happy to help answer any questions you have.

**Comment by dreyks** [comment]
this is an enum pattern that is highly recommended by many including Kent C. Dodds https://kentcdodds.com/blog/stop-using-isloading-booleans/

I'll try to come up with a PR in the next couple of days
