### ISSUE TITLE
[Feature] Hosted Fields component

### ISSUE THREAD

**Issue by mglaman** [paypal/react-paypal-js#49]
### 🚀 Feature Proposal

It'd be great to have a hosted fields component and support: https://developer.paypal.com/docs/business/checkout/advanced-card-payments/#

Currently, you cannot set the client-token as an option on the PayPalProvider. So even trying to write a custom component will not work.

### Motivation

We want to embed hosted fields

### Example

We've implemented this for the Drupal Commerce PayPal integration and are adding a headless example.

**Comment by mglaman** [comment]
Oh, just because it isn't in the props types didn't mean it was supported.

```
      <PayPalScriptProvider options={{
        'components': 'hosted-fields,buttons',
        'client-id': process.env.REACT_APP_PAYPAL_SB_CLIENT_ID,
        'data-partner-attribution-id': 'CommerceGuys_Cart_SPB',
        'data-client-token': process.env.REACT_APP_PAYPAL_SB_CLIENT_TOKEN,
      }}>
```

With this we can detect if eligible and use a hosted field setup or fallback to smart buttons

```
  const [{ isLoaded, options }] = usePayPalScriptReducer();
  const [supportsHostedFields, setSupportsHostedFields] = useState(null);

  useEffect(() => {
    console.log(options);
    if (isLoaded) {
      setSupportsHostedFields(window.paypal.HostedFields.isEligible())
    }
  }, [isLoaded])
```

**Comment by gregjopa** [comment]
@mglaman thanks for opening up this issue. You are correct that `data-client-token` should work fine even though it's missing from the prop-types. Thanks for pointing that out. I added it to the prop-types in PR #51.

Hosted-fields should definitely be possible using the custom component approach you outlined in https://github.com/paypal/react-paypal-js/issues/49#issuecomment-718198987. 

Another thing to note is the upcoming 2.0 release drops the `isLoaded` option and replaces it with `isPending`, `isResolved`, and `isRejected`. Ex:

```js
const [{ isResolved, options }] = usePayPalScriptReducer();
  const [supportsHostedFields, setSupportsHostedFields] = useState(null);

  useEffect(() => {
    console.log(options);
    if (isResolved) {
      setSupportsHostedFields(window.paypal.HostedFields.isEligible())
    }
  }, [isResolved])
```

I'm going to close this one out. Please re-open if you encounter any problems with the hosted-fields implementation.

**Comment by getTobiasNielsen** [comment]
Hey @gregjopa

Thank you for your great work for react community.

Reading through this issue, it looks like the data is being pulled from a environment variable, that looks wrong to me, after reading the API.
E.g.
> ```
>         'data-client-token': process.env.REACT_APP_PAYPAL_SB_CLIENT_TOKEN,
> ```

The API appears to require a new client_token per time the component gets loaded, a token that has to be generated with the access_token, one acquires with the API credentials.
![tip](https://user-images.githubusercontent.com/54803528/111874479-bbdeb800-8995-11eb-81f9-9b2c87f53c3a.PNG)
[(source)](https://developer.paypal.com/docs/business/checkout/advanced-card-payments/#2-generate-client-token)

To me it makes sense to store the API credentials on the server, and use those to return the client_token to the SPA.

Is this incorrect?

Again, thanks for your work. I am sure I'll have more questions as I too am very interested in having hosted fields.

**Comment by gregjopa** [comment]
Hi @getTobiasNielsen, I think an environment variable was just an example. The key thing is this is a sensitive runtime value that you should not check into version control with your client-side code.

> A client token is required to uniquely identify your buyer.

The docs mention that this client token is buyer specific. So you will need a new value every time you show the hosted fields component to a buyer. The more I think about it, adding a `<PayPalHostedFields>` component that plays nice with the Provider would be a great addition to react-paypal-js.

For now, you could try this:

Step 1 - wrap your app with the PayPalScriptProvider and pass the static param values that typically don't change often. Do not include a data-client-token here:
```js
// static params that are passed to the ReactPaypalProvider
const scriptProviderOptions = {
    "client-id": "test",
    "components": "buttons,hosted-fields"
};

// wrap your app with this
<PayPalScriptProvider options={scriptProviderOptions}></PayPalScriptProvider>
```

Step 2 - Create a hosted fields component that makes an ajax call to fetch the data-client-token value. I haven't tested this but wanted to share some initial thoughts regarding some of the logic needed:

```js
const [{ options }, dispatch] = usePayPalScriptReducer();
const [clientToken, setClientToken] = useState("");

// use fetch or axios or whatever to make a client-side call 
// to your server-side endpoint that wraps the /identity/generate-token endpoint
fetch("your/server/endpoint/for/generating/buyer/session-token")
    .then(response => response.json())
    .then(data => {
        setClientToken(data.clientToken);
        // pass client_token value to the data-client-token attribute of the JS SDK
        dispatch({
            type: "resetOptions",
            value: {
                ...scriptProviderOptions,
                "data-client-token": data.clientToken,
            },
        });
    });

 useEffect(() => {
    if (options.isResolved && clientToken) {
      setSupportsHostedFields(window.paypal.HostedFields.isEligible())
    }
  }, [isResolved, clientToken])

```

**Comment by getTobiasNielsen** [comment]
@gregjopa  Thank you for the speedy answer!

Passing the `data-client-token` seems to be working. Nice catch with the dispatch, I wasn't aware of how this library worked, but I see `usePayPalScriptReducer` has a lot of use.

I'll return once I've had a chance to look at the hosted fields.

Thanks again!

**Comment by getTobiasNielsen** [comment]
@gregjopa `window.paypal.HostedFields.isEligible()` seems to return `true` now.

It appears isResolved isn't defined in options, but can be grabbed on its own from `usePayPalScriptReducer`, like in your original example.

I was thinking about what you said about a `<PayPalHostedFields>`. I'd love to get involved in that, do you have any initial thought about how you would want it to look?

I was considering a PaypalHostedFields wrapping around the card / billing address fields, that has some internal logic, and error handling similar to that of `PayPalButtons`.
It would be able to accept things like createOrder, maybe styling or fields

It would also render things like the following unnecessary, as that could be done internally, and even give an error if the component was being used, but was missing from `components: "buttons,hosted-fields"`

```js
useEffect(() => {
    console.log(options);
    if (isLoaded) {
      setSupportsHostedFields(window.paypal.HostedFields.isEligible())
    }
  }, [isLoaded])
```
Here I'm wondering if, it makes sense to make more components, e.g. like a cvv component, because that makes it a lot less customizable. While it might work with cvv, even that could be required to be displaying cvc. This problem only gets harder with fields like extendedAddress, because that is very much based on localization.

```js
<PaypalHostedFields createOrder= {} >
   // card fields here
   // billing address here
</PaypalHostedFields>
```

Open to hearing what you think about this approach, where it's only a wrapper, and the html inside is left uncontrolled and referenced to with `refs` instead of `id`.

**Comment by gregjopa** [comment]
Hi @getTobiasNielsen, it's good to hear your got Hosted Fields working! 🎉  

> It appears isResolved isn't defined in options, but can be grabbed on its own from usePayPalScriptReducer, like in your original example.

Whoops, my mistake. It's not defined in the options (those are just for the params/attributes passed to the JS SDK script). I fixed it in the code snippet above.

> Open to hearing what you think about this approach, where it's only a wrapper, and the html inside is left uncontrolled and referenced to with refs instead of id.

I like that idea! I would like to keep the `<PayPalHostedFields>` as light weight as possible. Supporting custom content as `props.children` seems like a good idea. Would you be up for working on a prototype for this?

**Comment by getTobiasNielsen** [comment]
I'll make a prototype.

From my initial search, I see that the JS SDK doesn't have types for hosted-fields, so will see what I end up with.

**Comment by getTobiasNielsen** [comment]
A lot of the types are missing, would need to implement those, either in the file or in their respective places.

This is an initial prototype.

I was thinking it could be smart to add one of the default spinners I've seen paypal use, or if people don't like it, let people add a prop with a spinner element or some custom react component, if they fancy that instead.

**Comment by vrgimael** [comment]
Hey - is there any updates here? Trying to implement custom designs on payment fields, this would be pretty helpful
