### ISSUE TITLE
[Bug] Card Fields instead of Popup Checkout flow

### ISSUE THREAD

**Issue by gmerino92** [paypal/react-paypal-js#50]
Hi guys, didn't know if this qualified as a bug or not, but I'm getting some weird behaviour from the "Debit or Credit Card" button, or at least inconsistent with the examples shown in the Storybook.

I've implemented everything as suggested in the docs, using all the defaults and whenever I click on the "Debit or Credit Card" button I'm getting the following form:

<img width="396" alt="Captura de Pantalla 2020-10-29 a la(s) 01 50 23" src="https://user-images.githubusercontent.com/11561127/97527026-1f396080-1989-11eb-9870-7a99337cfd3d.png">

which animates in, instead of it taking me to the popup checkout flow as it does in the storybook example. (Shown below)

<img width="623" alt="Captura de Pantalla 2020-10-29 a la(s) 01 52 19" src="https://user-images.githubusercontent.com/11561127/97527145-64f62900-1989-11eb-9bd5-c0957020d7aa.png">

I'm wondering if this is the intended behaviour and if so, how could I revert it to the popup flow shown in the storybook examples? I couldn't find any info about this on the documentation.

FYI, I'm running v1.0.3

Sorry if this is not the appropriate forum for this question and thanks in advance for any help.

**Comment by gregjopa** [comment]
Hi @gmerino92 thanks for reporting this! It does appear to be a bug, at least with the storybook demos. I'm going to continue troubleshooting.

**Comment by gmerino92** [comment]
Great, @gregjopa . Let me know if there is any more info I can provide to help.

**Comment by gmerino92** [comment]
Awesome, thanks.
