### ISSUE TITLE
`changeCurrency` not available anymore

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/react-paypal-js#54]
I saw that `changeCurrency` was removed from the `actions`. What should be used now to change the currencies?

**Comment by gregjopa** [comment]
Hi @pedroapfilho, we recommend using the new `resetOptions` action. Here's an example story showing how to use it to change currency:
- https://github.com/paypal/react-paypal-js/blob/main/src/stories/usePayPalScriptReducer.stories.js#L18-L35
- https://paypal.github.io/react-paypal-js/?path=/story/example-usepaypalscriptreducer--currency-usd

Let me know if this solution works for you.

**Comment by pedroapfilho** [comment]
That's exactly what I needed! Thanks a lot for the quick response! Maybe you could open a `CONTRIBUTION.md` for this repo so we could document these props, maybe a table of possible props.

Thanks a lot!

**Comment by gregjopa** [comment]
@pedroapfilho happy to help! 

That's a good idea to document the options with `usePayPalScriptReducer`. We plan on doing that in the near future.
