### ISSUE TITLE
[Feature] Displaying LoadingIndicator until onApprove promise chain has finished

### ISSUE THREAD

**Issue by mercteil** [paypal/react-paypal-js#62]
I am facing an issue where my `server side` implementation of paypal payments has to wait until the payment is `captured` AND then do some DB operations (writing transactions id to DB, manipulating order status, etc.). Therefore the `capture` method has to successfully finish first.

As I found out the `capture` method closes the `paypal iframe` on the client side whenever it finishes successfully. Leaving the client in a state of uncertainty while some backend operations are still running.

This lib provides the ability of implementing a loading indicator by accessing the script hook like 
`const [{ isPending }] = usePayPalScriptReducer();` [[see docs here]](https://paypal.github.io/react-paypal-js/?path=/story/example-usepaypalscriptreducer--loading-spinner). (By the way the docs actually do not show how to use the hook. I manually found it [[here]](https://github.com/paypal/react-paypal-js/blob/9c8d8e922cbb92d12b400146fac0688fb2c5722c/src/stories/usePayPalScriptReducer.stories.js#L94).)

Feature: It would be great to have the `isPending` state until the transaction is not only captured but the `onApprove promise entirely finishes`.

I have a workaround, but it would be much cleaner with the `isPending` script hook:

```javascript
import React, { useState } from 'react';
import config from '@root/config';
import {  PayPalButtons,  PayPalScriptProvider,  usePayPalScriptReducer } from '@paypal/react-paypal-js';
import { Spinner } from 'appui';
import { StyledSpinnerContainer } from './styled';

const LoadingIndicator = ({ isLoading }) => {
  const [{ isPending }] = usePayPalScriptReducer();

  return (
    ((isLoading || isPending) && (
      <StyledSpinnerContainer>
        <Spinner />
      </StyledSpinnerContainer>
    )) ||
    ''
  );
};

const Paypal = ({ options, createOrder, onApprove, onError }) => {
  const [isLoading, setIsLoading] = useState(false);

  return (
    <PayPalScriptProvider
      options={{ ...options, components: 'buttons', 'client-id': config.paypalClientId }}
    >
      <LoadingIndicator {...{ isLoading }} />
      {!isLoading && (
        <PayPalButtons
          {...{
            style: { color: 'blue' },
            createOrder,
            onApprove: (...args) =>
              Promise.resolve()
                .then(() => setIsLoading(true))
                .then(() => onApprove(...args))
                .finally(() => setIsLoading(false)),
            onError,
          }}
        />
      )}
    </PayPalScriptProvider>
  );
};

export default Paypal;

**Comment by yocmen** [comment]
This could be awesome, I have the same issue, I just put a "loading" overlay in the back of the Paypal overlay... but something native could be better

**Comment by gregjopa** [comment]
Hi @mercteil, thanks for sharing how you're managing loading state. It's a cool example. We are missing docs for the `usePayPalScriptReducer` hook. Sorry that was a pain to figure out.

The `usePayPalScriptReducer` hook is for updating state for the JS SDK script params. It currently does not manage any state for components, only the script-level params. It's possible to have multiple different `<PayPalButtons />` components inside the `<PayPalScriptProvider>` context so managing order transactions in the `usePayPalScriptReducer` would be tricky. 

I'm going to discuss this feature request with the team and will follow up in a couple days.

**Comment by gregjopa** [comment]
hi @mercteil I spoke about this with the team internally. It turns out this is a common complaint and something we are going to fix in the sdk itself. I've created this github issue to track it: https://github.com/paypal/paypal-checkout-components/issues/1486. 

I think your work around is a great way to handle this for the time being. I'd like to avoid adding anything to react-paypal-js for this since it will be fixed in the SDK itself.
