### ISSUE TITLE
PayPalScript refreshing

### ISSUE THREAD

**Issue by FantaBoy1** [paypal/react-paypal-js#65]
Hi guys,

I'm trying to figure out how should I work with changing params like currency but I don't see any examples to implement it. I think it would be great to place more info about it. Right know im trying this approach:

```
const PaypalProvider = ({ children }) => {
  const {
    state: { paypal },
  } = useContext(AppContext);

  console.log(paypal);

  return (
    <PayPalScriptProvider
      key={paypal}
      options={{
        currency: paypal.currency,
        "client-id":
          "####",
      }}
    >
      {children}
    </PayPalScriptProvider>
  );
};

export default PaypalProvider;
```

So I have a global state that changes, and I see it in console.log() but how should I refresh this provider? Right now it doesn't work, and any changes doesn't affect this provider. I was trying to do something with a **key** but it doesn't work too. Maybe I'm working with it in a bad way?

**Comment by gregjopa** [comment]
Hi @FantaBoy1, please use the `usePayPalScriptReducer` to update the provider. Sorry you were confused by this. We are working on adding some documentation for it.

Here's a storybook example that shows how to update currency:
- https://github.com/paypal/react-paypal-js/blob/main/src/stories/usePayPalScriptReducer.stories.js#L25
- https://paypal.github.io/react-paypal-js/?path=/story/example-usepaypalscriptreducer--currency-usd

**Comment by FantaBoy1** [comment]
Great, thank You very much
