### ISSUE TITLE
[Feature] Use TypeScript

### ISSUE THREAD

**Issue by gregjopa** [paypal/react-paypal-js#69]
### 🚀 Feature Proposal

Update this library to use [TypeScript](https://www.typescriptlang.org/).

### Motivation

Several developers have requested TypeScript types for this library. We could solve that problem in a few different ways. One way is to convert this codebase to TypeScript and include types for all publicly exported functions.

Here's a good doc about [the advantages of TypeScript](https://www.typescriptlang.org/why-create-typescript).

### Related PRs

#30 - @camsjams shared some really helpful types here which would be a good starting point: https://gist.github.com/camsjams/b843637df7a30c260b341daf97a96d60
#53

### Additional Info

The current use of PropTypes is powering the Storybook docs: https://paypal.github.io/react-paypal-js/?path=/docs/example-paypalbuttons--default. We want to continue supporting PropTypes like this with using TypeScript. That may be one of the more challenging parts of the migration.

Any objections to migrating to TypeScript?

Any volunteers to take this work up?

**Comment by sahaparamjit** [comment]
@gregjopa I would like to work on this. I am learning TypeScript. So I guess it would be great if I take that.

**Comment by gregjopa** [comment]
@sahaparamjit that would be awesome! Happy to answer any questions you may have along the way.

**Comment by gregjopa** [comment]
Hi @sahaparamjit just wanted to check in. Have you had a chance to work on this? Let me know if you have any questions.

**Comment by isaacewing** [comment]
@gregjopa  I would also like to work on this. you made a great component... in javascript ha. I'm pretty good with typescript and would like to help. right now, i'm creating interfaces for my project and would like to contribute them the ts version of this when it's ready

**Comment by gregjopa** [comment]
@isaacewing that sounds great! I'd appreciate the help.

**Comment by HunteRoi** [comment]
Hey there! I know this started a few days ago but would it be possible to have some updates? I am working on a React+Typescript project and I would be really happy to see this library updated to its TS version :smile:

**Comment by gregjopa** [comment]
Hello TypeScript friends! I started hacking on TypeScript for paypal-js and would appreciate a code review if anyone has time: https://github.com/paypal/paypal-js/pull/55. The idea is to add TypeScript to paypal-js and then to this library (which depends on paypal-js).

The idea with this design is paypal-js would provide type definitions for the whole JS SDK so everyone will know what's possible with `window.paypal`. I also think the rollup config work from this PR could be applied to react-paypal-js.

**Comment by HunteRoi** [comment]
Hello guys! Happy New Year 😄 

I see that paypal/paypal-js#55 is merged. Can we have an update on this issue as well please?

**Comment by gregjopa** [comment]
Hi @HunteRoi! Happy new year! I put together a PR for adding TypeScript: #71 

Please review the PR and test out the beta!

Also, there are a lot of `@ts-expect-error` statements being used to avoid errors. I could use some help with cleaning these up. I would gladly accept PRs to this "typescript" branch.

**Comment by gregjopa** [comment]
react-paypal-js@4.0.0 has been published to npm which includes TypeScript type definitions! Please upgrade to v4 and let me know your feedback!
