### ISSUE TITLE
Impossible to style top-level container

### ISSUE THREAD

**Issue by sherlaimov-osdb** [paypal/react-paypal-js#70]
### 🐞 Describe the Bug

The button gets rendered with a top-level div with no attributes. There's no direct way to either place a class name or otherwise style the parent div.

### 🔬 Minimal Reproduction

Install the React PP buttons plugin and try setting a custom button width.

### 😕 Actual Behavior

Impossible to specify a class name or otherwise style the top-level div.

### 🤔 Expected Behavior

An explicit way to set a class name or style the top-level div with tools such as styled components and the like.
### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 3.0.3
| Browser          | Chrome
| Operating System |iOS

**Comment by gregjopa** [comment]
Hi @sherlaimov-osdb, the `className` prop has been added to every component and is part of the 4.0.0 release. Please give it a try.
