### ISSUE TITLE
[Bug] Sometimes get 'script-src-elem' was not explicitly set error on windows

### ISSUE THREAD

**Issue by RahavLussato** [paypal/react-paypal-js#72]
### 🐞 Describe the Bug

Sometimes on our sandbox env when we try click on the Paypal button to open the modal, its get stuck in infinite loading spinner and we see this error in the console
```
Refused to load the script 'http://bpp.eset.com/en-US/Redirect-Switch?token=XXX' because it violates the following Content Security Policy directive: "script-src 'self' https://.paypal.com: https://*.paypalobjects.com 'unsafe-inline' 'unsafe-eval' https://apis.google.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

### 🔬 Minimal Reproduction

Hard to reproduce as it sometimes happens and after some refreshes, it suddenly works.

### 😕 Actual Behavior

PayPal SDK not loaded because of the above error.

### 🤔 Expected Behavior

PayPal SDK should load and the Paypal modal should show the regular state.

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 2.0.0 |
| Browser          | Chrome |
| Operating System | Windows 10 |

**Comment by gregjopa** [comment]
Hi @RahavLussato I'm not familiar with that error. Are you using a [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) on your site?

If possible, please share the callback you are using with `createOrder`

**Comment by RahavLussato** [comment]
hi @gregjopa we are not using CSP and the weird thing is that happens only on windows on OSX it works well.

here is our createOrder callback:
```
const createOrder = (data, actions) => {
		return actions.order.create({
			purchase_units: [
				{
					amount: {
						value: amount,
					},
					payee: {
						merchant_id: payeeMerchantId,
						email_address: payeeEmail,
					},
				},
			],
		});
	};
```

**Comment by gregjopa** [comment]
Hi @RahavLussato, your `createOrder` callback function looks fine to me. The error seems like it's coming from the PayPal JS SDK and not from this React component. We are frequently pushing fixes to the different layers of the PayPal Checkout experience so this may have been fixed. 

If you are still seeing this error please open up a bug report here in paypal-checkout-components: https://github.com/paypal/paypal-checkout-components/issues/new/choose.

**Comment by RahavLussato** [comment]
thanks @gregjopa , i opened it there https://github.com/paypal/paypal-checkout-components/issues/1531
