### ISSUE TITLE
[Bug] unexpected token

### ISSUE THREAD

**Issue by vladimircherevko** [paypal/react-paypal-js#76]
### 🐞 Not js syntax

"@paypal/react-paypal-js": "^4.0.0"   in dist\react-paypal.node.js:286  unexpected token :    
buttons?.current?.close();
 _______ ^_______ ^

**Comment by gregjopa** [comment]
Hi @vladimircherevko nice catch! That is indeed a bug. That syntax is a new JS feature called [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) and I thought it would get transpiled down to ES5 in the dist files. I'll publish a bugfix asap.

**Comment by vladimircherevko** [comment]
thanks

**Comment by gregjopa** [comment]
I just published [4.0.1](https://www.npmjs.com/package/@paypal/react-paypal-js/v/4.0.1) to npm which includes the bugfix for this. This should be resolved. Thanks for reporting the issue 😄
