### ISSUE TITLE
How to re-render the Buttons component when createOrder() function changes

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/react-paypal-js#77]
I'm creating a checkout with the `PayPalButtons`, and I found an interesting bug, that made me realize something... We don't re-render the button if one of its functions changes, meaning that I created the `createOrder` function on the page, and this function depended on the shipping address coming from the context. It's undefined at first, but as soon as it gets re-hydrated, it gets the correct object.

The issue is that the `PayPalButtons` component doesn't care about this change, it doesn't have anything on the `useEffect` dependencies saying that it should, like:

https://github.com/paypal/react-paypal-js/blob/ba915eb6a932f097e0b3b5302ee341a3a8166027/src/components/PayPalButtons.tsx#L70

And then what I had to do is create add:

```js
        forceReRender={!!shippingAddress}
```

That makes the button re-render the function on re-hydration.

I think we should add the functions on the dependency there, and ask our users to use `useCallback` with some dependencies on their apps, it would solve this type of issue.

**Comment by gregjopa** [comment]
Hi @pedroapfilho, we added the `forceReRender` prop in this PR: https://github.com/paypal/react-paypal-js/pull/56. This was added to be conservative with our re-render strategy. Here's a storybook example showing how to use `forceReRender` when the amount changes: https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--dynamic-amount

> I think we should add the functions on the dependency there, and ask our users to use useCallback with some dependencies on their apps, it would solve this type of issue.

Unfortunately props that are functions do not play nice with the `useEffect` watch list: https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--dynamic-amount. They are always considered "changed" even when the actual function is exactly the same. The `forceReRender` prop seems to provide a way for the developer to manage re-rendering so I don't see this as a blocker. I'm open to PRs if you find another way to manage this.

**Comment by pedroapfilho** [comment]
@gregjopa actually, that's why you could ask the developers to use `useCallback` in their functions, this is a common practice in other libraries.

**Comment by gregjopa** [comment]
The `useCallback` hook is pretty cool. What do you think about using it with `createOrder` and `forceReRender` like so? It's using createOrder with a dynamic amount. I think the same could be applied to a dynamic shippingAddress.

```js

export const DynamicAmount = () => {
    const [amount, setAmount] = useState(2);
    const [orderID, setOrderID] = useState(false);

    // use useCallback to only update the value of `createOrder` when the `amount` changes 
    const createOrder = useCallback((data, actions) => {
        return actions.order
            .create({
                purchase_units: [
                    {
                        amount: {
                            value: amount,
                        },
                    },
                ],
            })
            .then((orderID) => {
                setOrderID(orderID);
                return orderID;
            });
    }, [amount]);

    function onChange({ target: { value } }) {
        setAmount(value);
        setOrderID(false);
    }

    return (
        <>
            <select onChange={onChange} name="amount" id="amount">
                <option value="2">$2.00</option>
                <option value="4">$4.00</option>
                <option value="6">$6.00</option>
            </select>
            <p>Order ID: {orderID ? orderID : "unknown"}</p>

            { /* pass createOrder to forceReRender to trigger a re-render when it changes */ }
            <PayPalButtons createOrder={createOrder} forceReRender={createOrder} />
        </>
    );
};
```

I know there's the pain of the extra step of assigning the memoized createOrder to `forceReRender` but it seems like a fair compromise.

**Comment by pedroapfilho** [comment]
Sure is! Do we have docs/stories for this use case? It would be nice to have! I can add!

**Comment by gregjopa** [comment]
> Do we have docs/stories for this use case? It would be nice to have! I can add!

@pedroapfilho that would be awesome! It would be great to update this "Dynamic Amounts" story to use `useCallback` like in the above code snippet: https://github.com/paypal/react-paypal-js/blob/main/src/stories/PayPalButtons.stories.js#L52. Would you be up for sending a PR for that?

It would be cool to add a new story for re-rendering when the shippingAddress changes as well.

**Comment by pedroapfilho** [comment]
I'll create a PR for it this weekend! I have some other use-cases for that too! Like, what should we do when we depend on more than one value? Should how do we create a list of dependencies?

**Comment by pedroapfilho** [comment]
@gregjopa What if we make it accept an array of dependencies on the `forceRerender`? So we can pass a list of values there, and if any changes, we re-render it?

**Comment by gregjopa** [comment]
> @gregjopa What if we make it accept an array of dependencies on the `forceRerender`? So we can pass a list of values there, and if any changes, we re-render it?

@pedroapfilho sure that’s a great idea. Would you be up for sending a PR for this?

**Comment by pedroapfilho** [comment]
Sure! Gonna cook it up this week!

**Comment by fabyeah** [comment]
> > Do we have docs/stories for this use case? It would be nice to have! I can add!
> 
> @pedroapfilho that would be awesome! It would be great to update this "Dynamic Amounts" story to use `useCallback` like in the above code snippet: https://github.com/paypal/react-paypal-js/blob/main/src/stories/PayPalButtons.stories.js#L52. Would you be up for sending a PR for that?
> 
> It would be cool to add a new story for re-rendering when the shippingAddress changes as well.

In the current example, changing the amount will produce the console error `Failed to render <PayPalButtons /> component. Error: Component closed` unless you wait a couple second after each change. I'm using Radio buttons to change the amount and get this quite a lot during normal use.

**Comment by hugo-licon** [comment]
Is there a way to update the order without closing the form? In my case, I want to update the order when the user enters a discount code. But the problem is that if the user fills the form, then adds the discount code, because we updated the order, we need to close the form, so all the data that the user entered is lost and needs to fill the form again

**Comment by theMostCuriousHomunculus** [comment]
use latest values (from state or props) in createOrder function without needing to force a re-render of the paypal buttons component (because that looks bad when it happens on every keystroke of a form input):

`
import {
	type FC,
	useEffect,
	useRef,
} from 'react';
import { PayPalButtons } from '@paypal/react-paypal-js';

const CheckoutButton: FC<{
    email: string;
    address_line_1: string;
    city: string;
    country_code: string;
    first_name: string;
    last_name: string;
    phone_number: string;
    postal_code: string;
    state: string;
    address_line_2?: string | undefined;
}> = (values) => {
	const {
		cartState,
		dispatchCartAction,
		setSnackbarErrorMessage,
	} = useGlobalStateContext();
	const { mode } = usePalletModeContext();
	const cartStateRef = useRef(cartState);
	const valuesRef = useRef(values);

	useEffect(
		() => {
			cartStateRef.current = cartState;
		},
		[cartState],
	);

	useEffect(
		() => {
			valuesRef.current = values;
		},
		[values],
	);

	return (
		<PayPalButtons
			createOrder={async (_data, _actions) => {
				return await asynchronousMutationThatReturnsTheOrderID({
					items: cartStateRef.current,
					shipping: valuesRef.current,
				});
			}}
			forceReRender={[mode]}
			onApprove={async (_data, actions) => {
				if (actions.order) {
					await actions.order.capture();
					dispatchCartAction({ type: 'empty' });
				}
			}}
			style={{
				color: mode === 'dark'
					? 'black'
					: undefined
			}}
		/>
	);
};
`
