### ISSUE TITLE
[Feature] Create a disabled state

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/react-paypal-js#78]
So, right now, the only way to "disable" the button is to make it fail or not show it at all.

It would be good to have an `isDisabled` state, that would disable the button depending on what the user does. For example, when the user doesn't have anything on his cart, or when something is missing on his validation.

**Comment by gregjopa** [comment]
Hey @pedroapfilho that's an interesting idea. I'm open to adding a new prop for enabling/disabling the buttons.  

We do have a way to do form validation with the JS SDK using the onClick and onInit callbacks: https://developer.paypal.com/docs/checkout/integration-features/validation/

But I'm unsure if the pattern translates well into React. A new prop would probably be more convenient for handling the enable()/disable() calls.

**Comment by pedroapfilho** [comment]
This enable/disable calls actually make the button disabled? Or does it only disable the onClick?

**Comment by gregjopa** [comment]
@pedroapfilho I added a new "disabled" prop to the latest release (`@paypal/react-paypal-js@4.1.0`). Here's a storybook demo: https://paypal.github.io/react-paypal-js/?path=/story/example-paypalbuttons--disabled

I'm going to close this issue out. Let me know if you find any problems with this new feature.
