### ISSUE TITLE
Error: Expected an order id to be passed

### ISSUE THREAD

**Issue by anarerdene** [paypal/react-paypal-js#81]
Error: Expected an order id to be passed

![image](https://user-images.githubusercontent.com/2210568/107152537-734ddb00-69a3-11eb-8ada-49afc6c5c858.png)

**Comment by Progressandro** [comment]
Having this same issue, but with subscription_id. Did you find any solution?

**Comment by anarerdene** [comment]
@Progressandro no. can i see your code ?

**Comment by gregjopa** [comment]
Hi @anarerdene thanks for using react-paypal-js! This question isn't related to this react library so I'm going to close it out. Please open a new issue over in paypal-checkout-components for checkout flow questions: https://github.com/paypal/paypal-checkout-components/issues/new/choose.
