### ISSUE TITLE
[FAQ] Where do I find the documentation for 'options'?

### ISSUE THREAD

**Issue by TrejoCode** [paypal/react-paypal-js#83]
### 🐞 Describe the Bug

PayPalScriptProvider supports 'options', but what are those values? Where do i find them?

In general the solution is great, but it seems that there is too much to work on, it takes a lot of documentation and examples.

``` jsx 
<PayPalScriptProvider options={{ "client-id": "sb", "Other?" : "??" }}>
</PayPalScriptProvider>
```

**Comment by gregjopa** [comment]
Hi @TrejoCode, this library uses paypal-js to load the SDK script. These options are documented here: https://github.com/paypal/paypal-js#passing-arguments

Sorry this was not clear. We should add this to the readme.

**Comment by gregjopa** [comment]
Thanks for the feedback on this. I updated the readme with more information about setting `options`: https://github.com/paypal/react-paypal-js#paypalscriptprovider.
