### ISSUE TITLE
paypal button debit or credit card shows create paypal account, how can hide it?

### ISSUE THREAD

**Issue by JELugoM** [paypal/react-paypal-js#84]
Hi, I have been worked on this integration but I have a problem, how can render the paypal button for debit or credit card without show the create paypal account seccion. I just want like the example on your storybook.
![Captura de Pantalla 2021-02-16 a la(s) 1 18 22 p m](https://user-images.githubusercontent.com/30191941/108111307-1fee2380-705a-11eb-9877-f753a3cf469c.png)

But instead of that I get a form with a seccion for create a new paypal account and is required, how can disable that seccion or making not required.

![Captura de Pantalla 2021-02-16 a la(s) 1 10 10 p m](https://user-images.githubusercontent.com/30191941/108111317-254b6e00-705a-11eb-8a75-d4c1c6f1ce30.png)

I hope you can help me, thanks.

**Comment by gregjopa** [comment]
Hi @JELugoM it is not possible to disable that feature in the guest checkout flow in the popup. The inline guest feature is still new and only supported in certain countries. When it's not supported, it falls back to the guest checkout flow in the popup.
