### ISSUE TITLE
[Feature] usePayPalScriptReducer has isReady value

### ISSUE THREAD

**Issue by dan003400** [paypal/react-paypal-js#86]
When using the isPending value from the contextual hook will cause flashing. This only means the script has been loaded, it does not mean that the actual PayPal button are ready and rendered.

If you have spinners for example using isPended, this will remove the spinner and then render nothing for a second or two, then the buttons will load in, this makes for a terrible screen jogging experience.

We need a way to know the buttons are ready to properly transition from loading to ready.

**Comment by dan003400** [comment]
Using local state combined with onInit callback seems to be too late.

**Comment by gregjopa** [comment]
Hi @dan003400, have you seen the loading spinner example in storybook? https://paypal.github.io/react-paypal-js/iframe.html?id=example-usepaypalscriptreducer--loading-spinner&viewMode=story. It's using `isPending`. Do you see the same problem with it? Or is it only with your implementation?

After the sdk script is loaded, the buttons should render instantly. If you are not seeing that, please share a demo and we can help troubleshoot.

**Comment by yocmen** [comment]
maybe using isResolved could help

**Comment by dan003400** [comment]
Well, I have been forced to ditch this package at the moment being that it doesn't even work properly #85
