### ISSUE TITLE
Is it posible to use multiple buttons at the same page?

### ISSUE THREAD

**Issue by yocmen** [paypal/react-paypal-js#87]
Here is an example: [sanboxcode](https://codesandbox.io/s/sad-http-tfnhv?file=/src/PaypalButton.js)

I added 2 buttons (single order and subscription order) but just one works, the dispatch method to reset the options don't look like a good solution in this case,  this is possible? could be nice to have this for some cases.

Thanks.

**Comment by gregjopa** [comment]
Hi @yocmen, currently the PayPal JS SDK does not support rendering an Orders button and a Subscriptions button on the page page. Each of these button types require different query params and have different eligibility requirements. And the JS SDK is currently designed to only support one script to manage all the components on the page. 

I wanted to mention that it is possible to render multiple paypal buttons on the same page that share the same script parameters. We just don't support rendering multiple buttons that require different query params.

**Comment by assainov** [comment]
@gregjopa what's the best practice to have Capture buttons and subscription buttons on the same page? Should we just re-render the `PayPalScriptProvider` with new options?
