### ISSUE TITLE
[Feature] Return custom content when the Button is not eligible

### ISSUE THREAD

**Issue by gregjopa** [paypal/react-paypal-js#90]
### 🚀 Feature Proposal

When rendering the PayPal Button, we only want to render it when it's eligible. For the use case when it's not eligible, we currently render an empty div element. The internet has enough divs already. Let's render `null` instead by default for this use case.

### Motivation

Avoid rendering unnecessary markup. Also, enable devs to show custom content when the buttons are unable to render due to ineligibility. 

### Example

```jsx
<PayPalButton fundingSource={FUNDING.VENMO}>
    {/* this Alert component is just an example. It's not part of react-paypal-js */}
    <Alert message={ `You are not eligible for {FUNDING.VENMO}` } />
</PayPalButton>
```

We'd need to update this code to use the children prop and render that and if there are no children default to null: https://github.com/paypal/react-paypal-js/blob/main/src/components/PayPalButtons.tsx#L134-L140.

**Comment by gregjopa** [comment]
I've been thinking more about this and it would be nice to be able to render custom content when ineligible. It could default to returning `null` but also provide a way to render an alert message to the user that the funding source is not supported. Ex:

```jsx

<PayPalButton fundingSource={FUNDING.VENMO}>
    <Alert message={ `You are not eligible for {FUNDING.VENMO}` } />
</PayPalButton>
```

This is the same pattern used by several html elements as well for serving up fallback content to users (audio/video/canvas etc.). Ex:

```html
<audio controls src="/media/cc0-audio/t-rex-roar.mp3">
    Your browser does not support the
    <code>audio</code> element.
</audio>
```

**Comment by avocadomayo** [comment]
> The internet has enough divs already.

Lol. I don't think the internet can recover from divitis

I'm loving this pattern you proposed!

```js
<PayPalButton fundingSource={FUNDING.VENMO}>
    {/* this Alert component is just an example. It's not part of react-paypal-js */}
    <Alert message={ `You are not eligible for {FUNDING.VENMO}` } />
</PayPalButton>
```

**Comment by gregjopa** [comment]
@avocadomayo thanks for the positive feedback! I'll work on adding this feature.

**Comment by fuxxingbunny** [comment]
Currency does not work ??

```
.create({purchase_units: [{ amount: { 
            currency: "EUR",
            value: price,
          },},],
```
