### ISSUE TITLE
[ASK] purchase_unit currency

### ISSUE THREAD

**Issue by fuxxingbunny** [paypal/react-paypal-js#93]
Currency does not work ??

```
.create({purchase_units: [{ amount: { 
            currency: "EUR",
            value: price,
          },},],
```

**Comment by gregjopa** [comment]
Hi @fuxxingbunny, you need to pass currency in two places:
1. as a query parameter when loading the JS SDK
2. to the createOrder api call (`actions.order.create`)

Here's the currency storybook currency example: https://paypal.github.io/react-paypal-js/?path=/story/example-usepaypalscriptreducer--currency
