### ISSUE TITLE
[Bug] Currency change not reliable

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/react-paypal-js#96]
### 🐞 Describe the Bug

It seems that if you add the `dispatch` on the `useEffect` to change the currency, and it triggers 2 times fastly, it doesn't get the correct currency reliably. 

### 🔬 Minimal Reproduction

We have a context, and we have a `defaultCurrency`, and a `selectedCurrency`, that is loaded from the server, so it initializes as `GBP` (default currency), and then fastly goes to `EUR` (as an example of selected currency that came from the server, on an API call)

### 😕 Actual Behavior

Creates the order as `GBP`

### 🤔 Expected Behavior

Should create the order in `EUR`

### ➕ Additional Context

What we did to fix this race condition was adding a check on the `useEffect`, like this:

```js
  useEffect(() => {
    if (selectedCurrency !== defaultCurrency) {
      paypalDispatch({
        type: "resetOptions",
        value: {
          ...options,
          currency: selectedCurrency,
        },
      });
    }
  }, [selectedCurrency]);
```

Then it works reliably.

So either we have to add it to the documentation, or create a solution for it

**Comment by gregjopa** [comment]
Hi @pedroapfilho can you provide a full example of the problem? Perhaps you can update the Storybook Currency example to demostrate the issue: https://paypal.github.io/react-paypal-js/iframe.html?id=example-usepaypalscriptreducer--currency&viewMode=story.

**Comment by gregjopa** [comment]
The other thing that comes to mind is to add a check to make sure the script is finished loading before dispatching the `resetOptions` action. I'm wondering if the problem is the script is still loading when you try to dispatch this event so it doesn't get picked up properly because of this code: https://github.com/paypal/react-paypal-js/blob/main/src/ScriptContext.tsx#L101

If so, adding this check should resolve the issue.

```js
if (isResolved && selectedCurrency !== defaultCurrency) {
    paypalDispatch({
    type: "resetOptions",
    value: {
        ...options,
        currency: selectedCurrency,
    },
    });
}
```

**Comment by pedroapfilho** [comment]
Hello @gregjopa sorry for not providing the example right away, I was in the middle of the investigation, and just thought about it.

What we actually could do is say to the users to:

```
If you run the `resetOptions` inside a `useEffect` call, you must add an if statement inside to check if the previous script was already resolved, because this can cause a race-condition and make the call not very reliable.
```

**Comment by pedroapfilho** [comment]
I'll create an example on the storybook today, stay tuned for the PR.

**Comment by gregjopa** [comment]
Do you think this feature request would help your use case with setting currency later on after defining the Script Provider? https://github.com/paypal/react-paypal-js/issues/89.

**Comment by pedroapfilho** [comment]
Yes and no.

It could help if we wanted to lazy load the component until we have the currency figured out, or we can basically trigger it after `isResolved`, just like you added on your comment.
