### ISSUE TITLE
[Feature] forceRerender as an array

### ISSUE THREAD

**Issue by pedroapfilho** [paypal/react-paypal-js#98]
Right now we have only one property on the `forceRerender` prop, I had to add my `createOrder` function to it, which is an `useCallback` function, and it respects the array of properties of it to force the rerender.

I think we can make it more readable/reliable if we make the `forceRerender` be an array, so we can pass as many properties to it as we want, and it would be very easy to implement.

**Comment by gregjopa** [comment]
Hey @pedroapfilho, sure I'm open to adding this feature with turning the `forceRerender` prop into an array. Right now we expect this prop to be a primitive value so it would be a breaking change. Would you be up for sending a PR for adding this feature?

**Comment by pedroapfilho** [comment]
I would! This change is very simple! I'll do it today at night!
