### ISSUE TITLE
[Bug] onError() not being called in Inline card form

### ISSUE THREAD

**Issue by bruno-silva5** [paypal/react-paypal-js#99]
### 🐞 Describe the Bug

Can't handle error when there is invalid data in the form. If the user insert invalid data, like an postal code = "111111111111111111", it just shows a message in console and "onError()" is not called, if I try to .catch() in my API calls to server-side when capturing, does not work too.

### 🔬 Minimal Reproduction

In the card form, insert a zip code like: "111111111111111111", click in Continue. 

### 😕 Actual Behavior

console logs returns:

ppxo_inline_guest_unhandled_error 
Object { handledErrors: (1) […], unhandledErrors: [], inline_guest_version: "2.12.7", timestamp: 1617132129038, windowID: "36382bffb2", pageID: "5e8b1ce512", referer: "www.sandbox.paypal.com", host: "www.sandbox.paypal.com", path: "/smart/card-fields", env: "sandbox", … }
beaver-logger.js:237:35
    s beaver-logger.js:237
    u beaver-logger.js:396
    p beaver-logger.js:443
    error index.js:90
    H submitInlineGuestForm.js:339
    value Redux
    H submitInlineGuestForm.js:327
    Redux 2
    errorBoundaryMiddleware errorBoundaryMiddleware.js:15
    ignoreNoopActionMiddleware noopActionCreator.js:25
    Redux 2
    r runtime.js:62
    l runtime.js:296
    t runtime.js:114

### 🤔 Expected Behavior

onError() be called, so I could manage the error and display an message showing to the user what field is wrong.

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  | 5.1.1
| Firefox          | 87.0
| Ubuntu | 20.04.2 LTS

**Comment by gregjopa** [comment]
Hi @bruno-silva5 thanks for reporting. This is an issue with the JS SDK and not this react library so let's track this issue here instead: https://github.com/paypal/paypal-checkout-components/issues/1550. I'll work with the right folks at PayPal to get this fixed.
